import type { TimelineEventType } from '@/lib/types/crm';
import {
  Mail,
  MailOpen,
  MousePointer,
  AlertOctagon,
  BellOff,
  MessageSquare,
  CheckCircle2,
  XCircle,
  Phone,
  StickyNote,
  GitBranch,
  ListPlus,
  ListChecks,
  Wallet,
  CircleDollarSign,
  Undo2,
  Megaphone,
  CircleCheck,
  Target,
  Trophy,
  TimerOff,
  FileSignature,
  PenLine,
  FileX2,
  Briefcase,
  Handshake,
  ShieldCheck,
  Zap,
  ZapOff,
  CircleX,
  Send,
} from 'lucide-react';

type Visual = { icon: typeof Mail; color: string; label: string };

const VISUALS: Record<TimelineEventType, Visual> = {
  email_sent:           { icon: Mail,           color: 'text-blue-400',    label: 'Email sent' },
  email_opened:         { icon: MailOpen,       color: 'text-blue-300',    label: 'Email opened' },
  email_clicked:        { icon: MousePointer,   color: 'text-cyan-300',    label: 'Email link clicked' },
  email_bounced:        { icon: AlertOctagon,   color: 'text-red-400',     label: 'Email bounced' },
  email_unsubscribed:   { icon: BellOff,        color: 'text-red-300',     label: 'Email unsubscribed' },
  sms_sent:             { icon: MessageSquare,  color: 'text-emerald-400', label: 'SMS sent' },
  sms_delivered:        { icon: CheckCircle2,   color: 'text-emerald-300', label: 'SMS delivered' },
  sms_failed:           { icon: XCircle,        color: 'text-red-400',     label: 'SMS failed' },
  sms_received:         { icon: MessageSquare,  color: 'text-blue-400',    label: 'SMS received' },
  sms_stopped:          { icon: BellOff,        color: 'text-red-400',     label: 'STOP received' },
  call_logged:          { icon: Phone,          color: 'text-purple-300',  label: 'Call logged' },
  note_added:           { icon: StickyNote,     color: 'text-yellow-300',  label: 'Note added' },
  stage_changed:        { icon: GitBranch,      color: 'text-indigo-300',  label: 'Stage changed' },
  task_created:         { icon: ListPlus,       color: 'text-blue-300',    label: 'Task created' },
  task_completed:       { icon: ListChecks,     color: 'text-emerald-300', label: 'Task completed' },
  deposit_initiated:    { icon: Wallet,         color: 'text-orange-300',  label: 'Deposit initiated' },
  deposit_paid:         { icon: CircleDollarSign, color: 'text-emerald-400', label: 'Deposit paid' },
  deposit_refunded:     { icon: Undo2,          color: 'text-amber-400',   label: 'Deposit refunded' },
  auction_started:      { icon: Megaphone,      color: 'text-blue-400',    label: 'Auction started' },
  auction_closed:       { icon: CircleCheck,    color: 'text-blue-300',    label: 'Auction closed' },
  offer_received:       { icon: Target,         color: 'text-purple-400',  label: 'Offer received' },
  offer_selected:       { icon: Trophy,         color: 'text-emerald-400', label: 'Offer selected' },
  offer_expired:        { icon: TimerOff,       color: 'text-gray-400',    label: 'Offer expired' },
  contract_sent:        { icon: FileSignature,  color: 'text-blue-400',    label: 'Contract sent' },
  docusign_signed:      { icon: PenLine,        color: 'text-emerald-400', label: 'Contract signed' },
  docusign_declined:    { icon: FileX2,         color: 'text-red-400',     label: 'Contract declined' },
  dealer_action:        { icon: Briefcase,      color: 'text-cyan-300',    label: 'Dealer action' },
  affiliate_action:     { icon: Handshake,      color: 'text-pink-300',    label: 'Affiliate action' },
  admin_action:         { icon: ShieldCheck,    color: 'text-gray-300',    label: 'Admin action' },
  automation_triggered: { icon: Zap,            color: 'text-yellow-300',  label: 'Automation triggered' },
  automation_completed: { icon: CircleCheck,    color: 'text-emerald-300', label: 'Automation completed' },
  automation_exited:    { icon: ZapOff,         color: 'text-gray-400',    label: 'Automation exited' },
  campaign_sent:        { icon: Send,           color: 'text-blue-300',    label: 'Campaign sent' },
  campaign_opened:      { icon: MailOpen,       color: 'text-cyan-300',    label: 'Campaign opened' },
  campaign_clicked:     { icon: MousePointer,   color: 'text-cyan-200',    label: 'Campaign clicked' },
};

const FALLBACK: Visual = { icon: CircleX, color: 'text-gray-500', label: 'Event' };

export function timelineVisual(type: TimelineEventType): Visual {
  return VISUALS[type] ?? FALLBACK;
}
