import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, Calculator } from "lucide-react";

import { prisma } from "@/lib/prisma";
import { buildPageMetadata } from "@/lib/seo/metadata";
import {
  JsonLd,
  articleSchema,
  faqSchema,
  breadcrumbSchema,
} from "@/lib/seo/jsonld";
import { getPillarLinksForCluster } from "@/lib/seo/pillar-links";
import {
  rankRelatedArticles,
  RELATED_LINK_LIMIT,
  type RelatedArticleCandidate,
  type RelatedArticleLink,
} from "@/lib/seo/internal-links";
import { splitBodyForMidCta } from "@/lib/seo/article-body";
import ContentTracker from "@/components/analytics/ContentTracker";
import ArticleCTA from "@/components/content/ArticleCTA";
import RelatedArticles from "@/components/content/RelatedArticles";

// Phase C1 — programmatic buying-guide article route. Serves any PUBLISHED
// ContentArticle generated by the Phase C2 engine. The six cornerstone pillar
// pages live at their own static routes and take precedence over this dynamic
// segment, so this only ever resolves programmatic slugs.
//
// ISR keeps DB reads off the hot path while still picking up newly published
// articles within the revalidation window.
export const revalidate = 3600;

const CALCULATOR_URL = "/tools/dealer-fee-calculator";

interface PageProps {
  params: Promise<{ slug: string }>;
}

interface ArticleFaq {
  question: string;
  answer: string;
}

type Article = NonNullable<Awaited<ReturnType<typeof loadArticle>>>;

async function loadArticle(slug: string) {
  try {
    return await prisma.contentArticle.findFirst({
      where: { slug, status: "PUBLISHED" },
    });
  } catch {
    // DB unavailable (e.g. at build time) — treat as not found.
    return null;
  }
}

// Phase C4 — fetch a candidate pool of other published articles (same vehicle,
// same city, or same cluster) and rank it into the lateral internal-link set.
// The candidate query is intentionally broad; the ranking (pure, tested) trims
// it to a small, varied set in lib/seo/internal-links.ts.
async function loadRelatedArticles(current: Article): Promise<RelatedArticleLink[]> {
  const candidateWhere = {
    status: "PUBLISHED" as const,
    slug: { not: current.slug },
    OR: [
      { city: current.city, state: current.state },
      ...(current.make && current.model
        ? [{ make: current.make, model: current.model }]
        : []),
      { cluster: current.cluster },
    ],
  };

  let candidates: RelatedArticleCandidate[] = [];
  try {
    candidates = await prisma.contentArticle.findMany({
      where: candidateWhere,
      select: {
        slug: true,
        title: true,
        h1: true,
        cluster: true,
        make: true,
        model: true,
        city: true,
        state: true,
        metro: true,
      },
      // Over-fetch a bounded pool, then rank in JS. Newest first as a sensible
      // pre-ranking bias for ties at the DB level.
      orderBy: { publishedAt: "desc" },
      take: 48,
    });
  } catch {
    return [];
  }

  return rankRelatedArticles(
    {
      slug: current.slug,
      title: current.title,
      h1: current.h1,
      cluster: current.cluster,
      make: current.make,
      model: current.model,
      city: current.city,
      state: current.state,
      metro: current.metro,
    },
    candidates,
    RELATED_LINK_LIMIT,
  );
}

function parseFaqs(faqJson: string | null): ArticleFaq[] {
  if (!faqJson) return [];
  try {
    const parsed = JSON.parse(faqJson);
    if (!Array.isArray(parsed)) return [];
    return parsed
      .filter(
        (f): f is ArticleFaq =>
          typeof f?.question === "string" && typeof f?.answer === "string",
      )
      .map((f) => ({ question: f.question, answer: f.answer }));
  } catch {
    return [];
  }
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const article = await loadArticle(slug);
  if (!article) {
    return { title: "Article not found | AutoLenis", robots: { index: false, follow: false } };
  }
  return buildPageMetadata({
    title: article.title,
    description: article.metaDescription,
    path: `/buying-guide/${slug}`,
  });
}

export default async function BuyingGuideArticlePage({ params }: PageProps) {
  const { slug } = await params;
  const article = await loadArticle(slug);
  if (!article) notFound();

  const faqs = parseFaqs(article.faqJson);
  const pillars = getPillarLinksForCluster(article.cluster);
  const related = await loadRelatedArticles(article);
  const cityState = article.state ? `${article.city}, ${article.state}` : article.city;
  const bodyParts = splitBodyForMidCta(article.body);

  return (
    <>
      <ArticleSchemas article={article} faqs={faqs} slug={slug} />
      <ContentTracker
        articleSlug={slug}
        cluster={article.cluster}
        city={article.city}
        state={article.state}
      />

      <article
        className="mx-auto max-w-3xl px-6 md:px-8 pt-28 pb-20 md:pt-36"
        data-testid="buying-guide-article"
      >
        {/* Header + named-author byline (E-E-A-T) */}
        <header className="mb-10">
          <p className="text-xs tracking-widest uppercase font-semibold text-[#0B5FD1] mb-4">
            Buying Guide{cityState ? ` · ${cityState}` : ""}
          </p>
          <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-[#111827] tracking-tight leading-[1.1] mb-6">
            {article.h1}
          </h1>
          <div className="text-sm text-[#6B7280]">
            By{" "}
            <Link href="/author/markist" className="text-[#0B5FD1] font-medium hover:underline">
              Markist, Founder of AutoLenis
            </Link>
          </div>
        </header>

        {/* Above-fold conversion element — state- and vehicle-aware, tracked */}
        <ArticleCTA
          articleSlug={slug}
          cluster={article.cluster}
          city={article.city}
          state={article.state}
          make={article.make}
          model={article.model}
          position="above_fold"
        />

        {/* Generated body — split at the mid-point so a CTA sits mid-page */}
        <div className="pillar-body space-y-6 text-[#374151] leading-relaxed [&_h2]:text-2xl [&_h2]:font-bold [&_h2]:text-[#111827] [&_h2]:tracking-tight [&_h2]:mb-4 [&_h2]:mt-10 [&_h3]:text-lg [&_h3]:font-semibold [&_h3]:text-[#111827] [&_h3]:mb-2 [&_h3]:mt-6 [&_p]:mb-4 [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:space-y-2 [&_ul]:mb-4 [&_ol]:list-decimal [&_ol]:pl-6 [&_ol]:space-y-2 [&_ol]:mb-4 [&_a]:text-[#0B5FD1] [&_a]:font-medium hover:[&_a]:underline [&_strong]:text-[#111827]">
          <div dangerouslySetInnerHTML={{ __html: bodyParts.before }} />
          {bodyParts.didSplit && (
            <ArticleCTA
              articleSlug={slug}
              cluster={article.cluster}
              city={article.city}
              state={article.state}
              make={article.make}
              model={article.model}
              position="mid_page"
            />
          )}
          {bodyParts.after && (
            <div dangerouslySetInnerHTML={{ __html: bodyParts.after }} />
          )}
        </div>

        {/* State-aware dealer fee calculator — relevant on every cluster */}
        <Link
          href={CALCULATOR_URL}
          data-testid="article-calculator-link"
          className="mt-10 flex items-center gap-4 rounded-2xl border border-[#E5E7EB] bg-white px-6 py-5 hover:border-[#0B5FD1] hover:shadow-sm transition-all"
        >
          <span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[#F0F7FF] text-[#0B5FD1]">
            <Calculator size={20} />
          </span>
          <span className="flex-1">
            <span className="block text-sm font-semibold text-[#111827]">
              Check any fee against {article.state || "your state"}&apos;s rules
            </span>
            <span className="block text-sm text-[#6B7280]">
              Free dealer fee calculator — is that fee required, negotiable, or junk?
            </span>
          </span>
          <ArrowRight size={16} className="shrink-0 text-[#0B5FD1]" />
        </Link>

        {/* Bottom conversion element — state- and vehicle-aware, tracked */}
        <ArticleCTA
          articleSlug={slug}
          cluster={article.cluster}
          city={article.city}
          state={article.state}
          make={article.make}
          model={article.model}
          position="bottom"
        />

        {/* FAQ */}
        {faqs.length > 0 && (
          <section className="mt-16" data-testid="article-faq">
            <h2 className="text-2xl font-bold text-[#111827] tracking-tight mb-6">
              Frequently Asked Questions
            </h2>
            <div className="divide-y divide-[#E5E7EB] border-t border-[#E5E7EB]">
              {faqs.map((f) => (
                <div key={f.question} className="py-5">
                  <h3 className="text-base font-semibold text-[#111827] mb-2">{f.question}</h3>
                  <p className="text-[#4B5563] leading-relaxed">{f.answer}</p>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* Lateral internal links — related programmatic articles */}
        <RelatedArticles links={related} />

        {/* Internal links — cluster pillar pages */}
        {pillars.length > 0 && (
          <section className="mt-16" data-testid="article-related">
            <h2 className="text-xl font-bold text-[#111827] tracking-tight mb-5">
              Keep reading
            </h2>
            <ul className="grid sm:grid-cols-2 gap-4">
              {pillars.map((p) => (
                <li key={p.slug}>
                  <Link
                    href={p.url}
                    className="block rounded-xl border border-[#E5E7EB] bg-white p-5 hover:border-[#0B5FD1] hover:shadow-sm transition-all"
                  >
                    <span className="text-sm font-semibold text-[#111827]">{p.title}</span>
                    <span className="mt-1 flex items-center gap-1 text-xs text-[#0B5FD1]">
                      Read guide <ArrowRight size={12} />
                    </span>
                  </Link>
                </li>
              ))}
            </ul>
          </section>
        )}
      </article>
    </>
  );
}

function ArticleSchemas({
  article,
  faqs,
  slug,
}: {
  article: Article;
  faqs: ArticleFaq[];
  slug: string;
}) {
  return (
    <>
      <JsonLd
        id={`article-${slug}`}
        data={articleSchema({
          headline: article.title,
          description: article.metaDescription,
          slug,
          datePublished: article.publishedAt?.toISOString(),
          dateModified: article.updatedAt?.toISOString(),
        })}
      />
      {faqs.length > 0 && <JsonLd id={`article-faq-${slug}`} data={faqSchema(faqs)} />}
      <JsonLd
        id={`article-breadcrumb-${slug}`}
        data={breadcrumbSchema([
          { name: "Buying Guide", path: "/buying-guide" },
          { name: article.h1, path: `/buying-guide/${slug}` },
        ])}
      />
    </>
  );
}
