-- PRODUCTION PHYSICAL SCHEMA — schema only, no data, no credentials.
--
-- Synthesised read-only from production's pg_catalog on 2026-09-03. `pg_dump` could not be used:
-- this session holds no production DSN, and the available client is 16.13, which refuses to dump a
-- 17.6 server. Every statement below was generated by a SELECT against catalog views; no row of
-- application data, no role password and no connection string is reproduced anywhere in this file.
--
-- WHAT THIS PROVES AND WHAT IT DOES NOT. This is the PHYSICAL schema: types, tables, columns,
-- defaults, constraints, indexes, functions, triggers, RLS and policies. It says nothing about
-- whether `_prisma_migrations` is correct — ledger correctness is a separate question (§6), and a
-- restore of this file deliberately carries no ledger at all.

CREATE SCHEMA IF NOT EXISTS extensions;
-- Supabase-managed schemas the application schema references only indirectly.
CREATE SCHEMA IF NOT EXISTS vault;
