CREATE TABLE public.buyer_offer_review_items (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  buyer_offer_review_id text NOT NULL,
  dealer_submission_id text NOT NULL,
  vehicle_index integer DEFAULT 0 NOT NULL,
  status text DEFAULT 'PENDING'::text NOT NULL,
  responded_at timestamp without time zone,
  buyer_note text
);
CREATE TABLE public.buyer_offer_reviews (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  review_token text DEFAULT (gen_random_uuid())::text NOT NULL,
  vehicle_offer_id text NOT NULL,
  buyer_email text NOT NULL,
  buyer_name text NOT NULL,
  admin_message text,
  sent_at timestamp without time zone DEFAULT now() NOT NULL,
  expires_at timestamp without time zone
);
CREATE TABLE public.buyer_opportunities (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  session_id text NOT NULL,
  conversation_id text,
  buyer_id text,
  phone text,
  first_name text,
  vehicle_type text,
  make text,
  model text,
  body_style text,
  year_min integer,
  year_max integer,
  "trim" text,
  budget_type text,
  budget_amount integer,
  monthly_payment integer,
  timeline text,
  zip text,
  has_trade_in boolean,
  trade_in_details jsonb,
  financing_needed boolean,
  messages jsonb DEFAULT '[]'::jsonb NOT NULL,
  completed boolean DEFAULT false NOT NULL,
  lead_score integer,
  lead_temperature text,
  scoring_reason text,
  founder_notified boolean DEFAULT false NOT NULL,
  buyer_sms_sent boolean DEFAULT false NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  email text,
  buyer_email_sent boolean DEFAULT false NOT NULL,
  founder_email_sent boolean DEFAULT false NOT NULL,
  market_msrp_estimate integer,
  market_avg_paid_price integer,
  market_typical_markup text,
  market_good_deal_target integer,
  market_notes text,
  market_enriched_at timestamp with time zone,
  source text,
  call_reason text,
  consent_sms boolean DEFAULT false,
  consent_at timestamp with time zone,
  intake_processed_at timestamp(3) without time zone,
  intake_attempts integer DEFAULT 0 NOT NULL,
  intake_failed_at timestamp(3) without time zone,
  intake_failure_reason text
);
CREATE TABLE public.buyer_preferences (
  id text NOT NULL,
  buyer_id text NOT NULL,
  email_notifications boolean DEFAULT true NOT NULL,
  sms_notifications boolean DEFAULT false NOT NULL,
  marketing_emails boolean DEFAULT false NOT NULL,
  auction_alerts boolean DEFAULT true NOT NULL,
  deal_updates boolean DEFAULT true NOT NULL,
  created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at timestamp(3) without time zone NOT NULL,
  vehicle_type_preference text,
  new_or_used_preference text
);
CREATE TABLE public.buyer_request_claim_tokens (
  id text NOT NULL,
  token_hash text NOT NULL,
  buyer_id text NOT NULL,
  vehicle_request_id text,
  expires_at timestamp(3) without time zone NOT NULL,
  consumed_at timestamp(3) without time zone,
  created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE public.buyers (
  id text NOT NULL,
  user_id text NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  phone text,
  address text,
  city text,
  state text,
  zip text,
  onboarding_complete boolean DEFAULT false NOT NULL,
  terms_accepted_at timestamp(3) without time zone,
  terms_version text,
  profile_picture_url text,
  employment_status text,
  income_range text,
  affiliate_id text,
  created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at timestamp(3) without time zone NOT NULL,
  plan "BuyerPlan" DEFAULT 'STANDARD'::"BuyerPlan" NOT NULL,
  plan_upgraded_at timestamp(3) without time zone,
  archived_at timestamp(3) without time zone,
  disabled_at timestamp(3) without time zone,
  purged_at timestamp(3) without time zone,
  is_suspended boolean DEFAULT false NOT NULL,
  suspended_at timestamp(3) without time zone,
  suspended_reason text,
  account_status text DEFAULT 'ACTIVE'::text NOT NULL,
  is_guest boolean DEFAULT false NOT NULL,
  lead_score integer,
  lead_temperature text,
  sequence_paused boolean DEFAULT false NOT NULL,
  opted_out_sms boolean DEFAULT false NOT NULL,
  timezone text
);
CREATE TABLE public.campaign_recipients (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  campaign_id uuid NOT NULL,
  contact_id uuid NOT NULL,
  status text DEFAULT 'pending'::text NOT NULL,
  sent_at timestamp with time zone,
  delivered_at timestamp with time zone,
  opened_at timestamp with time zone,
  clicked_at timestamp with time zone,
  unsubscribed_at timestamp with time zone,
  error_message text,
  resend_id text,
  twilio_sid text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.campaigns (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  name text NOT NULL,
  type text NOT NULL,
  status text DEFAULT 'draft'::text NOT NULL,
  segment_id uuid,
  template_id uuid,
  sms_body text,
  scheduled_at timestamp with time zone,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  recipient_count integer DEFAULT 0 NOT NULL,
  sent_count integer DEFAULT 0 NOT NULL,
  delivered_count integer DEFAULT 0 NOT NULL,
  opened_count integer DEFAULT 0 NOT NULL,
  clicked_count integer DEFAULT 0 NOT NULL,
  bounced_count integer DEFAULT 0 NOT NULL,
  failed_count integer DEFAULT 0 NOT NULL,
  unsubscribed_count integer DEFAULT 0 NOT NULL,
  suppressed_count integer DEFAULT 0 NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.circumvention_attempts (
  id text NOT NULL,
  thread_id text NOT NULL,
  message_id text NOT NULL,
  user_id text NOT NULL,
  flag "AntiCircumventionFlag" NOT NULL,
  pattern text NOT NULL,
  detected_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  resolved boolean DEFAULT false NOT NULL,
  resolved_by text
);
CREATE TABLE public.commissions (
  id text NOT NULL,
  affiliate_id text NOT NULL,
  deal_id text NOT NULL,
  level integer NOT NULL,
  rate double precision NOT NULL,
  amount_cents integer NOT NULL,
  status "CommissionStatus" DEFAULT 'PENDING'::"CommissionStatus" NOT NULL,
  qualifying_event_id text NOT NULL,
  paid_at timestamp(3) without time zone,
  created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at timestamp(3) without time zone NOT NULL,
  basis_cents integer,
  payout_id text,
  approved_at timestamp(3) without time zone,
  approved_by text,
  reversed_at timestamp(3) without time zone
);
CREATE TABLE public.comms_outbox (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  channel text NOT NULL,
  dedup_key text NOT NULL,
  status text DEFAULT 'pending'::text NOT NULL,
  payload jsonb NOT NULL,
  attempts integer DEFAULT 0 NOT NULL,
  last_error text,
  last_result text,
  provider_id text,
  run_at timestamp with time zone DEFAULT now() NOT NULL,
  claimed_at timestamp with time zone,
  dispatched_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.competitor_insights (
  id text NOT NULL,
  competitor text NOT NULL,
  topic text NOT NULL,
  content_type text NOT NULL,
  estimated_engagement text NOT NULL,
  opportunity text NOT NULL,
  suggested_hook text DEFAULT ''::text NOT NULL,
  signal_created boolean DEFAULT false NOT NULL,
  week_of text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.compliance_events (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  event_type text NOT NULL,
  buyer_id text NOT NULL,
  prequal_application_id text,
  metadata jsonb,
  created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE public.compliance_rules (
  id text NOT NULL,
  rule_type "ComplianceRuleType" NOT NULL,
  version integer DEFAULT 1 NOT NULL,
  status "ComplianceRuleStatus" DEFAULT 'DRAFT'::"ComplianceRuleStatus" NOT NULL,
  content jsonb,
  template_body text,
  source text,
  effective_at timestamp(3) without time zone,
  created_by text,
  activated_by text,
  activated_at timestamp(3) without time zone,
  created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE public.contact_identities (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  contact_id uuid NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid NOT NULL,
  is_primary boolean DEFAULT false NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.contact_timeline_events (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  contact_id uuid NOT NULL,
  event_type text NOT NULL,
  event_data jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.contacts (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  email text,
  phone text,
  first_name text,
  last_name text,
  source text NOT NULL,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  source_url text,
  ip_address inet,
  consent_sms boolean DEFAULT false NOT NULL,
  consent_email boolean DEFAULT false NOT NULL,
  consent_at timestamp with time zone,
  consent_ip inet,
  consent_text text,
  lifecycle_stage text DEFAULT 'lead'::text NOT NULL,
  do_not_contact boolean DEFAULT false NOT NULL,
  tags text[] DEFAULT '{}'::text[],
  notes text,
  assigned_to uuid,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  lead_score integer,
  lead_temperature text,
  nurture_status text DEFAULT 'none'::text NOT NULL,
  last_contacted_at timestamp with time zone
);
