CREATE TABLE public.dealer_capacity_configs (
  id text NOT NULL,
  dealer_id text NOT NULL,
  max_auction_load integer DEFAULT 5 NOT NULL,
  preferred_makes text[],
  preferred_price_min integer,
  preferred_price_max integer,
  updated_at timestamp(3) without time zone NOT NULL
);
CREATE TABLE public.dealer_contact_profiles (
  id text NOT NULL,
  rooftop_id text NOT NULL,
  name text,
  name_key text,
  title text,
  email text,
  email_key text,
  phone text,
  phone_key text,
  email_source text,
  email_verification_status text,
  email_verified_at timestamp(3) without time zone,
  contact_source text,
  contact_confidence text,
  last_verified_at timestamp(3) without time zone,
  created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at timestamp(3) without time zone NOT NULL,
  apollo_person_id text,
  apollo_organization_id text,
  apollo_last_synced_at timestamp(3) without time zone,
  linkedin_url text,
  dnc_status text,
  dnc_checked_at timestamp(3) without time zone,
  phone_type text,
  consent_basis text DEFAULT 'NONE'::text NOT NULL,
  consent_basis_set_at timestamp(3) without time zone,
  consent_basis_source text,
  is_primary_contact boolean DEFAULT false NOT NULL
);
CREATE TABLE public.dealer_discoveries (
  id text NOT NULL,
  dealer_name text NOT NULL,
  city text,
  state text,
  discovered_from text NOT NULL,
  inventory_count integer DEFAULT 0 NOT NULL,
  status "DealerDiscoveryStatus" DEFAULT 'DISCOVERED'::"DealerDiscoveryStatus" NOT NULL,
  contacted_at timestamp(3) without time zone,
  invited_at timestamp(3) without time zone,
  notes text,
  created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at timestamp(3) without time zone NOT NULL
);
CREATE TABLE public.dealer_feed_configs (
  id text NOT NULL,
  dealer_id text NOT NULL,
  feed_url text NOT NULL,
  format "FeedFormat" NOT NULL,
  refresh_interval_hours integer DEFAULT 24 NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  last_sync_at timestamp(3) without time zone,
  last_sync_status text,
  created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at timestamp(3) without time zone NOT NULL
);
CREATE TABLE public.dealer_intelligence (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  dealer_name text NOT NULL,
  brand text NOT NULL,
  city text NOT NULL,
  state text NOT NULL,
  zip text NOT NULL,
  latitude double precision,
  longitude double precision,
  website text,
  inventory_signal text DEFAULT 'normal'::text NOT NULL,
  dealer_density_score double precision,
  dealers_within_30mi integer,
  data_source text NOT NULL,
  last_updated timestamp with time zone DEFAULT now() NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.dealer_invitations (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  dealership_name text NOT NULL,
  contact_name text NOT NULL,
  email text NOT NULL,
  personal_message text,
  token text,
  expires_at timestamp(3) without time zone NOT NULL,
  status "DealerInvitationStatus" DEFAULT 'PENDING'::"DealerInvitationStatus" NOT NULL,
  invited_by text NOT NULL,
  accepted_at timestamp(3) without time zone,
  dealer_id text,
  created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  token_hash text,
  consumed_at timestamp(3) without time zone
);
CREATE TABLE public.dealer_licenses (
  id text NOT NULL,
  dealer_id text NOT NULL,
  license_num text NOT NULL,
  state text NOT NULL,
  expires_at timestamp(3) without time zone,
  document_url text,
  is_active boolean DEFAULT true NOT NULL,
  created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE public.dealer_offer_submissions (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  vehicle_offer_id text NOT NULL,
  dealership_name text NOT NULL,
  contact_name text NOT NULL,
  contact_email text NOT NULL,
  contact_phone text NOT NULL,
  vehicles jsonb DEFAULT '[]'::jsonb NOT NULL,
  notes text,
  submitted_at timestamp without time zone DEFAULT now() NOT NULL,
  invite_id text,
  rejected boolean DEFAULT false,
  rejected_at timestamp without time zone,
  dealer_id text,
  documents jsonb
);
CREATE TABLE public.dealer_outreach_log (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  dealer_prospect_id text NOT NULL,
  outreach_type text NOT NULL,
  channel text NOT NULL,
  subject text,
  body text,
  to_email text,
  from_email text,
  resend_id text,
  status text NOT NULL,
  error_message text,
  sent_at timestamp without time zone DEFAULT now(),
  delivered_at timestamp without time zone,
  replied_at timestamp without time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  outreach_sequence_step integer DEFAULT 1,
  follow_up_scheduled_at timestamp without time zone,
  reply_detected_at timestamp without time zone,
  to_phone text,
  from_phone text,
  twilio_sid text,
  call_disposition text,
  call_duration_seconds integer,
  consent_basis text
);
CREATE TABLE public.dealer_payments (
  id text NOT NULL,
  dealer_id text NOT NULL,
  deal_id text,
  amount_cents integer NOT NULL,
  type text NOT NULL,
  status text DEFAULT 'PENDING'::text NOT NULL,
  processed_at timestamp(3) without time zone,
  created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE public.dealer_prospects (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  buyer_opp_id text,
  name text NOT NULL,
  address text,
  city text,
  state text,
  zip text,
  phone text,
  email text,
  website text,
  brand text,
  source_url text,
  search_score double precision,
  distance_miles double precision,
  status "DealerProspectStatus" DEFAULT 'DISCOVERED'::"DealerProspectStatus" NOT NULL,
  outreach_draft text,
  contacted_at timestamp with time zone,
  replied_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  outreach_script text,
  script_drafted_at timestamp with time zone,
  script_attempts integer DEFAULT 0 NOT NULL,
  founder_notes text,
  scripted_at timestamp with time zone,
  onboarded_at timestamp with time zone,
  dead_at timestamp with time zone,
  dead_reason text,
  email_source text,
  email_enriched_at timestamp without time zone,
  reply_detected_at timestamp without time zone,
  sequence_paused_at timestamp without time zone,
  sequence_pause_reason text,
  contact_name text,
  contact_title text,
  contact_phone text,
  contact_linkedin text,
  apollo_enriched_at timestamp with time zone,
  apollo_confidence double precision,
  enrichment_source text,
  contact_source_url text,
  contact_source text,
  contact_confidence text,
  contact_enriched_at timestamp(3) without time zone,
  claim_token text,
  claim_token_expires_at timestamp(3) without time zone,
  converted_application_id text,
  email_verified_at timestamp(3) without time zone,
  email_verification_status text,
  latitude double precision,
  longitude double precision,
  rooftop_id text
);
CREATE TABLE public.dealer_rooftops (
  id text NOT NULL,
  display_name text NOT NULL,
  name_key text NOT NULL,
  website_host text,
  phone_key text,
  name_zip_key text,
  name_city_state_key text,
  zip text,
  city text,
  state text,
  latitude double precision,
  longitude double precision,
  makes text[] DEFAULT ARRAY[]::text[] NOT NULL,
  makes_source text,
  created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at timestamp(3) without time zone NOT NULL
);
CREATE TABLE public.dealer_scorecard_snapshots (
  id text NOT NULL,
  dealer_id text NOT NULL,
  tier text NOT NULL,
  offer_win_rate double precision NOT NULL,
  deal_completion_rate double precision NOT NULL,
  auction_response_rate double precision NOT NULL,
  avg_response_hours double precision NOT NULL,
  junk_fee_ratio double precision NOT NULL,
  snapshot_date timestamp(3) without time zone NOT NULL,
  created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE public.dealer_scorecard_weights (
  id text NOT NULL,
  name text DEFAULT 'default'::text NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  weight_win_rate double precision DEFAULT 0.35 NOT NULL,
  weight_completion double precision DEFAULT 0.25 NOT NULL,
  weight_response double precision DEFAULT 0.20 NOT NULL,
  weight_junk_fees double precision DEFAULT 0.20 NOT NULL,
  created_by text,
  updated_at timestamp(3) without time zone NOT NULL
);
CREATE TABLE public.dealer_verifications (
  id text NOT NULL,
  dealer_id text NOT NULL,
  license_num text,
  state text,
  verified boolean DEFAULT false NOT NULL,
  verified_at timestamp(3) without time zone,
  verified_by text,
  documents jsonb DEFAULT '[]'::jsonb NOT NULL,
  created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE public.dealers (
  id text NOT NULL,
  user_id text NOT NULL,
  dealership_name text NOT NULL,
  phone text,
  address text,
  city text,
  state text,
  zip text,
  status "DealerStatus" DEFAULT 'PENDING'::"DealerStatus" NOT NULL,
  tier text DEFAULT 'STANDARD'::text NOT NULL,
  current_auction_load integer DEFAULT 0 NOT NULL,
  scorecard_tier text,
  created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at timestamp(3) without time zone NOT NULL,
  license_number text,
  agreed_to_terms_at timestamp(3) without time zone,
  onboarding_step text DEFAULT 'BUSINESS_INFO'::text NOT NULL,
  marketplace_agreement_envelope_id text,
  marketplace_agreement_sent_at timestamp without time zone,
  marketplace_agreement_signed_at timestamp without time zone,
  is_system_placeholder boolean DEFAULT false NOT NULL,
  latitude double precision,
  longitude double precision,
  rooftop_id text
);
CREATE TABLE public.deals (
  id text NOT NULL,
  buyer_id text NOT NULL,
  offer_id text,
  status "DealStatus" DEFAULT 'PENDING'::"DealStatus" NOT NULL,
  financing_path text,
  insurance_status "InsuranceStatus" DEFAULT 'NOT_STARTED'::"InsuranceStatus" NOT NULL,
  fee_paid_at timestamp(3) without time zone,
  fee_amount_cents integer,
  stripe_fee_pi_id text,
  contract_shield_score integer,
  contract_shield_status text,
  risk_score integer,
  risk_tier "RiskTier",
  created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at timestamp(3) without time zone NOT NULL,
  fee_refunded_at timestamp with time zone,
  fee_refunded_amount_cents integer,
  admin_notes text,
  vehicle_request_offer_id text,
  dealer_award_dispatched_at timestamp(3) without time zone,
  dealer_award_attempts integer DEFAULT 0 NOT NULL
);
CREATE TABLE public.deposits (
  id text NOT NULL,
  buyer_id text NOT NULL,
  amount_cents integer NOT NULL,
  status "DepositStatus" DEFAULT 'PENDING'::"DepositStatus" NOT NULL,
  stripe_payment_intent_id text,
  stripe_session_id text,
  refunded_at timestamp(3) without time zone,
  created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at timestamp(3) without time zone NOT NULL
);
CREATE TABLE public.document_requests (
  id text NOT NULL,
  deal_id text,
  buyer_id text,
  requested_by text NOT NULL,
  document_type "DocumentType" NOT NULL,
  reason text,
  status "DocumentRequestStatus" DEFAULT 'PENDING'::"DocumentRequestStatus" NOT NULL,
  due_at timestamp(3) without time zone,
  fulfilled_at timestamp(3) without time zone,
  created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE public.document_versions (
  id text NOT NULL,
  document_id text NOT NULL,
  version integer DEFAULT 1 NOT NULL,
  url text NOT NULL,
  size_bytes integer,
  is_active boolean DEFAULT true NOT NULL,
  uploaded_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE public.documents (
  id text NOT NULL,
  buyer_id text,
  dealer_id text,
  deal_id text,
  type "DocumentType" NOT NULL,
  name text NOT NULL,
  url text NOT NULL,
  mime_type text,
  size_bytes integer,
  is_verified boolean DEFAULT false NOT NULL,
  verified_at timestamp(3) without time zone,
  verified_by text,
  uploaded_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE public.e_sign_envelope_history (
  id text NOT NULL,
  deal_id text NOT NULL,
  envelope_id text NOT NULL,
  attempt_number integer NOT NULL,
  status "ESignStatus" NOT NULL,
  document_version_id text,
  document_hash text,
  signer_user_id text,
  signer_role text,
  signer_name text,
  signer_email text,
  consented_to_electronic boolean DEFAULT false NOT NULL,
  consented_at timestamp(3) without time zone,
  signature_text text,
  signed_at timestamp(3) without time zone,
  viewed_at timestamp(3) without time zone,
  ip_address text,
  user_agent text,
  decline_reason text,
  voided_at timestamp(3) without time zone,
  void_reason text,
  expires_at timestamp(3) without time zone,
  completed_at timestamp(3) without time zone,
  certificate_pdf_path text,
  sent_at timestamp(3) without time zone,
  superseded_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  consent_policy_version text,
  consent_snapshot jsonb,
  executed_document_key text,
  executed_document_hash text,
  executed_generated_at timestamp(3) without time zone
);
CREATE TABLE public.e_sign_envelopes (
  id text NOT NULL,
  deal_id text NOT NULL,
  docusign_envelope_id text,
  status "ESignStatus" DEFAULT 'PENDING'::"ESignStatus" NOT NULL,
  sent_at timestamp(3) without time zone,
  completed_at timestamp(3) without time zone,
  voided_at timestamp(3) without time zone,
  void_reason text,
  created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at timestamp(3) without time zone NOT NULL,
  document_key text,
  document_version_id text,
  document_hash text,
  signer_user_id text,
  signer_role text,
  signer_name text,
  signer_email text,
  consented_to_electronic boolean DEFAULT false NOT NULL,
  consented_at timestamp(3) without time zone,
  signature_text text,
  signed_at timestamp(3) without time zone,
  viewed_at timestamp(3) without time zone,
  ip_address text,
  user_agent text,
  decline_reason text,
  expires_at timestamp(3) without time zone,
  certificate_pdf_path text,
  certificate_generated_at timestamp(3) without time zone,
  attempt_number integer DEFAULT 1 NOT NULL,
  consent_policy_version text,
  consent_snapshot jsonb,
  executed_document_key text,
  executed_document_hash text,
  executed_generated_at timestamp(3) without time zone,
  confirmations_sent_at timestamp(3) without time zone
);
CREATE TABLE public.email_send_logs (
  id text NOT NULL,
  idempotency_key text NOT NULL,
  recipient text NOT NULL,
  template_id text NOT NULL,
  status text DEFAULT 'SENT'::text NOT NULL,
  resend_id text,
  sent_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE public.email_suppression (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  email text NOT NULL,
  reason text NOT NULL,
  contact_id uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  suppressed_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.email_template_versions (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  template_id uuid NOT NULL,
  version integer NOT NULL,
  subject text NOT NULL,
  html_body text NOT NULL,
  text_body text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.email_templates (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  name text NOT NULL,
  subject text NOT NULL,
  category text DEFAULT 'transactional'::text NOT NULL,
  html_body text NOT NULL,
  text_body text,
  variables text[] DEFAULT '{}'::text[] NOT NULL,
  thumbnail_url text,
  status text DEFAULT 'active'::text NOT NULL,
  version integer DEFAULT 1 NOT NULL,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  template_key text
);
CREATE TABLE public.encouragement_messages (
  id text NOT NULL,
  text text NOT NULL,
  placement text NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  "order" integer DEFAULT 0 NOT NULL,
  created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at timestamp(3) without time zone NOT NULL
);
CREATE TABLE public.external_pre_approval_documents (
  id text NOT NULL,
  pre_approval_id text NOT NULL,
  document_url text NOT NULL,
  mime_type text,
  size_bytes integer,
  uploaded_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  verified_at timestamp(3) without time zone
);
CREATE TABLE public.external_pre_approvals (
  id text NOT NULL,
  buyer_id text NOT NULL,
  status "ExternalPreApprovalStatus" DEFAULT 'SUBMITTED'::"ExternalPreApprovalStatus" NOT NULL,
  lender_name text,
  approved_amount_cents integer,
  apr_rate double precision,
  term_months integer,
  expiry_date timestamp(3) without time zone,
  document_url text,
  reviewed_at timestamp(3) without time zone,
  reviewed_by text,
  rejection_reason text,
  additional_info_required text,
  created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at timestamp(3) without time zone NOT NULL
);
CREATE TABLE public.faith_content_audit_logs (
  id text NOT NULL,
  admin_id text NOT NULL,
  action text NOT NULL,
  entity_id text,
  description text NOT NULL,
  created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE public.feature_flags (
  id text NOT NULL,
  key text NOT NULL,
  enabled boolean DEFAULT false NOT NULL,
  description text,
  conditions jsonb,
  updated_by text,
  updated_at timestamp(3) without time zone NOT NULL
);
CREATE TABLE public.financing (
  id text NOT NULL,
  deal_id text NOT NULL,
  path "FinancingPath" NOT NULL,
  selected_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  lender_name text,
  approved_amount_cents integer,
  apr_rate double precision,
  term_months integer,
  monthly_payment_cents integer,
  status "FinancingStatus" DEFAULT 'PENDING'::"FinancingStatus" NOT NULL
);
CREATE TABLE public.financing_audit_events (
  id text NOT NULL,
  sequence integer NOT NULL,
  event_type "FinancingAuditEventType" NOT NULL,
  actor_type "FinancingAuditActorType" NOT NULL,
  actor_id text,
  credit_application_id text,
  deal_id text,
  buyer_id text,
  rule_id text,
  payload jsonb NOT NULL,
  prev_hash text,
  hash text NOT NULL,
  created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE public.financing_review_tasks (
  id text NOT NULL,
  credit_application_id text NOT NULL,
  deal_id text,
  buyer_id text,
  task_type "FinancingReviewTaskType" NOT NULL,
  status "FinancingReviewTaskStatus" DEFAULT 'OPEN'::"FinancingReviewTaskStatus" NOT NULL,
  reason text,
  assigned_admin_id text,
  resolution text,
  resolution_outcome text,
  resolved_by text,
  resolved_at timestamp(3) without time zone,
  created_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
