ALTER TABLE public."_prisma_migrations" ADD CONSTRAINT "_prisma_migrations_pkey" PRIMARY KEY ("id");
-- production has NO primary key on _prisma_migrations_backup_20260831 (every column nullable)
ALTER TABLE public."ab_test_groups" ADD CONSTRAINT "ab_test_groups_pkey" PRIMARY KEY ("id");
ALTER TABLE public."ab_test_variants" ADD CONSTRAINT "ab_test_variants_pkey" PRIMARY KEY ("id");
ALTER TABLE public."accepted_terms" ADD CONSTRAINT "accepted_terms_pkey" PRIMARY KEY ("id");
ALTER TABLE public."acquisition_conversations" ADD CONSTRAINT "acquisition_conversations_pkey" PRIMARY KEY ("id");
ALTER TABLE public."admin_audit_log" ADD CONSTRAINT "admin_audit_log_pkey" PRIMARY KEY ("id");
ALTER TABLE public."admin_audit_logs" ADD CONSTRAINT "admin_audit_logs_pkey" PRIMARY KEY ("id");
ALTER TABLE public."admin_briefing_history" ADD CONSTRAINT "admin_briefing_history_pkey" PRIMARY KEY ("id");
ALTER TABLE public."admin_briefings" ADD CONSTRAINT "admin_briefings_pkey" PRIMARY KEY ("id");
ALTER TABLE public."admin_impersonations" ADD CONSTRAINT "admin_impersonations_pkey" PRIMARY KEY ("id");
ALTER TABLE public."admin_inventory_search_runs" ADD CONSTRAINT "admin_inventory_search_runs_pkey" PRIMARY KEY ("id");
ALTER TABLE public."admin_journey_notes" ADD CONSTRAINT "admin_journey_notes_pkey" PRIMARY KEY ("id");
ALTER TABLE public."admin_journey_unlocks" ADD CONSTRAINT "admin_journey_unlocks_pkey" PRIMARY KEY ("id");
ALTER TABLE public."admin_login_logs" ADD CONSTRAINT "admin_login_logs_pkey" PRIMARY KEY ("id");
ALTER TABLE public."admin_mfa_email_tokens" ADD CONSTRAINT "admin_mfa_email_tokens_pkey" PRIMARY KEY ("id");
ALTER TABLE public."admin_sessions" ADD CONSTRAINT "admin_sessions_pkey" PRIMARY KEY ("id");
ALTER TABLE public."admin_support_notes" ADD CONSTRAINT "admin_support_notes_pkey" PRIMARY KEY ("id");
ALTER TABLE public."admins" ADD CONSTRAINT "admins_pkey" PRIMARY KEY ("id");
ALTER TABLE public."affiliate_clicks" ADD CONSTRAINT "affiliate_clicks_pkey" PRIMARY KEY ("id");
ALTER TABLE public."affiliate_compliance_records" ADD CONSTRAINT "affiliate_compliance_records_pkey" PRIMARY KEY ("id");
ALTER TABLE public."affiliate_documents" ADD CONSTRAINT "affiliate_documents_pkey" PRIMARY KEY ("id");
ALTER TABLE public."affiliate_onboarding_reviews" ADD CONSTRAINT "affiliate_onboarding_reviews_pkey" PRIMARY KEY ("id");
ALTER TABLE public."affiliate_payment_profiles" ADD CONSTRAINT "affiliate_payment_profiles_pkey" PRIMARY KEY ("id");
ALTER TABLE public."affiliate_payout_methods" ADD CONSTRAINT "affiliate_payout_methods_pkey" PRIMARY KEY ("id");
ALTER TABLE public."affiliate_payout_schedules" ADD CONSTRAINT "affiliate_payout_schedules_pkey" PRIMARY KEY ("id");
ALTER TABLE public."affiliate_payouts" ADD CONSTRAINT "affiliate_payouts_pkey" PRIMARY KEY ("id");
ALTER TABLE public."affiliate_profiles" ADD CONSTRAINT "affiliate_profiles_pkey" PRIMARY KEY ("id");
ALTER TABLE public."affiliate_referrals" ADD CONSTRAINT "affiliate_referrals_pkey" PRIMARY KEY ("id");
ALTER TABLE public."affiliate_tax_profiles" ADD CONSTRAINT "affiliate_tax_profiles_pkey" PRIMARY KEY ("id");
ALTER TABLE public."affiliate_tier_history" ADD CONSTRAINT "affiliate_tier_history_pkey" PRIMARY KEY ("id");
ALTER TABLE public."affiliates" ADD CONSTRAINT "affiliates_pkey" PRIMARY KEY ("id");
ALTER TABLE public."ai_action_intents" ADD CONSTRAINT "ai_action_intents_pkey" PRIMARY KEY ("id");
ALTER TABLE public."ai_chat_messages" ADD CONSTRAINT "ai_chat_messages_pkey" PRIMARY KEY ("id");
ALTER TABLE public."ai_chat_sessions" ADD CONSTRAINT "ai_chat_sessions_pkey" PRIMARY KEY ("id");
ALTER TABLE public."ai_context_cache" ADD CONSTRAINT "ai_context_cache_pkey" PRIMARY KEY ("id");
ALTER TABLE public."ai_conversation_contexts" ADD CONSTRAINT "ai_conversation_contexts_pkey" PRIMARY KEY ("id");
ALTER TABLE public."ai_kill_switch_logs" ADD CONSTRAINT "ai_kill_switch_logs_pkey" PRIMARY KEY ("id");
ALTER TABLE public."ai_media_generations" ADD CONSTRAINT "ai_media_generations_pkey" PRIMARY KEY ("id");
ALTER TABLE public."amips_intelligence_snapshots" ADD CONSTRAINT "amips_intelligence_snapshots_pkey" PRIMARY KEY ("id");
ALTER TABLE public."amips_market_scores" ADD CONSTRAINT "amips_market_scores_pkey" PRIMARY KEY ("id");
ALTER TABLE public."amips_pages" ADD CONSTRAINT "amips_pages_pkey" PRIMARY KEY ("id");
ALTER TABLE public."analytics_cohorts" ADD CONSTRAINT "analytics_cohorts_pkey" PRIMARY KEY ("id");
ALTER TABLE public."apollo_credit_ledger" ADD CONSTRAINT "apollo_credit_ledger_pkey" PRIMARY KEY ("id");
ALTER TABLE public."apollo_enrichment_runs" ADD CONSTRAINT "apollo_enrichment_runs_pkey" PRIMARY KEY ("id");
ALTER TABLE public."apollo_person_candidates" ADD CONSTRAINT "apollo_person_candidates_pkey" PRIMARY KEY ("id");
ALTER TABLE public."apollo_reveals" ADD CONSTRAINT "apollo_reveals_pkey" PRIMARY KEY ("id");
ALTER TABLE public."auction_extension_logs" ADD CONSTRAINT "auction_extension_logs_pkey" PRIMARY KEY ("id");
ALTER TABLE public."auction_invitations" ADD CONSTRAINT "auction_invitations_pkey" PRIMARY KEY ("id");
ALTER TABLE public."auction_vehicles" ADD CONSTRAINT "auction_vehicles_pkey" PRIMARY KEY ("id");
ALTER TABLE public."auctions" ADD CONSTRAINT "auctions_pkey" PRIMARY KEY ("id");
ALTER TABLE public."audit_logs" ADD CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id");
ALTER TABLE public."autolenis_intelligence" ADD CONSTRAINT "autolenis_intelligence_pkey" PRIMARY KEY ("id");
ALTER TABLE public."best_price_calculation_logs" ADD CONSTRAINT "best_price_calculation_logs_pkey" PRIMARY KEY ("id");
ALTER TABLE public."best_price_weight_configs" ADD CONSTRAINT "best_price_weight_configs_pkey" PRIMARY KEY ("id");
ALTER TABLE public."best_price_weight_history" ADD CONSTRAINT "best_price_weight_history_pkey" PRIMARY KEY ("id");
ALTER TABLE public."buyer_activity_events" ADD CONSTRAINT "buyer_activity_events_pkey" PRIMARY KEY ("id");
ALTER TABLE public."buyer_credit_history" ADD CONSTRAINT "buyer_credit_history_pkey" PRIMARY KEY ("id");
ALTER TABLE public."buyer_inventory_preferences" ADD CONSTRAINT "buyer_inventory_preferences_pkey" PRIMARY KEY ("id");
ALTER TABLE public."buyer_nudge_preferences" ADD CONSTRAINT "buyer_nudge_preferences_pkey" PRIMARY KEY ("id");
ALTER TABLE public."buyer_offer_review_items" ADD CONSTRAINT "buyer_offer_review_items_pkey" PRIMARY KEY ("id");
ALTER TABLE public."buyer_offer_reviews" ADD CONSTRAINT "buyer_offer_reviews_pkey" PRIMARY KEY ("id");
ALTER TABLE public."buyer_opportunities" ADD CONSTRAINT "buyer_opportunities_pkey" PRIMARY KEY ("id");
ALTER TABLE public."buyer_preferences" ADD CONSTRAINT "buyer_preferences_pkey" PRIMARY KEY ("id");
ALTER TABLE public."buyer_request_claim_tokens" ADD CONSTRAINT "buyer_request_claim_tokens_pkey" PRIMARY KEY ("id");
ALTER TABLE public."buyers" ADD CONSTRAINT "buyers_pkey" PRIMARY KEY ("id");
ALTER TABLE public."campaign_recipients" ADD CONSTRAINT "campaign_recipients_pkey" PRIMARY KEY ("id");
ALTER TABLE public."campaigns" ADD CONSTRAINT "campaigns_pkey" PRIMARY KEY ("id");
ALTER TABLE public."circumvention_attempts" ADD CONSTRAINT "circumvention_attempts_pkey" PRIMARY KEY ("id");
ALTER TABLE public."commissions" ADD CONSTRAINT "commissions_pkey" PRIMARY KEY ("id");
ALTER TABLE public."comms_outbox" ADD CONSTRAINT "comms_outbox_pkey" PRIMARY KEY ("id");
ALTER TABLE public."competitor_insights" ADD CONSTRAINT "competitor_insights_pkey" PRIMARY KEY ("id");
ALTER TABLE public."compliance_events" ADD CONSTRAINT "compliance_events_pkey" PRIMARY KEY ("id");
ALTER TABLE public."compliance_rules" ADD CONSTRAINT "compliance_rules_pkey" PRIMARY KEY ("id");
ALTER TABLE public."contact_identities" ADD CONSTRAINT "contact_identities_pkey" PRIMARY KEY ("id");
ALTER TABLE public."contact_timeline_events" ADD CONSTRAINT "contact_timeline_events_pkey" PRIMARY KEY ("id");
ALTER TABLE public."contacts" ADD CONSTRAINT "contacts_pkey" PRIMARY KEY ("id");
ALTER TABLE public."content_article_versions" ADD CONSTRAINT "content_article_versions_pkey" PRIMARY KEY ("id");
ALTER TABLE public."content_articles" ADD CONSTRAINT "content_articles_pkey" PRIMARY KEY ("id");
ALTER TABLE public."content_attributions" ADD CONSTRAINT "content_attributions_pkey" PRIMARY KEY ("id");
ALTER TABLE public."content_derivatives" ADD CONSTRAINT "content_derivatives_pkey" PRIMARY KEY ("id");
ALTER TABLE public."content_franchises" ADD CONSTRAINT "content_franchises_pkey" PRIMARY KEY ("id");
ALTER TABLE public."content_generation_job_items" ADD CONSTRAINT "content_generation_job_items_pkey" PRIMARY KEY ("id");
ALTER TABLE public."content_generation_jobs" ADD CONSTRAINT "content_generation_jobs_pkey" PRIMARY KEY ("id");
ALTER TABLE public."content_media_assets" ADD CONSTRAINT "content_media_assets_pkey" PRIMARY KEY ("id");
ALTER TABLE public."content_queue" ADD CONSTRAINT "content_queue_pkey" PRIMARY KEY ("id");
ALTER TABLE public."content_validation_results" ADD CONSTRAINT "content_validation_results_pkey" PRIMARY KEY ("id");
ALTER TABLE public."content_workflow_events" ADD CONSTRAINT "content_workflow_events_pkey" PRIMARY KEY ("id");
ALTER TABLE public."contract_scan_history" ADD CONSTRAINT "contract_scan_history_pkey" PRIMARY KEY ("id");
ALTER TABLE public."contract_scan_rule_history" ADD CONSTRAINT "contract_scan_rule_history_pkey" PRIMARY KEY ("id");
ALTER TABLE public."contract_scan_rules" ADD CONSTRAINT "contract_scan_rules_pkey" PRIMARY KEY ("id");
ALTER TABLE public."contract_scans" ADD CONSTRAINT "contract_scans_pkey" PRIMARY KEY ("id");
ALTER TABLE public."contract_versions" ADD CONSTRAINT "contract_versions_pkey" PRIMARY KEY ("id");
ALTER TABLE public."conversation_messages" ADD CONSTRAINT "conversation_messages_pkey" PRIMARY KEY ("id");
ALTER TABLE public."conversations" ADD CONSTRAINT "conversations_pkey" PRIMARY KEY ("id");
ALTER TABLE public."creator_attributions" ADD CONSTRAINT "creator_attributions_pkey" PRIMARY KEY ("id");
ALTER TABLE public."creator_network" ADD CONSTRAINT "creator_network_pkey" PRIMARY KEY ("id");
ALTER TABLE public."credit_applications" ADD CONSTRAINT "credit_applications_pkey" PRIMARY KEY ("id");
ALTER TABLE public."crm_tasks" ADD CONSTRAINT "crm_tasks_pkey" PRIMARY KEY ("id");
ALTER TABLE public."cron_job_logs" ADD CONSTRAINT "cron_job_logs_pkey" PRIMARY KEY ("id");
ALTER TABLE public."csrf_tokens" ADD CONSTRAINT "csrf_tokens_pkey" PRIMARY KEY ("id");
ALTER TABLE public."deal_notes" ADD CONSTRAINT "deal_notes_pkey" PRIMARY KEY ("id");
ALTER TABLE public."deal_status_history" ADD CONSTRAINT "deal_status_history_pkey" PRIMARY KEY ("id");
ALTER TABLE public."deal_timeline" ADD CONSTRAINT "deal_timeline_pkey" PRIMARY KEY ("id");
ALTER TABLE public."dealer_account_claim_tokens" ADD CONSTRAINT "dealer_account_claim_tokens_pkey" PRIMARY KEY ("id");
ALTER TABLE public."dealer_agreement_signatures" ADD CONSTRAINT "dealer_agreement_signatures_pkey" PRIMARY KEY ("id");
ALTER TABLE public."dealer_applications" ADD CONSTRAINT "dealer_applications_pkey" PRIMARY KEY ("id");
ALTER TABLE public."dealer_availability" ADD CONSTRAINT "dealer_availability_pkey" PRIMARY KEY ("id");
ALTER TABLE public."dealer_availability_windows" ADD CONSTRAINT "dealer_availability_windows_pkey" PRIMARY KEY ("id");
ALTER TABLE public."dealer_blackout_dates" ADD CONSTRAINT "dealer_blackout_dates_pkey" PRIMARY KEY ("id");
ALTER TABLE public."dealer_capacity_configs" ADD CONSTRAINT "dealer_capacity_configs_pkey" PRIMARY KEY ("id");
ALTER TABLE public."dealer_contact_profiles" ADD CONSTRAINT "dealer_contact_profiles_pkey" PRIMARY KEY ("id");
ALTER TABLE public."dealer_discoveries" ADD CONSTRAINT "dealer_discoveries_pkey" PRIMARY KEY ("id");
ALTER TABLE public."dealer_feed_configs" ADD CONSTRAINT "dealer_feed_configs_pkey" PRIMARY KEY ("id");
ALTER TABLE public."dealer_intelligence" ADD CONSTRAINT "dealer_intelligence_pkey" PRIMARY KEY ("id");
ALTER TABLE public."dealer_invitations" ADD CONSTRAINT "dealer_invitations_pkey" PRIMARY KEY ("id");
ALTER TABLE public."dealer_licenses" ADD CONSTRAINT "dealer_licenses_pkey" PRIMARY KEY ("id");
ALTER TABLE public."dealer_offer_submissions" ADD CONSTRAINT "dealer_offer_submissions_pkey" PRIMARY KEY ("id");
ALTER TABLE public."dealer_outreach_log" ADD CONSTRAINT "dealer_outreach_log_pkey" PRIMARY KEY ("id");
ALTER TABLE public."dealer_payments" ADD CONSTRAINT "dealer_payments_pkey" PRIMARY KEY ("id");
ALTER TABLE public."dealer_prospects" ADD CONSTRAINT "dealer_prospects_pkey" PRIMARY KEY ("id");
ALTER TABLE public."dealer_rooftops" ADD CONSTRAINT "dealer_rooftops_pkey" PRIMARY KEY ("id");
ALTER TABLE public."dealer_scorecard_snapshots" ADD CONSTRAINT "dealer_scorecard_snapshots_pkey" PRIMARY KEY ("id");
ALTER TABLE public."dealer_scorecard_weights" ADD CONSTRAINT "dealer_scorecard_weights_pkey" PRIMARY KEY ("id");
ALTER TABLE public."dealer_verifications" ADD CONSTRAINT "dealer_verifications_pkey" PRIMARY KEY ("id");
ALTER TABLE public."dealers" ADD CONSTRAINT "dealers_pkey" PRIMARY KEY ("id");
ALTER TABLE public."deals" ADD CONSTRAINT "deals_pkey" PRIMARY KEY ("id");
ALTER TABLE public."deposits" ADD CONSTRAINT "deposits_pkey" PRIMARY KEY ("id");
ALTER TABLE public."document_requests" ADD CONSTRAINT "document_requests_pkey" PRIMARY KEY ("id");
ALTER TABLE public."document_versions" ADD CONSTRAINT "document_versions_pkey" PRIMARY KEY ("id");
ALTER TABLE public."documents" ADD CONSTRAINT "documents_pkey" PRIMARY KEY ("id");
ALTER TABLE public."e_sign_envelope_history" ADD CONSTRAINT "e_sign_envelope_history_pkey" PRIMARY KEY ("id");
ALTER TABLE public."e_sign_envelopes" ADD CONSTRAINT "e_sign_envelopes_pkey" PRIMARY KEY ("id");
ALTER TABLE public."email_send_logs" ADD CONSTRAINT "email_send_logs_pkey" PRIMARY KEY ("id");
ALTER TABLE public."email_suppression" ADD CONSTRAINT "email_suppression_pkey" PRIMARY KEY ("id");
ALTER TABLE public."email_template_versions" ADD CONSTRAINT "email_template_versions_pkey" PRIMARY KEY ("id");
ALTER TABLE public."email_templates" ADD CONSTRAINT "email_templates_pkey" PRIMARY KEY ("id");
ALTER TABLE public."encouragement_messages" ADD CONSTRAINT "encouragement_messages_pkey" PRIMARY KEY ("id");
ALTER TABLE public."external_pre_approval_documents" ADD CONSTRAINT "external_pre_approval_documents_pkey" PRIMARY KEY ("id");
ALTER TABLE public."external_pre_approvals" ADD CONSTRAINT "external_pre_approvals_pkey" PRIMARY KEY ("id");
ALTER TABLE public."faith_content_audit_logs" ADD CONSTRAINT "faith_content_audit_logs_pkey" PRIMARY KEY ("id");
ALTER TABLE public."feature_flags" ADD CONSTRAINT "feature_flags_pkey" PRIMARY KEY ("id");
ALTER TABLE public."financing" ADD CONSTRAINT "financing_pkey" PRIMARY KEY ("id");
ALTER TABLE public."financing_audit_events" ADD CONSTRAINT "financing_audit_events_pkey" PRIMARY KEY ("id");
ALTER TABLE public."financing_review_tasks" ADD CONSTRAINT "financing_review_tasks_pkey" PRIMARY KEY ("id");
ALTER TABLE public."financing_scenarios" ADD CONSTRAINT "financing_scenarios_pkey" PRIMARY KEY ("id");
ALTER TABLE public."funnel_stage_snapshots" ADD CONSTRAINT "funnel_stage_snapshots_pkey" PRIMARY KEY ("id");
ALTER TABLE public."health_check_logs" ADD CONSTRAINT "health_check_logs_pkey" PRIMARY KEY ("id");
ALTER TABLE public."hook_performance" ADD CONSTRAINT "hook_performance_pkey" PRIMARY KEY ("id");
ALTER TABLE public."hope_page_content" ADD CONSTRAINT "hope_page_content_pkey" PRIMARY KEY ("id");
ALTER TABLE public."idempotency_keys" ADD CONSTRAINT "idempotency_keys_pkey" PRIMARY KEY ("key_hash");
ALTER TABLE public."identity_firewall_entries" ADD CONSTRAINT "identity_firewall_entries_pkey" PRIMARY KEY ("id");
ALTER TABLE public."insurance_policies" ADD CONSTRAINT "insurance_policies_pkey" PRIMARY KEY ("id");
ALTER TABLE public."insurance_providers" ADD CONSTRAINT "insurance_providers_pkey" PRIMARY KEY ("id");
ALTER TABLE public."insurance_quotes" ADD CONSTRAINT "insurance_quotes_pkey" PRIMARY KEY ("id");
ALTER TABLE public."inventory_feed_logs" ADD CONSTRAINT "inventory_feed_logs_pkey" PRIMARY KEY ("id");
ALTER TABLE public."inventory_items" ADD CONSTRAINT "inventory_items_pkey" PRIMARY KEY ("id");
ALTER TABLE public."inventory_price_alerts" ADD CONSTRAINT "inventory_price_alerts_pkey" PRIMARY KEY ("id");
ALTER TABLE public."inventory_quality_scores" ADD CONSTRAINT "inventory_quality_scores_pkey" PRIMARY KEY ("id");
ALTER TABLE public."inventory_sources" ADD CONSTRAINT "inventory_sources_pkey" PRIMARY KEY ("id");
ALTER TABLE public."inventory_sync_runs" ADD CONSTRAINT "inventory_sync_runs_pkey" PRIMARY KEY ("id");
ALTER TABLE public."inventory_upload_batches" ADD CONSTRAINT "inventory_upload_batches_pkey" PRIMARY KEY ("id");
ALTER TABLE public."jobs_dead_letter" ADD CONSTRAINT "jobs_dead_letter_pkey" PRIMARY KEY ("id");
ALTER TABLE public."junk_fee_patterns" ADD CONSTRAINT "junk_fee_patterns_pkey" PRIMARY KEY ("id");
ALTER TABLE public."lead_nurture_schedule" ADD CONSTRAINT "lead_nurture_schedule_pkey" PRIMARY KEY ("id");
ALTER TABLE public."lead_nurtures" ADD CONSTRAINT "lead_nurtures_pkey" PRIMARY KEY ("id");
ALTER TABLE public."lead_scores" ADD CONSTRAINT "lead_scores_pkey" PRIMARY KEY ("id");
ALTER TABLE public."lead_scoring_events" ADD CONSTRAINT "lead_scoring_events_pkey" PRIMARY KEY ("id");
ALTER TABLE public."lifecycle_touch_schedule" ADD CONSTRAINT "lifecycle_touch_schedule_pkey" PRIMARY KEY ("id");
ALTER TABLE public."market_coverage" ADD CONSTRAINT "market_coverage_pkey" PRIMARY KEY ("id");
ALTER TABLE public."market_intelligence" ADD CONSTRAINT "market_intelligence_pkey" PRIMARY KEY ("id");
ALTER TABLE public."marketplace_intelligence" ADD CONSTRAINT "marketplace_intelligence_pkey" PRIMARY KEY ("id");
ALTER TABLE public."message_read_receipts" ADD CONSTRAINT "message_read_receipts_pkey" PRIMARY KEY ("id");
ALTER TABLE public."message_thread_participants" ADD CONSTRAINT "message_thread_participants_pkey" PRIMARY KEY ("id");
ALTER TABLE public."message_threads" ADD CONSTRAINT "message_threads_pkey" PRIMARY KEY ("id");
ALTER TABLE public."messages" ADD CONSTRAINT "messages_pkey" PRIMARY KEY ("id");
ALTER TABLE public."notification_batches" ADD CONSTRAINT "notification_batches_pkey" PRIMARY KEY ("id");
ALTER TABLE public."notification_preferences" ADD CONSTRAINT "notification_preferences_pkey" PRIMARY KEY ("id");
ALTER TABLE public."notifications" ADD CONSTRAINT "notifications_pkey" PRIMARY KEY ("id");
ALTER TABLE public."nudge_configurations" ADD CONSTRAINT "nudge_configurations_pkey" PRIMARY KEY ("id");
ALTER TABLE public."nudge_events" ADD CONSTRAINT "nudge_events_pkey" PRIMARY KEY ("id");
ALTER TABLE public."offers" ADD CONSTRAINT "offers_pkey" PRIMARY KEY ("id");
ALTER TABLE public."outside_auction_invites" ADD CONSTRAINT "outside_auction_invites_pkey" PRIMARY KEY ("id");
ALTER TABLE public."payment_provider_events" ADD CONSTRAINT "payment_provider_events_pkey" PRIMARY KEY ("id");
ALTER TABLE public."pickups" ADD CONSTRAINT "pickups_pkey" PRIMARY KEY ("id");
ALTER TABLE public."platform_alerts" ADD CONSTRAINT "platform_alerts_pkey" PRIMARY KEY ("id");
ALTER TABLE public."platform_stat_snapshots" ADD CONSTRAINT "platform_stat_snapshots_pkey" PRIMARY KEY ("id");
ALTER TABLE public."posting_windows" ADD CONSTRAINT "posting_windows_pkey" PRIMARY KEY ("id");
ALTER TABLE public."pre_qualifications" ADD CONSTRAINT "pre_qualifications_pkey" PRIMARY KEY ("id");
ALTER TABLE public."prequal_consents" ADD CONSTRAINT "prequal_consents_pkey" PRIMARY KEY ("id");
ALTER TABLE public."rate_limit_events" ADD CONSTRAINT "rate_limit_events_pkey" PRIMARY KEY ("id");
ALTER TABLE public."referral_milestone_configs" ADD CONSTRAINT "referral_milestone_configs_pkey" PRIMARY KEY ("id");
ALTER TABLE public."referral_milestones" ADD CONSTRAINT "referral_milestones_pkey" PRIMARY KEY ("id");
ALTER TABLE public."refinance_applications" ADD CONSTRAINT "refinance_applications_pkey" PRIMARY KEY ("id");
ALTER TABLE public."refinance_compliance_logs" ADD CONSTRAINT "refinance_compliance_logs_pkey" PRIMARY KEY ("id");
ALTER TABLE public."revenue_attributions" ADD CONSTRAINT "revenue_attributions_pkey" PRIMARY KEY ("id");
ALTER TABLE public."revenue_snapshots" ADD CONSTRAINT "revenue_snapshots_pkey" PRIMARY KEY ("id");
ALTER TABLE public."saved_searches" ADD CONSTRAINT "saved_searches_pkey" PRIMARY KEY ("id");
ALTER TABLE public."search_cache" ADD CONSTRAINT "search_cache_pkey" PRIMARY KEY ("id");
ALTER TABLE public."search_filters" ADD CONSTRAINT "search_filters_pkey" PRIMARY KEY ("id");
ALTER TABLE public."search_intelligence" ADD CONSTRAINT "search_intelligence_pkey" PRIMARY KEY ("id");
ALTER TABLE public."segments" ADD CONSTRAINT "segments_pkey" PRIMARY KEY ("id");
ALTER TABLE public."seo_health_scores" ADD CONSTRAINT "seo_health_scores_pkey" PRIMARY KEY ("id");
ALTER TABLE public."seo_keywords" ADD CONSTRAINT "seo_keywords_pkey" PRIMARY KEY ("id");
ALTER TABLE public."seo_page_configs" ADD CONSTRAINT "seo_page_configs_pkey" PRIMARY KEY ("id");
ALTER TABLE public."seo_redirects" ADD CONSTRAINT "seo_redirects_pkey" PRIMARY KEY ("id");
ALTER TABLE public."seo_sitemap_entries" ADD CONSTRAINT "seo_sitemap_entries_pkey" PRIMARY KEY ("id");
ALTER TABLE public."service_fee_payments" ADD CONSTRAINT "service_fee_payments_pkey" PRIMARY KEY ("id");
ALTER TABLE public."sessions" ADD CONSTRAINT "sessions_pkey" PRIMARY KEY ("id");
ALTER TABLE public."shortlist_items" ADD CONSTRAINT "shortlist_items_pkey" PRIMARY KEY ("id");
ALTER TABLE public."shortlists" ADD CONSTRAINT "shortlists_pkey" PRIMARY KEY ("id");
ALTER TABLE public."sla_violations" ADD CONSTRAINT "sla_violations_pkey" PRIMARY KEY ("id");
ALTER TABLE public."sms_opt_outs" ADD CONSTRAINT "sms_opt_outs_pkey" PRIMARY KEY ("id");
ALTER TABLE public."sms_suppression" ADD CONSTRAINT "sms_suppression_pkey" PRIMARY KEY ("id");
ALTER TABLE public."social_intelligence_cache" ADD CONSTRAINT "social_intelligence_cache_pkey" PRIMARY KEY ("id");
ALTER TABLE public."social_leads" ADD CONSTRAINT "social_leads_pkey" PRIMARY KEY ("id");
ALTER TABLE public."social_performance" ADD CONSTRAINT "social_performance_pkey" PRIMARY KEY ("id");
ALTER TABLE public."social_posts" ADD CONSTRAINT "social_posts_pkey" PRIMARY KEY ("id");
ALTER TABLE public."social_videos" ADD CONSTRAINT "social_videos_pkey" PRIMARY KEY ("id");
ALTER TABLE public."system_config_history" ADD CONSTRAINT "system_config_history_pkey" PRIMARY KEY ("id");
ALTER TABLE public."system_configurations" ADD CONSTRAINT "system_configurations_pkey" PRIMARY KEY ("id");
ALTER TABLE public."testimonials" ADD CONSTRAINT "testimonials_pkey" PRIMARY KEY ("id");
ALTER TABLE public."topic_signals" ADD CONSTRAINT "topic_signals_pkey" PRIMARY KEY ("id");
ALTER TABLE public."trade_in_submissions" ADD CONSTRAINT "trade_in_submissions_pkey" PRIMARY KEY ("id");
ALTER TABLE public."trade_in_valuations" ADD CONSTRAINT "trade_in_valuations_pkey" PRIMARY KEY ("id");
ALTER TABLE public."user_preferences" ADD CONSTRAINT "user_preferences_pkey" PRIMARY KEY ("id");
ALTER TABLE public."users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");
ALTER TABLE public."vehicle_comparisons_saved" ADD CONSTRAINT "vehicle_comparisons_saved_pkey" PRIMARY KEY ("id");
ALTER TABLE public."vehicle_intelligence" ADD CONSTRAINT "vehicle_intelligence_pkey" PRIMARY KEY ("id");
ALTER TABLE public."vehicle_match_scores" ADD CONSTRAINT "vehicle_match_scores_pkey" PRIMARY KEY ("id");
ALTER TABLE public."vehicle_offer_dealer_invites" ADD CONSTRAINT "vehicle_offer_dealer_invites_pkey" PRIMARY KEY ("id");
ALTER TABLE public."vehicle_offers" ADD CONSTRAINT "vehicle_offers_pkey" PRIMARY KEY ("id");
ALTER TABLE public."vehicle_request_buyer_updates" ADD CONSTRAINT "vehicle_request_buyer_updates_pkey" PRIMARY KEY ("id");
ALTER TABLE public."vehicle_request_due_diligence_checkpoints" ADD CONSTRAINT "vehicle_request_due_diligence_checkpoints_pkey" PRIMARY KEY ("id");
ALTER TABLE public."vehicle_request_events" ADD CONSTRAINT "vehicle_request_events_pkey" PRIMARY KEY ("id");
ALTER TABLE public."vehicle_request_financing" ADD CONSTRAINT "vehicle_request_financing_pkey" PRIMARY KEY ("id");
ALTER TABLE public."vehicle_request_match_results" ADD CONSTRAINT "vehicle_request_match_results_pkey" PRIMARY KEY ("id");
ALTER TABLE public."vehicle_request_offers" ADD CONSTRAINT "vehicle_request_offers_pkey" PRIMARY KEY ("id");
ALTER TABLE public."vehicle_request_research_logs" ADD CONSTRAINT "vehicle_request_research_logs_pkey" PRIMARY KEY ("id");
ALTER TABLE public."vehicle_requests" ADD CONSTRAINT "vehicle_requests_pkey" PRIMARY KEY ("id");
ALTER TABLE public."verse_library" ADD CONSTRAINT "verse_library_pkey" PRIMARY KEY ("id");
ALTER TABLE public."verse_page_assignments" ADD CONSTRAINT "verse_page_assignments_pkey" PRIMARY KEY ("id");
ALTER TABLE public."violation_pattern_records" ADD CONSTRAINT "violation_pattern_records_pkey" PRIMARY KEY ("id");
ALTER TABLE public."webhook_events" ADD CONSTRAINT "webhook_events_pkey" PRIMARY KEY ("id");
ALTER TABLE public."winning_patterns" ADD CONSTRAINT "winning_patterns_pkey" PRIMARY KEY ("id");
ALTER TABLE public."workflow_enrollments" ADD CONSTRAINT "workflow_enrollments_pkey" PRIMARY KEY ("id");
ALTER TABLE public."workflow_execution_log" ADD CONSTRAINT "workflow_execution_log_pkey" PRIMARY KEY ("id");
ALTER TABLE public."workflow_versions" ADD CONSTRAINT "workflow_versions_pkey" PRIMARY KEY ("id");
ALTER TABLE public."workflows" ADD CONSTRAINT "workflows_pkey" PRIMARY KEY ("id");
ALTER TABLE public."acquisition_conversations" ADD CONSTRAINT "acquisition_conversations_session_id_key" UNIQUE ("session_id");
ALTER TABLE public."admin_journey_unlocks" ADD CONSTRAINT "admin_journey_unlocks_buyer_id_stage_id_key" UNIQUE ("buyer_id", "stage_id");
ALTER TABLE public."affiliate_onboarding_reviews" ADD CONSTRAINT "affiliate_onboarding_reviews_affiliate_id_key" UNIQUE ("affiliate_id");
ALTER TABLE public."affiliate_payment_profiles" ADD CONSTRAINT "affiliate_payment_profiles_affiliate_id_key" UNIQUE ("affiliate_id");
ALTER TABLE public."affiliate_payout_methods" ADD CONSTRAINT "affiliate_payout_methods_affiliate_id_key" UNIQUE ("affiliate_id");
ALTER TABLE public."affiliate_profiles" ADD CONSTRAINT "affiliate_profiles_affiliate_id_key" UNIQUE ("affiliate_id");
ALTER TABLE public."affiliate_tax_profiles" ADD CONSTRAINT "affiliate_tax_profiles_affiliate_id_key" UNIQUE ("affiliate_id");
ALTER TABLE public."ai_media_generations" ADD CONSTRAINT "ai_media_generations_higgsfield_request_id_key" UNIQUE ("higgsfield_request_id");
ALTER TABLE public."buyer_offer_reviews" ADD CONSTRAINT "buyer_offer_reviews_review_token_key" UNIQUE ("review_token");
ALTER TABLE public."buyer_opportunities" ADD CONSTRAINT "buyer_opportunities_session_id_key" UNIQUE ("session_id");
ALTER TABLE public."campaign_recipients" ADD CONSTRAINT "campaign_recipients_campaign_id_contact_id_key" UNIQUE ("campaign_id", "contact_id");
ALTER TABLE public."contact_identities" ADD CONSTRAINT "contact_identities_entity_type_entity_id_key" UNIQUE ("entity_type", "entity_id");
ALTER TABLE public."content_articles" ADD CONSTRAINT "content_articles_slug_key" UNIQUE ("slug");
ALTER TABLE public."content_franchises" ADD CONSTRAINT "content_franchises_slug_key" UNIQUE ("slug");
ALTER TABLE public."dealer_applications" ADD CONSTRAINT "dealer_applications_dealer_id_key" UNIQUE ("dealer_id");
ALTER TABLE public."dealer_invitations" ADD CONSTRAINT "dealer_invitations_dealer_id_key" UNIQUE ("dealer_id");
ALTER TABLE public."dealer_invitations" ADD CONSTRAINT "dealer_invitations_token_key" UNIQUE ("token");
ALTER TABLE public."dealer_offer_submissions" ADD CONSTRAINT "dealer_offer_submissions_invite_id_key" UNIQUE ("invite_id");
ALTER TABLE public."deals" ADD CONSTRAINT "deals_vehicle_request_offer_id_key" UNIQUE ("vehicle_request_offer_id");
ALTER TABLE public."email_suppression" ADD CONSTRAINT "email_suppression_email_key" UNIQUE ("email");
ALTER TABLE public."email_template_versions" ADD CONSTRAINT "email_template_versions_template_id_version_key" UNIQUE ("template_id", "version");
ALTER TABLE public."hook_performance" ADD CONSTRAINT "hook_performance_platform_hook_type_key" UNIQUE ("platform", "hook_type");
ALTER TABLE public."outside_auction_invites" ADD CONSTRAINT "outside_auction_invites_offer_id_key" UNIQUE ("offer_id");
ALTER TABLE public."outside_auction_invites" ADD CONSTRAINT "outside_auction_invites_token_key" UNIQUE ("token");
ALTER TABLE public."posting_windows" ADD CONSTRAINT "posting_windows_platform_day_of_week_key" UNIQUE ("platform", "day_of_week");
ALTER TABLE public."referral_milestone_configs" ADD CONSTRAINT "referral_milestone_configs_milestone_code_key" UNIQUE ("milestone_code");
ALTER TABLE public."search_cache" ADD CONSTRAINT "search_cache_cache_key_key" UNIQUE ("cache_key");
ALTER TABLE public."sms_opt_outs" ADD CONSTRAINT "sms_opt_outs_phone_key" UNIQUE ("phone");
ALTER TABLE public."sms_suppression" ADD CONSTRAINT "sms_suppression_phone_key" UNIQUE ("phone");
ALTER TABLE public."social_intelligence_cache" ADD CONSTRAINT "social_intelligence_cache_cache_key_key" UNIQUE ("cache_key");
ALTER TABLE public."social_videos" ADD CONSTRAINT "social_videos_post_id_key" UNIQUE ("post_id");
ALTER TABLE public."vehicle_offer_dealer_invites" ADD CONSTRAINT "vehicle_offer_dealer_invites_submission_id_key" UNIQUE ("submission_id");
ALTER TABLE public."vehicle_offer_dealer_invites" ADD CONSTRAINT "vehicle_offer_dealer_invites_token_key" UNIQUE ("token");
ALTER TABLE public."vehicle_offers" ADD CONSTRAINT "vehicle_offers_token_key" UNIQUE ("token");
ALTER TABLE public."workflow_versions" ADD CONSTRAINT "workflow_versions_workflow_id_version_key" UNIQUE ("workflow_id", "version");
