ALTER TABLE public."ab_test_variants" ADD CONSTRAINT "ab_test_variants_group_id_fkey" FOREIGN KEY (group_id) REFERENCES ab_test_groups(id) ON DELETE CASCADE;
ALTER TABLE public."accepted_terms" ADD CONSTRAINT "accepted_terms_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."admin_journey_notes" ADD CONSTRAINT "admin_journey_notes_buyer_id_fkey" FOREIGN KEY (buyer_id) REFERENCES buyers(id) ON DELETE CASCADE;
ALTER TABLE public."admin_journey_unlocks" ADD CONSTRAINT "admin_journey_unlocks_buyer_id_fkey" FOREIGN KEY (buyer_id) REFERENCES buyers(id) ON DELETE CASCADE;
ALTER TABLE public."admin_mfa_email_tokens" ADD CONSTRAINT "admin_mfa_email_tokens_admin_id_fkey" FOREIGN KEY (admin_id) REFERENCES admins(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."admins" ADD CONSTRAINT "admins_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."affiliate_clicks" ADD CONSTRAINT "affiliate_clicks_affiliate_id_fkey" FOREIGN KEY (affiliate_id) REFERENCES affiliates(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."affiliate_documents" ADD CONSTRAINT "affiliate_documents_affiliate_id_fkey" FOREIGN KEY (affiliate_id) REFERENCES affiliates(id) ON DELETE CASCADE;
ALTER TABLE public."affiliate_onboarding_reviews" ADD CONSTRAINT "affiliate_onboarding_reviews_affiliate_id_fkey" FOREIGN KEY (affiliate_id) REFERENCES affiliates(id) ON DELETE CASCADE;
ALTER TABLE public."affiliate_payment_profiles" ADD CONSTRAINT "affiliate_payment_profiles_affiliate_id_fkey" FOREIGN KEY (affiliate_id) REFERENCES affiliates(id) ON DELETE CASCADE;
ALTER TABLE public."affiliate_payout_methods" ADD CONSTRAINT "affiliate_payout_methods_affiliate_id_fkey" FOREIGN KEY (affiliate_id) REFERENCES affiliates(id) ON DELETE CASCADE;
ALTER TABLE public."affiliate_payouts" ADD CONSTRAINT "affiliate_payouts_affiliate_id_fkey" FOREIGN KEY (affiliate_id) REFERENCES affiliates(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."affiliate_profiles" ADD CONSTRAINT "affiliate_profiles_affiliate_id_fkey" FOREIGN KEY (affiliate_id) REFERENCES affiliates(id) ON DELETE CASCADE;
ALTER TABLE public."affiliate_tax_profiles" ADD CONSTRAINT "affiliate_tax_profiles_affiliate_id_fkey" FOREIGN KEY (affiliate_id) REFERENCES affiliates(id) ON DELETE CASCADE;
ALTER TABLE public."affiliates" ADD CONSTRAINT "affiliates_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES affiliates(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public."affiliates" ADD CONSTRAINT "affiliates_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."ai_chat_messages" ADD CONSTRAINT "ai_chat_messages_session_id_fkey" FOREIGN KEY (session_id) REFERENCES ai_chat_sessions(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."apollo_person_candidates" ADD CONSTRAINT "apollo_person_candidates_rooftop_id_fkey" FOREIGN KEY (rooftop_id) REFERENCES dealer_rooftops(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public."auction_invitations" ADD CONSTRAINT "auction_invitations_auction_id_fkey" FOREIGN KEY (auction_id) REFERENCES auctions(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."auction_invitations" ADD CONSTRAINT "auction_invitations_dealer_id_fkey" FOREIGN KEY (dealer_id) REFERENCES dealers(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."auction_vehicles" ADD CONSTRAINT "auction_vehicles_auction_id_fkey" FOREIGN KEY (auction_id) REFERENCES auctions(id) ON DELETE CASCADE;
ALTER TABLE public."auction_vehicles" ADD CONSTRAINT "auction_vehicles_inventory_item_id_fkey" FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id);
ALTER TABLE public."auctions" ADD CONSTRAINT "auctions_buyer_id_fkey" FOREIGN KEY (buyer_id) REFERENCES buyers(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."auctions" ADD CONSTRAINT "auctions_deposit_id_fkey" FOREIGN KEY (deposit_id) REFERENCES deposits(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."auctions" ADD CONSTRAINT "auctions_original_auction_id_fkey" FOREIGN KEY (original_auction_id) REFERENCES auctions(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public."auctions" ADD CONSTRAINT "auctions_vehicle_request_id_fkey" FOREIGN KEY (vehicle_request_id) REFERENCES vehicle_requests(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public."buyer_activity_events" ADD CONSTRAINT "buyer_activity_events_buyer_id_fkey" FOREIGN KEY (buyer_id) REFERENCES buyers(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."buyer_offer_review_items" ADD CONSTRAINT "buyer_offer_review_items_buyer_offer_review_id_fkey" FOREIGN KEY (buyer_offer_review_id) REFERENCES buyer_offer_reviews(id) ON DELETE CASCADE;
ALTER TABLE public."buyer_offer_review_items" ADD CONSTRAINT "buyer_offer_review_items_dealer_submission_id_fkey" FOREIGN KEY (dealer_submission_id) REFERENCES dealer_offer_submissions(id) ON DELETE CASCADE;
ALTER TABLE public."buyer_offer_reviews" ADD CONSTRAINT "buyer_offer_reviews_vehicle_offer_id_fkey" FOREIGN KEY (vehicle_offer_id) REFERENCES vehicle_offers(id) ON DELETE CASCADE;
ALTER TABLE public."buyer_preferences" ADD CONSTRAINT "buyer_preferences_buyer_id_fkey" FOREIGN KEY (buyer_id) REFERENCES buyers(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."buyers" ADD CONSTRAINT "buyers_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."campaign_recipients" ADD CONSTRAINT "campaign_recipients_campaign_id_fkey" FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE;
ALTER TABLE public."campaign_recipients" ADD CONSTRAINT "campaign_recipients_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;
ALTER TABLE public."campaigns" ADD CONSTRAINT "campaigns_segment_id_fkey" FOREIGN KEY (segment_id) REFERENCES segments(id) ON DELETE SET NULL;
ALTER TABLE public."campaigns" ADD CONSTRAINT "campaigns_template_id_fkey" FOREIGN KEY (template_id) REFERENCES email_templates(id) ON DELETE SET NULL;
ALTER TABLE public."commissions" ADD CONSTRAINT "commissions_affiliate_id_fkey" FOREIGN KEY (affiliate_id) REFERENCES affiliates(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."commissions" ADD CONSTRAINT "commissions_payout_id_fkey" FOREIGN KEY (payout_id) REFERENCES affiliate_payouts(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."compliance_events" ADD CONSTRAINT "compliance_events_buyer_id_fkey" FOREIGN KEY (buyer_id) REFERENCES buyers(id) ON DELETE CASCADE;
ALTER TABLE public."compliance_events" ADD CONSTRAINT "compliance_events_prequal_application_id_fkey" FOREIGN KEY (prequal_application_id) REFERENCES pre_qualifications(id) ON DELETE SET NULL;
ALTER TABLE public."contact_identities" ADD CONSTRAINT "contact_identities_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;
ALTER TABLE public."contact_timeline_events" ADD CONSTRAINT "contact_timeline_events_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;
ALTER TABLE public."content_article_versions" ADD CONSTRAINT "content_article_versions_article_id_fkey" FOREIGN KEY (article_id) REFERENCES content_articles(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."content_derivatives" ADD CONSTRAINT "content_derivatives_post_id_fkey" FOREIGN KEY (post_id) REFERENCES social_posts(id) ON DELETE CASCADE;
ALTER TABLE public."content_derivatives" ADD CONSTRAINT "content_derivatives_signal_id_fkey" FOREIGN KEY (signal_id) REFERENCES topic_signals(id) ON DELETE SET NULL;
ALTER TABLE public."content_generation_job_items" ADD CONSTRAINT "content_generation_job_items_article_id_fkey" FOREIGN KEY (article_id) REFERENCES content_articles(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public."content_generation_job_items" ADD CONSTRAINT "content_generation_job_items_job_id_fkey" FOREIGN KEY (job_id) REFERENCES content_generation_jobs(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."content_media_assets" ADD CONSTRAINT "content_media_assets_article_id_fkey" FOREIGN KEY (article_id) REFERENCES content_articles(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."content_validation_results" ADD CONSTRAINT "content_validation_results_article_id_fkey" FOREIGN KEY (article_id) REFERENCES content_articles(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."content_workflow_events" ADD CONSTRAINT "content_workflow_events_article_id_fkey" FOREIGN KEY (article_id) REFERENCES content_articles(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public."contract_scans" ADD CONSTRAINT "contract_scans_contract_version_id_fkey" FOREIGN KEY (contract_version_id) REFERENCES contract_versions(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public."contract_scans" ADD CONSTRAINT "contract_scans_deal_id_fkey" FOREIGN KEY (deal_id) REFERENCES deals(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."contract_versions" ADD CONSTRAINT "contract_versions_deal_id_fkey" FOREIGN KEY (deal_id) REFERENCES deals(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."conversation_messages" ADD CONSTRAINT "conversation_messages_conversation_id_fkey" FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE;
ALTER TABLE public."conversations" ADD CONSTRAINT "conversations_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;
ALTER TABLE public."creator_attributions" ADD CONSTRAINT "creator_attributions_creator_id_fkey" FOREIGN KEY (creator_id) REFERENCES creator_network(id) ON DELETE CASCADE;
ALTER TABLE public."credit_applications" ADD CONSTRAINT "credit_applications_buyer_id_fkey" FOREIGN KEY (buyer_id) REFERENCES buyers(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."credit_applications" ADD CONSTRAINT "credit_applications_deal_id_fkey" FOREIGN KEY (deal_id) REFERENCES deals(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."crm_tasks" ADD CONSTRAINT "crm_tasks_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;
ALTER TABLE public."crm_tasks" ADD CONSTRAINT "crm_tasks_workflow_enrollment_id_fkey" FOREIGN KEY (workflow_enrollment_id) REFERENCES workflow_enrollments(id) ON DELETE SET NULL;
ALTER TABLE public."deal_notes" ADD CONSTRAINT "deal_notes_deal_id_fkey" FOREIGN KEY (deal_id) REFERENCES deals(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."dealer_agreement_signatures" ADD CONSTRAINT "dealer_agreement_signatures_dealer_id_fkey" FOREIGN KEY (dealer_id) REFERENCES dealers(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."dealer_availability" ADD CONSTRAINT "dealer_availability_dealer_id_fkey" FOREIGN KEY (dealer_id) REFERENCES dealers(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."dealer_availability_windows" ADD CONSTRAINT "dealer_availability_windows_availability_id_fkey" FOREIGN KEY (availability_id) REFERENCES dealer_availability(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."dealer_blackout_dates" ADD CONSTRAINT "dealer_blackout_dates_availability_id_fkey" FOREIGN KEY (availability_id) REFERENCES dealer_availability(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."dealer_contact_profiles" ADD CONSTRAINT "dealer_contact_profiles_rooftop_id_fkey" FOREIGN KEY (rooftop_id) REFERENCES dealer_rooftops(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."dealer_feed_configs" ADD CONSTRAINT "dealer_feed_configs_dealer_id_fkey" FOREIGN KEY (dealer_id) REFERENCES dealers(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."dealer_offer_submissions" ADD CONSTRAINT "dealer_offer_submissions_dealer_id_fkey" FOREIGN KEY (dealer_id) REFERENCES dealers(id);
ALTER TABLE public."dealer_offer_submissions" ADD CONSTRAINT "dealer_offer_submissions_vehicle_offer_id_fkey" FOREIGN KEY (vehicle_offer_id) REFERENCES vehicle_offers(id) ON DELETE CASCADE;
ALTER TABLE public."dealer_outreach_log" ADD CONSTRAINT "dealer_outreach_log_dealer_prospect_id_fkey" FOREIGN KEY (dealer_prospect_id) REFERENCES dealer_prospects(id);
ALTER TABLE public."dealer_prospects" ADD CONSTRAINT "dealer_prospects_buyer_opp_id_fkey" FOREIGN KEY (buyer_opp_id) REFERENCES buyer_opportunities(id) ON DELETE CASCADE;
ALTER TABLE public."dealer_prospects" ADD CONSTRAINT "dealer_prospects_rooftop_id_fkey" FOREIGN KEY (rooftop_id) REFERENCES dealer_rooftops(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public."dealer_scorecard_snapshots" ADD CONSTRAINT "dealer_scorecard_snapshots_dealer_id_fkey" FOREIGN KEY (dealer_id) REFERENCES dealers(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."dealers" ADD CONSTRAINT "dealers_rooftop_id_fkey" FOREIGN KEY (rooftop_id) REFERENCES dealer_rooftops(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public."dealers" ADD CONSTRAINT "dealers_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."deals" ADD CONSTRAINT "deals_buyer_id_fkey" FOREIGN KEY (buyer_id) REFERENCES buyers(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."deals" ADD CONSTRAINT "deals_offer_id_fkey" FOREIGN KEY (offer_id) REFERENCES offers(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."deals" ADD CONSTRAINT "deals_vehicle_request_offer_id_fkey" FOREIGN KEY (vehicle_request_offer_id) REFERENCES vehicle_request_offers(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public."deposits" ADD CONSTRAINT "deposits_buyer_id_fkey" FOREIGN KEY (buyer_id) REFERENCES buyers(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."e_sign_envelope_history" ADD CONSTRAINT "e_sign_envelope_history_deal_id_fkey" FOREIGN KEY (deal_id) REFERENCES deals(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."e_sign_envelopes" ADD CONSTRAINT "e_sign_envelopes_deal_id_fkey" FOREIGN KEY (deal_id) REFERENCES deals(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."email_suppression" ADD CONSTRAINT "email_suppression_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE SET NULL;
ALTER TABLE public."email_template_versions" ADD CONSTRAINT "email_template_versions_template_id_fkey" FOREIGN KEY (template_id) REFERENCES email_templates(id) ON DELETE CASCADE;
ALTER TABLE public."external_pre_approvals" ADD CONSTRAINT "external_pre_approvals_buyer_id_fkey" FOREIGN KEY (buyer_id) REFERENCES buyers(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."financing" ADD CONSTRAINT "financing_deal_id_fkey" FOREIGN KEY (deal_id) REFERENCES deals(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."financing_review_tasks" ADD CONSTRAINT "financing_review_tasks_credit_application_id_fkey" FOREIGN KEY (credit_application_id) REFERENCES credit_applications(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."financing_scenarios" ADD CONSTRAINT "financing_scenarios_buyer_id_fkey" FOREIGN KEY (buyer_id) REFERENCES buyers(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."insurance_policies" ADD CONSTRAINT "insurance_policies_buyer_id_fkey" FOREIGN KEY (buyer_id) REFERENCES buyers(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."insurance_quotes" ADD CONSTRAINT "insurance_quotes_buyer_id_fkey" FOREIGN KEY (buyer_id) REFERENCES buyers(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."inventory_items" ADD CONSTRAINT "inventory_items_dealer_id_fkey" FOREIGN KEY (dealer_id) REFERENCES dealers(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public."inventory_items" ADD CONSTRAINT "inventory_items_rooftop_id_fkey" FOREIGN KEY (rooftop_id) REFERENCES dealer_rooftops(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public."inventory_sync_runs" ADD CONSTRAINT "inventory_sync_runs_source_id_fkey" FOREIGN KEY (source_id) REFERENCES inventory_sources(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."lead_scoring_events" ADD CONSTRAINT "lead_scoring_events_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;
ALTER TABLE public."message_thread_participants" ADD CONSTRAINT "message_thread_participants_thread_id_fkey" FOREIGN KEY (thread_id) REFERENCES message_threads(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."messages" ADD CONSTRAINT "messages_thread_id_fkey" FOREIGN KEY (thread_id) REFERENCES message_threads(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."notifications" ADD CONSTRAINT "notifications_affiliate_id_fkey" FOREIGN KEY (affiliate_id) REFERENCES affiliates(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."notifications" ADD CONSTRAINT "notifications_buyer_id_fkey" FOREIGN KEY (buyer_id) REFERENCES buyers(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."notifications" ADD CONSTRAINT "notifications_dealer_id_fkey" FOREIGN KEY (dealer_id) REFERENCES dealers(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."nudge_events" ADD CONSTRAINT "nudge_events_buyer_id_fkey" FOREIGN KEY (buyer_id) REFERENCES buyers(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."offers" ADD CONSTRAINT "offers_auction_id_fkey" FOREIGN KEY (auction_id) REFERENCES auctions(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."offers" ADD CONSTRAINT "offers_dealer_id_fkey" FOREIGN KEY (dealer_id) REFERENCES dealers(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."offers" ADD CONSTRAINT "offers_original_offer_id_fkey" FOREIGN KEY (original_offer_id) REFERENCES offers(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public."outside_auction_invites" ADD CONSTRAINT "outside_auction_invites_auction_id_fkey" FOREIGN KEY (auction_id) REFERENCES auctions(id) ON DELETE CASCADE;
ALTER TABLE public."outside_auction_invites" ADD CONSTRAINT "outside_auction_invites_offer_id_fkey" FOREIGN KEY (offer_id) REFERENCES offers(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public."pickups" ADD CONSTRAINT "pickups_deal_id_fkey" FOREIGN KEY (deal_id) REFERENCES deals(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."pre_qualifications" ADD CONSTRAINT "pre_qualifications_buyer_id_fkey" FOREIGN KEY (buyer_id) REFERENCES buyers(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."prequal_consents" ADD CONSTRAINT "prequal_consents_buyer_id_fkey" FOREIGN KEY (buyer_id) REFERENCES buyers(id) ON DELETE CASCADE;
ALTER TABLE public."prequal_consents" ADD CONSTRAINT "prequal_consents_prequal_id_fkey" FOREIGN KEY (prequal_id) REFERENCES pre_qualifications(id) ON DELETE CASCADE;
ALTER TABLE public."refinance_applications" ADD CONSTRAINT "refinance_applications_buyer_id_fkey" FOREIGN KEY (buyer_id) REFERENCES buyers(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public."refinance_compliance_logs" ADD CONSTRAINT "refinance_compliance_logs_application_id_fkey" FOREIGN KEY (application_id) REFERENCES refinance_applications(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."revenue_attributions" ADD CONSTRAINT "revenue_attributions_post_id_fkey" FOREIGN KEY (post_id) REFERENCES social_posts(id) ON DELETE CASCADE;
ALTER TABLE public."saved_searches" ADD CONSTRAINT "saved_searches_buyer_id_fkey" FOREIGN KEY (buyer_id) REFERENCES buyers(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."sessions" ADD CONSTRAINT "sessions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."shortlist_items" ADD CONSTRAINT "shortlist_items_shortlist_id_fkey" FOREIGN KEY (shortlist_id) REFERENCES shortlists(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."shortlists" ADD CONSTRAINT "shortlists_buyer_id_fkey" FOREIGN KEY (buyer_id) REFERENCES buyers(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."sms_suppression" ADD CONSTRAINT "sms_suppression_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE SET NULL;
ALTER TABLE public."social_performance" ADD CONSTRAINT "social_performance_post_id_fkey" FOREIGN KEY (post_id) REFERENCES social_posts(id) ON DELETE CASCADE;
ALTER TABLE public."social_posts" ADD CONSTRAINT "social_posts_franchise_id_fkey" FOREIGN KEY (franchise_id) REFERENCES content_franchises(id) ON DELETE SET NULL;
ALTER TABLE public."social_posts" ADD CONSTRAINT "social_posts_signal_id_fkey" FOREIGN KEY (signal_id) REFERENCES topic_signals(id) ON DELETE SET NULL;
ALTER TABLE public."social_videos" ADD CONSTRAINT "social_videos_post_id_fkey" FOREIGN KEY (post_id) REFERENCES social_posts(id) ON DELETE CASCADE;
ALTER TABLE public."trade_in_submissions" ADD CONSTRAINT "trade_in_submissions_buyer_id_fkey" FOREIGN KEY (buyer_id) REFERENCES buyers(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."vehicle_offer_dealer_invites" ADD CONSTRAINT "vehicle_offer_dealer_invites_submission_id_fkey" FOREIGN KEY (submission_id) REFERENCES dealer_offer_submissions(id);
ALTER TABLE public."vehicle_offer_dealer_invites" ADD CONSTRAINT "vehicle_offer_dealer_invites_vehicle_offer_id_fkey" FOREIGN KEY (vehicle_offer_id) REFERENCES vehicle_offers(id) ON DELETE CASCADE;
ALTER TABLE public."vehicle_request_buyer_updates" ADD CONSTRAINT "vehicle_request_buyer_updates_request_id_fkey" FOREIGN KEY (request_id) REFERENCES vehicle_requests(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."vehicle_request_due_diligence_checkpoints" ADD CONSTRAINT "vehicle_request_due_diligence_checkpoints_request_id_fkey" FOREIGN KEY (request_id) REFERENCES vehicle_requests(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."vehicle_request_events" ADD CONSTRAINT "vehicle_request_events_request_id_fkey" FOREIGN KEY (request_id) REFERENCES vehicle_requests(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."vehicle_request_financing" ADD CONSTRAINT "vehicle_request_financing_vehicle_request_id_fkey" FOREIGN KEY (vehicle_request_id) REFERENCES vehicle_requests(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."vehicle_request_offers" ADD CONSTRAINT "vehicle_request_offers_request_id_fkey" FOREIGN KEY (request_id) REFERENCES vehicle_requests(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."vehicle_request_research_logs" ADD CONSTRAINT "vehicle_request_research_logs_request_id_fkey" FOREIGN KEY (request_id) REFERENCES vehicle_requests(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."vehicle_requests" ADD CONSTRAINT "vehicle_requests_buyer_id_fkey" FOREIGN KEY (buyer_id) REFERENCES buyers(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."verse_page_assignments" ADD CONSTRAINT "verse_page_assignments_verse_id_fkey" FOREIGN KEY (verse_id) REFERENCES verse_library(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public."workflow_enrollments" ADD CONSTRAINT "workflow_enrollments_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;
ALTER TABLE public."workflow_enrollments" ADD CONSTRAINT "workflow_enrollments_workflow_id_fkey" FOREIGN KEY (workflow_id) REFERENCES workflows(id) ON DELETE CASCADE;
ALTER TABLE public."workflow_execution_log" ADD CONSTRAINT "workflow_execution_log_enrollment_id_fkey" FOREIGN KEY (enrollment_id) REFERENCES workflow_enrollments(id) ON DELETE CASCADE;
ALTER TABLE public."workflow_versions" ADD CONSTRAINT "workflow_versions_workflow_id_fkey" FOREIGN KEY (workflow_id) REFERENCES workflows(id) ON DELETE CASCADE;
