CREATE INDEX ab_test_groups_platform_status_idx ON public.ab_test_groups USING btree (platform, status);
CREATE INDEX ab_test_variants_group_id_idx ON public.ab_test_variants USING btree (group_id);
CREATE UNIQUE INDEX ab_test_variants_group_post_idx ON public.ab_test_variants USING btree (group_id, post_id);
CREATE UNIQUE INDEX accepted_terms_user_id_terms_version_key ON public.accepted_terms USING btree (user_id, terms_version);
CREATE INDEX acquisition_conversations_buyer_id_idx ON public.acquisition_conversations USING btree (buyer_id);
CREATE INDEX acquisition_conversations_session_id_idx ON public.acquisition_conversations USING btree (session_id);
CREATE INDEX admin_audit_logs_admin_id_idx ON public.admin_audit_logs USING btree (admin_id);
CREATE INDEX admin_audit_logs_entity_type_entity_id_idx ON public.admin_audit_logs USING btree (entity_type, entity_id);
CREATE INDEX admin_mfa_email_tokens_admin_id_idx ON public.admin_mfa_email_tokens USING btree (admin_id);
CREATE INDEX admin_sessions_admin_id_idx ON public.admin_sessions USING btree (admin_id);
CREATE UNIQUE INDEX admin_sessions_token_key ON public.admin_sessions USING btree (token);
CREATE UNIQUE INDEX admins_user_id_key ON public.admins USING btree (user_id);
CREATE INDEX affiliate_clicks_affiliate_id_clicked_at_idx ON public.affiliate_clicks USING btree (affiliate_id, clicked_at);
CREATE INDEX affiliate_clicks_affiliate_id_idx ON public.affiliate_clicks USING btree (affiliate_id);
CREATE INDEX affiliate_clicks_clicked_at_idx ON public.affiliate_clicks USING btree (clicked_at);
CREATE INDEX affiliate_clicks_converted_idx ON public.affiliate_clicks USING btree (converted_at) WHERE (converted_at IS NOT NULL);
CREATE INDEX affiliate_clicks_referral_code_idx ON public.affiliate_clicks USING btree (referral_code);
CREATE UNIQUE INDEX affiliate_compliance_records_affiliate_id_key ON public.affiliate_compliance_records USING btree (affiliate_id);
CREATE INDEX affiliate_documents_affiliate_id_idx ON public.affiliate_documents USING btree (affiliate_id);
CREATE UNIQUE INDEX affiliate_payout_schedules_affiliate_id_key ON public.affiliate_payout_schedules USING btree (affiliate_id);
CREATE INDEX affiliate_payouts_affiliate_id_idx ON public.affiliate_payouts USING btree (affiliate_id);
CREATE UNIQUE INDEX affiliate_payouts_one_pending_per_affiliate ON public.affiliate_payouts USING btree (affiliate_id) WHERE (status = 'PENDING'::"PayoutStatus");
CREATE UNIQUE INDEX affiliate_referrals_affiliate_id_referred_user_id_key ON public.affiliate_referrals USING btree (affiliate_id, referred_user_id);
CREATE UNIQUE INDEX affiliate_referrals_referred_user_id_key ON public.affiliate_referrals USING btree (referred_user_id);
CREATE INDEX affiliates_parent_id_idx ON public.affiliates USING btree (parent_id);
CREATE UNIQUE INDEX affiliates_referral_code_key ON public.affiliates USING btree (referral_code);
CREATE UNIQUE INDEX affiliates_unsubscribe_token_key ON public.affiliates USING btree (unsubscribe_token);
CREATE UNIQUE INDEX affiliates_user_id_key ON public.affiliates USING btree (user_id);
CREATE INDEX ai_action_intents_actor_type_actor_id_idx ON public.ai_action_intents USING btree (actor_type, actor_id);
CREATE UNIQUE INDEX ai_action_intents_idempotency_key_key ON public.ai_action_intents USING btree (idempotency_key);
CREATE INDEX ai_action_intents_status_idx ON public.ai_action_intents USING btree (status);
CREATE INDEX ai_action_intents_status_requires_human_approval_idx ON public.ai_action_intents USING btree (status, requires_human_approval);
CREATE UNIQUE INDEX ai_context_cache_buyer_id_key ON public.ai_context_cache USING btree (buyer_id);
CREATE UNIQUE INDEX ai_conversation_contexts_buyer_id_key ON public.ai_conversation_contexts USING btree (buyer_id);
CREATE INDEX ai_media_gen_post_id_idx ON public.ai_media_generations USING btree (social_post_id);
CREATE INDEX ai_media_gen_request_id_idx ON public.ai_media_generations USING btree (higgsfield_request_id);
CREATE INDEX ai_media_gen_status_idx ON public.ai_media_generations USING btree (status);
CREATE INDEX amips_intelligence_snapshots_captured_at_idx ON public.amips_intelligence_snapshots USING btree (captured_at);
CREATE UNIQUE INDEX amips_market_scores_make_model_metro_key ON public.amips_market_scores USING btree (make, model, metro);
CREATE INDEX amips_market_scores_metro_idx ON public.amips_market_scores USING btree (metro);
CREATE INDEX amips_market_scores_overall_idx ON public.amips_market_scores USING btree (overall_buyer_advantage);
CREATE INDEX amips_pages_lifecycle_status_idx ON public.amips_pages USING btree (lifecycle_status);
CREATE INDEX amips_pages_make_model_metro_idx ON public.amips_pages USING btree (make, model, metro);
CREATE INDEX amips_pages_published_at_idx ON public.amips_pages USING btree (published_at);
CREATE UNIQUE INDEX amips_pages_slug_key ON public.amips_pages USING btree (slug);
CREATE INDEX amips_pages_tier_lifecycle_idx ON public.amips_pages USING btree (content_tier, lifecycle_status);
CREATE UNIQUE INDEX apollo_credit_ledger_cycle_key_key ON public.apollo_credit_ledger USING btree (cycle_key);
CREATE INDEX apollo_enrichment_runs_started_at_idx ON public.apollo_enrichment_runs USING btree (started_at);
CREATE INDEX apollo_enrichment_runs_status_idx ON public.apollo_enrichment_runs USING btree (status);
CREATE UNIQUE INDEX apollo_person_candidates_apollo_person_id_key ON public.apollo_person_candidates USING btree (apollo_person_id);
CREATE INDEX apollo_person_candidates_enrichment_status_idx ON public.apollo_person_candidates USING btree (enrichment_status);
CREATE INDEX apollo_person_candidates_rooftop_id_idx ON public.apollo_person_candidates USING btree (rooftop_id);
CREATE INDEX apollo_person_candidates_search_run_key_idx ON public.apollo_person_candidates USING btree (search_run_key);
CREATE UNIQUE INDEX apollo_reveals_rooftop_id_cycle_key_key ON public.apollo_reveals USING btree (rooftop_id, cycle_key);
CREATE INDEX apollo_reveals_rooftop_id_idx ON public.apollo_reveals USING btree (rooftop_id);
CREATE UNIQUE INDEX auction_invitations_auction_id_dealer_id_key ON public.auction_invitations USING btree (auction_id, dealer_id);
CREATE UNIQUE INDEX auctions_deposit_id_key ON public.auctions USING btree (deposit_id);
CREATE INDEX auctions_post_close_unprocessed_idx ON public.auctions USING btree (status) WHERE (post_close_processed_at IS NULL);
CREATE INDEX auctions_vehicle_request_id_idx ON public.auctions USING btree (vehicle_request_id);
CREATE INDEX audit_logs_admin_id_idx ON public.audit_logs USING btree (admin_id);
CREATE INDEX audit_logs_entity_type_entity_id_idx ON public.audit_logs USING btree (entity_type, entity_id);
CREATE INDEX autolenis_intelligence_metro_idx ON public.autolenis_intelligence USING btree (metro);
CREATE UNIQUE INDEX autolenis_intelligence_metro_make_model_period_key ON public.autolenis_intelligence USING btree (metro, vehicle_make, vehicle_model, period_month);
CREATE INDEX autolenis_intelligence_transaction_count_idx ON public.autolenis_intelligence USING btree (transaction_count);
CREATE INDEX buyer_activity_events_buyer_id_created_at_idx ON public.buyer_activity_events USING btree (buyer_id, created_at);
CREATE INDEX buyer_credit_history_buyer_id_idx ON public.buyer_credit_history USING btree (buyer_id);
CREATE UNIQUE INDEX buyer_inventory_preferences_buyer_id_key ON public.buyer_inventory_preferences USING btree (buyer_id);
CREATE UNIQUE INDEX buyer_nudge_preferences_buyer_id_key ON public.buyer_nudge_preferences USING btree (buyer_id);
CREATE INDEX buyer_opportunities_buyer_id_idx ON public.buyer_opportunities USING btree (buyer_id);
CREATE INDEX buyer_opportunities_call_reason_idx ON public.buyer_opportunities USING btree (call_reason);
CREATE INDEX buyer_opportunities_created_at_idx ON public.buyer_opportunities USING btree (created_at DESC);
CREATE INDEX buyer_opportunities_email_idx ON public.buyer_opportunities USING btree (email);
CREATE INDEX buyer_opportunities_phone_idx ON public.buyer_opportunities USING btree (phone);
CREATE INDEX buyer_opportunities_source_idx ON public.buyer_opportunities USING btree (source);
CREATE INDEX buyer_opportunities_temperature_idx ON public.buyer_opportunities USING btree (lead_temperature);
CREATE UNIQUE INDEX buyer_preferences_buyer_id_key ON public.buyer_preferences USING btree (buyer_id);
CREATE INDEX buyer_request_claim_tokens_buyer_id_idx ON public.buyer_request_claim_tokens USING btree (buyer_id);
CREATE INDEX buyer_request_claim_tokens_token_hash_idx ON public.buyer_request_claim_tokens USING btree (token_hash);
CREATE UNIQUE INDEX buyer_request_claim_tokens_token_hash_key ON public.buyer_request_claim_tokens USING btree (token_hash);
CREATE INDEX buyers_affiliate_id_idx ON public.buyers USING btree (affiliate_id);
CREATE UNIQUE INDEX buyers_user_id_key ON public.buyers USING btree (user_id);
CREATE INDEX commissions_affiliate_id_status_idx ON public.commissions USING btree (affiliate_id, status);
CREATE INDEX commissions_payout_id_idx ON public.commissions USING btree (payout_id);
CREATE UNIQUE INDEX commissions_qualifying_event_id_key ON public.commissions USING btree (qualifying_event_id);
CREATE INDEX commissions_status_created_at_idx ON public.commissions USING btree (status, created_at);
CREATE INDEX competitor_insights_week_idx ON public.competitor_insights USING btree (week_of);
CREATE INDEX compliance_events_buyer_id_created_at_idx ON public.compliance_events USING btree (buyer_id, created_at);
CREATE INDEX compliance_events_event_type_idx ON public.compliance_events USING btree (event_type);
CREATE INDEX compliance_events_prequal_application_id_idx ON public.compliance_events USING btree (prequal_application_id);
CREATE UNIQUE INDEX compliance_rules_one_active_per_type ON public.compliance_rules USING btree (rule_type) WHERE (status = 'ACTIVE'::"ComplianceRuleStatus");
CREATE INDEX compliance_rules_rule_type_status_idx ON public.compliance_rules USING btree (rule_type, status);
CREATE UNIQUE INDEX compliance_rules_rule_type_version_key ON public.compliance_rules USING btree (rule_type, version);
CREATE INDEX content_article_versions_article_id_version_number_idx ON public.content_article_versions USING btree (article_id, version_number);
CREATE UNIQUE INDEX content_article_versions_article_id_version_number_key ON public.content_article_versions USING btree (article_id, version_number);
CREATE INDEX content_articles_city_state_idx ON public.content_articles USING btree (city, state);
CREATE INDEX content_articles_cluster_idx ON public.content_articles USING btree (cluster);
CREATE INDEX content_articles_cluster_status_idx ON public.content_articles USING btree (cluster, status);
CREATE INDEX content_articles_lifecycle_status_idx ON public.content_articles USING btree (lifecycle_status);
CREATE INDEX content_articles_metro_idx ON public.content_articles USING btree (metro);
CREATE INDEX content_articles_metro_status_idx ON public.content_articles USING btree (metro, status);
CREATE INDEX content_articles_noindex_idx ON public.content_articles USING btree (noindex);
CREATE INDEX content_articles_published_at_idx ON public.content_articles USING btree (published_at);
CREATE INDEX content_articles_refresh_due_at_idx ON public.content_articles USING btree (refresh_due_at);
CREATE INDEX content_articles_scheduled_at_idx ON public.content_articles USING btree (scheduled_at);
CREATE INDEX content_articles_status_idx ON public.content_articles USING btree (status);
CREATE INDEX content_articles_wave_idx ON public.content_articles USING btree (wave);
CREATE INDEX content_attributions_article_slug_idx ON public.content_attributions USING btree (article_slug);
CREATE INDEX content_attributions_buyer_opp_idx ON public.content_attributions USING btree (buyer_opportunity_id);
CREATE INDEX content_attributions_city_state_idx ON public.content_attributions USING btree (city, state);
CREATE INDEX content_attributions_cluster_idx ON public.content_attributions USING btree (cluster);
CREATE INDEX content_attributions_converted_idx ON public.content_attributions USING btree (converted);
CREATE INDEX content_attributions_metro_idx ON public.content_attributions USING btree (metro);
CREATE INDEX content_derivatives_post_id_idx ON public.content_derivatives USING btree (post_id);
CREATE INDEX content_derivatives_signal_id_idx ON public.content_derivatives USING btree (signal_id);
CREATE INDEX content_derivatives_source_article_id_idx ON public.content_derivatives USING btree (source_article_id);
CREATE INDEX content_franchises_active_idx ON public.content_franchises USING btree (active);
CREATE INDEX content_franchises_slug_idx ON public.content_franchises USING btree (slug);
CREATE INDEX content_generation_job_items_article_id_idx ON public.content_generation_job_items USING btree (article_id);
CREATE INDEX content_generation_job_items_idempotency_key_idx ON public.content_generation_job_items USING btree (idempotency_key);
CREATE INDEX content_generation_job_items_job_id_status_idx ON public.content_generation_job_items USING btree (job_id, status);
CREATE INDEX content_generation_job_items_status_idx ON public.content_generation_job_items USING btree (status);
CREATE INDEX content_generation_jobs_created_at_idx ON public.content_generation_jobs USING btree (created_at);
CREATE INDEX content_generation_jobs_job_type_idx ON public.content_generation_jobs USING btree (job_type);
CREATE INDEX content_generation_jobs_status_idx ON public.content_generation_jobs USING btree (status);
CREATE INDEX content_media_assets_article_id_idx ON public.content_media_assets USING btree (article_id);
CREATE INDEX content_media_assets_status_idx ON public.content_media_assets USING btree (status);
CREATE INDEX content_queue_content_tier_idx ON public.content_queue USING btree (content_tier);
CREATE INDEX content_queue_scheduled_date_idx ON public.content_queue USING btree (scheduled_date);
CREATE INDEX content_queue_status_priority_idx ON public.content_queue USING btree (status, priority_score);
CREATE INDEX content_validation_results_article_id_created_at_idx ON public.content_validation_results USING btree (article_id, created_at);
CREATE INDEX content_validation_results_article_id_idx ON public.content_validation_results USING btree (article_id);
CREATE INDEX content_workflow_events_article_id_idx ON public.content_workflow_events USING btree (article_id);
CREATE INDEX content_workflow_events_created_at_idx ON public.content_workflow_events USING btree (created_at);
CREATE INDEX content_workflow_events_event_type_idx ON public.content_workflow_events USING btree (event_type);
CREATE INDEX content_workflow_events_job_id_idx ON public.content_workflow_events USING btree (job_id);
CREATE INDEX contract_scan_history_deal_id_idx ON public.contract_scan_history USING btree (deal_id);
CREATE INDEX contract_scans_contract_version_id_idx ON public.contract_scans USING btree (contract_version_id);
CREATE INDEX creator_attributions_creator_id_idx ON public.creator_attributions USING btree (creator_id);
CREATE INDEX creator_attributions_post_id_idx ON public.creator_attributions USING btree (post_id);
CREATE INDEX creator_network_platform_idx ON public.creator_network USING btree (platform);
CREATE INDEX creator_network_status_idx ON public.creator_network USING btree (status);
CREATE INDEX credit_applications_buyer_id_status_idx ON public.credit_applications USING btree (buyer_id, status);
CREATE INDEX credit_applications_deal_id_idx ON public.credit_applications USING btree (deal_id);
CREATE UNIQUE INDEX credit_applications_one_active_per_deal ON public.credit_applications USING btree (deal_id) WHERE (status <> 'WITHDRAWN'::"CreditApplicationStatus");
CREATE INDEX credit_applications_status_idx ON public.credit_applications USING btree (status);
CREATE INDEX cron_job_logs_cron_name_started_at_idx ON public.cron_job_logs USING btree (cron_name, started_at);
CREATE UNIQUE INDEX csrf_tokens_token_key ON public.csrf_tokens USING btree (token);
CREATE INDEX deal_notes_deal_id_idx ON public.deal_notes USING btree (deal_id);
CREATE INDEX deal_status_history_deal_id_idx ON public.deal_status_history USING btree (deal_id);
CREATE INDEX deal_timeline_deal_id_occurred_at_idx ON public.deal_timeline USING btree (deal_id, occurred_at);
CREATE INDEX dealer_account_claim_tokens_dealer_id_idx ON public.dealer_account_claim_tokens USING btree (dealer_id);
CREATE INDEX dealer_account_claim_tokens_token_hash_idx ON public.dealer_account_claim_tokens USING btree (token_hash);
CREATE UNIQUE INDEX dealer_account_claim_tokens_token_hash_key ON public.dealer_account_claim_tokens USING btree (token_hash);
CREATE INDEX dealer_agreement_signatures_agreement_version_idx ON public.dealer_agreement_signatures USING btree (agreement_version);
CREATE UNIQUE INDEX dealer_agreement_signatures_dealer_id_key ON public.dealer_agreement_signatures USING btree (dealer_id);
CREATE INDEX dealer_agreement_signatures_signed_at_idx ON public.dealer_agreement_signatures USING btree (signed_at);
CREATE INDEX dealer_applications_status_idx ON public.dealer_applications USING btree (status);
CREATE UNIQUE INDEX dealer_availability_dealer_id_key ON public.dealer_availability USING btree (dealer_id);
CREATE INDEX dealer_availability_windows_availability_id_idx ON public.dealer_availability_windows USING btree (availability_id);
CREATE INDEX dealer_blackout_dates_availability_id_idx ON public.dealer_blackout_dates USING btree (availability_id);
CREATE UNIQUE INDEX dealer_capacity_configs_dealer_id_key ON public.dealer_capacity_configs USING btree (dealer_id);
CREATE UNIQUE INDEX dealer_contact_profiles_apollo_person_id_key ON public.dealer_contact_profiles USING btree (apollo_person_id);
CREATE INDEX dealer_contact_profiles_dnc_status_idx ON public.dealer_contact_profiles USING btree (dnc_status);
CREATE INDEX dealer_contact_profiles_email_key_idx ON public.dealer_contact_profiles USING btree (email_key);
CREATE INDEX dealer_contact_profiles_rooftop_id_email_key_idx ON public.dealer_contact_profiles USING btree (rooftop_id, email_key);
CREATE UNIQUE INDEX dealer_feed_configs_dealer_id_key ON public.dealer_feed_configs USING btree (dealer_id);
CREATE INDEX dealer_intelligence_brand_city_state_idx ON public.dealer_intelligence USING btree (brand, city, state);
CREATE INDEX dealer_intelligence_last_updated_idx ON public.dealer_intelligence USING btree (last_updated);
CREATE INDEX dealer_intelligence_state_idx ON public.dealer_intelligence USING btree (state);
CREATE INDEX dealer_invitations_status_idx ON public.dealer_invitations USING btree (status);
CREATE INDEX dealer_invitations_token_hash_idx ON public.dealer_invitations USING btree (token_hash);
CREATE UNIQUE INDEX dealer_invitations_token_hash_key ON public.dealer_invitations USING btree (token_hash);
CREATE INDEX dealer_invitations_token_idx ON public.dealer_invitations USING btree (token);
CREATE INDEX dealer_outreach_log_dealer_idx ON public.dealer_outreach_log USING btree (dealer_prospect_id);
CREATE INDEX dealer_outreach_log_dealer_prospect_id_outreach_sequence_st_idx ON public.dealer_outreach_log USING btree (dealer_prospect_id, outreach_sequence_step, channel);
CREATE UNIQUE INDEX dealer_outreach_log_live_attempt_key ON public.dealer_outreach_log USING btree (dealer_prospect_id, outreach_sequence_step, channel) WHERE (status <> 'failed'::text);
CREATE INDEX dealer_outreach_log_resend_id_idx ON public.dealer_outreach_log USING btree (resend_id);
CREATE INDEX dealer_outreach_log_sent_at_idx ON public.dealer_outreach_log USING btree (sent_at);
CREATE INDEX dealer_outreach_log_status_idx ON public.dealer_outreach_log USING btree (status);
CREATE INDEX dealer_prospects_buyer_opp_id_idx ON public.dealer_prospects USING btree (buyer_opp_id);
CREATE UNIQUE INDEX dealer_prospects_claim_token_key ON public.dealer_prospects USING btree (claim_token);
CREATE INDEX dealer_prospects_email_idx ON public.dealer_prospects USING btree (email) WHERE (email IS NOT NULL);
CREATE INDEX dealer_prospects_email_source_idx ON public.dealer_prospects USING btree (email_source);
CREATE INDEX dealer_prospects_reply_idx ON public.dealer_prospects USING btree (reply_detected_at) WHERE (reply_detected_at IS NOT NULL);
CREATE INDEX dealer_prospects_rooftop_id_idx ON public.dealer_prospects USING btree (rooftop_id);
CREATE INDEX dealer_prospects_status_buyer_idx ON public.dealer_prospects USING btree (status, buyer_opp_id);
CREATE INDEX dealer_prospects_status_created_idx ON public.dealer_prospects USING btree (status, created_at DESC);
CREATE INDEX dealer_prospects_status_idx ON public.dealer_prospects USING btree (status);
CREATE INDEX dealer_prospects_zip_idx ON public.dealer_prospects USING btree (zip);
CREATE INDEX dealer_rooftops_name_city_state_key_idx ON public.dealer_rooftops USING btree (name_city_state_key);
CREATE INDEX dealer_rooftops_name_zip_key_idx ON public.dealer_rooftops USING btree (name_zip_key);
CREATE INDEX dealer_rooftops_phone_key_idx ON public.dealer_rooftops USING btree (phone_key);
CREATE UNIQUE INDEX dealer_rooftops_website_host_key ON public.dealer_rooftops USING btree (website_host);
CREATE INDEX dealer_scorecard_snapshots_dealer_id_snapshot_date_idx ON public.dealer_scorecard_snapshots USING btree (dealer_id, snapshot_date);
CREATE UNIQUE INDEX dealer_verifications_dealer_id_key ON public.dealer_verifications USING btree (dealer_id);
CREATE INDEX dealers_is_system_placeholder_idx ON public.dealers USING btree (is_system_placeholder) WHERE (is_system_placeholder = true);
CREATE INDEX dealers_rooftop_id_idx ON public.dealers USING btree (rooftop_id);
CREATE UNIQUE INDEX dealers_user_id_key ON public.dealers USING btree (user_id);
CREATE UNIQUE INDEX deals_offer_id_key ON public.deals USING btree (offer_id);
CREATE UNIQUE INDEX deposits_stripe_payment_intent_id_key ON public.deposits USING btree (stripe_payment_intent_id);
