CREATE UNIQUE INDEX deposits_stripe_session_id_key ON public.deposits USING btree (stripe_session_id);
CREATE INDEX e_sign_envelope_history_deal_id_idx ON public.e_sign_envelope_history USING btree (deal_id);
CREATE INDEX e_sign_envelope_history_envelope_id_idx ON public.e_sign_envelope_history USING btree (envelope_id);
CREATE UNIQUE INDEX e_sign_envelopes_deal_id_key ON public.e_sign_envelopes USING btree (deal_id);
CREATE INDEX e_sign_envelopes_document_key_idx ON public.e_sign_envelopes USING btree (document_key);
CREATE INDEX e_sign_envelopes_document_version_id_idx ON public.e_sign_envelopes USING btree (document_version_id);
CREATE UNIQUE INDEX e_sign_envelopes_docusign_envelope_id_key ON public.e_sign_envelopes USING btree (docusign_envelope_id);
CREATE UNIQUE INDEX email_send_logs_idempotency_key_key ON public.email_send_logs USING btree (idempotency_key);
CREATE UNIQUE INDEX feature_flags_key_key ON public.feature_flags USING btree (key);
CREATE INDEX financing_audit_events_credit_application_id_idx ON public.financing_audit_events USING btree (credit_application_id);
CREATE INDEX financing_audit_events_deal_id_idx ON public.financing_audit_events USING btree (deal_id);
CREATE INDEX financing_audit_events_event_type_idx ON public.financing_audit_events USING btree (event_type);
CREATE UNIQUE INDEX financing_audit_events_sequence_key ON public.financing_audit_events USING btree (sequence);
CREATE UNIQUE INDEX financing_deal_id_key ON public.financing USING btree (deal_id);
CREATE INDEX financing_review_tasks_credit_application_id_idx ON public.financing_review_tasks USING btree (credit_application_id);
CREATE UNIQUE INDEX financing_review_tasks_one_open_per_app_type ON public.financing_review_tasks USING btree (credit_application_id, task_type) WHERE (status = ANY (ARRAY['OPEN'::"FinancingReviewTaskStatus", 'IN_PROGRESS'::"FinancingReviewTaskStatus"]));
CREATE INDEX financing_review_tasks_status_task_type_idx ON public.financing_review_tasks USING btree (status, task_type);
CREATE INDEX funnel_stage_snapshots_metric_snapshot_date_idx ON public.funnel_stage_snapshots USING btree (metric, snapshot_date);
CREATE UNIQUE INDEX hope_page_content_section_key ON public.hope_page_content USING btree (section);
CREATE INDEX idx_admin_audit_admin ON public.admin_audit_log USING btree (admin_id, created_at DESC);
CREATE INDEX idx_admin_audit_entity ON public.admin_audit_log USING btree (entity_type, entity_id);
CREATE INDEX idx_ajn_buyer_stage ON public.admin_journey_notes USING btree (buyer_id, stage_id);
CREATE INDEX idx_aju_buyer ON public.admin_journey_unlocks USING btree (buyer_id);
CREATE INDEX idx_av_auction ON public.auction_vehicles USING btree (auction_id);
CREATE INDEX idx_campaign_recipients_campaign ON public.campaign_recipients USING btree (campaign_id);
CREATE INDEX idx_campaign_recipients_contact ON public.campaign_recipients USING btree (contact_id);
CREATE INDEX idx_campaign_recipients_resend_id ON public.campaign_recipients USING btree (resend_id) WHERE (resend_id IS NOT NULL);
CREATE INDEX idx_campaign_recipients_status ON public.campaign_recipients USING btree (campaign_id, status);
CREATE INDEX idx_campaign_recipients_twilio_sid ON public.campaign_recipients USING btree (twilio_sid) WHERE (twilio_sid IS NOT NULL);
CREATE INDEX idx_campaigns_created_at ON public.campaigns USING btree (created_at DESC);
CREATE INDEX idx_campaigns_scheduled_at ON public.campaigns USING btree (scheduled_at) WHERE (scheduled_at IS NOT NULL);
CREATE INDEX idx_campaigns_status ON public.campaigns USING btree (status);
CREATE INDEX idx_comms_outbox_drain ON public.comms_outbox USING btree (run_at) WHERE (status = ANY (ARRAY['pending'::text, 'sending'::text]));
CREATE INDEX idx_contact_identities_contact ON public.contact_identities USING btree (contact_id);
CREATE INDEX idx_contact_identities_lookup ON public.contact_identities USING btree (entity_type, entity_id);
CREATE INDEX idx_contact_timeline_chronology ON public.contact_timeline_events USING btree (contact_id, created_at DESC);
CREATE INDEX idx_contact_timeline_type ON public.contact_timeline_events USING btree (event_type);
CREATE INDEX idx_contacts_assigned ON public.contacts USING btree (assigned_to) WHERE (assigned_to IS NOT NULL);
CREATE UNIQUE INDEX idx_contacts_email_unique_not_null ON public.contacts USING btree (lower(email)) WHERE ((email IS NOT NULL) AND (deleted_at IS NULL));
CREATE INDEX idx_contacts_lead_score ON public.contacts USING btree (lead_score DESC) WHERE (deleted_at IS NULL);
CREATE INDEX idx_contacts_lifecycle ON public.contacts USING btree (lifecycle_stage);
CREATE INDEX idx_contacts_nurture_coverage ON public.contacts USING btree (nurture_status, last_contacted_at) WHERE ((deleted_at IS NULL) AND (do_not_contact = false));
CREATE INDEX idx_contacts_phone ON public.contacts USING btree (phone) WHERE (deleted_at IS NULL);
CREATE INDEX idx_contacts_source ON public.contacts USING btree (source) WHERE (source IS NOT NULL);
CREATE INDEX idx_contacts_utm_source ON public.contacts USING btree (utm_source) WHERE (utm_source IS NOT NULL);
CREATE INDEX idx_conversations_assigned ON public.conversations USING btree (assigned_to) WHERE (assigned_to IS NOT NULL);
CREATE INDEX idx_conversations_contact ON public.conversations USING btree (contact_id);
CREATE INDEX idx_conversations_status ON public.conversations USING btree (status);
CREATE INDEX idx_crm_tasks_contact ON public.crm_tasks USING btree (contact_id) WHERE (contact_id IS NOT NULL);
CREATE INDEX idx_crm_tasks_due ON public.crm_tasks USING btree (due_at) WHERE (status = ANY (ARRAY['open'::text, 'in_progress'::text]));
CREATE INDEX idx_crm_tasks_status_scope ON public.crm_tasks USING btree (status, scope);
CREATE INDEX idx_crm_tasks_workflow_enrollment ON public.crm_tasks USING btree (workflow_enrollment_id) WHERE (workflow_enrollment_id IS NOT NULL);
CREATE INDEX idx_dealer_invites_token ON public.vehicle_offer_dealer_invites USING btree (token);
CREATE INDEX idx_dealer_invites_vehicle_offer ON public.vehicle_offer_dealer_invites USING btree (vehicle_offer_id);
CREATE INDEX idx_deals_vehicle_request_offer_id ON public.deals USING btree (vehicle_request_offer_id);
CREATE INDEX idx_dlq_event ON public.jobs_dead_letter USING btree (event_name);
CREATE INDEX idx_dlq_failed_at ON public.jobs_dead_letter USING btree (failed_at DESC);
CREATE INDEX idx_dos_dealer_id ON public.dealer_offer_submissions USING btree (dealer_id);
CREATE INDEX idx_email_template_versions_template ON public.email_template_versions USING btree (template_id, version DESC);
CREATE INDEX idx_email_templates_category ON public.email_templates USING btree (category);
CREATE INDEX idx_email_templates_status ON public.email_templates USING btree (status);
CREATE UNIQUE INDEX idx_email_templates_template_key ON public.email_templates USING btree (template_key) WHERE (template_key IS NOT NULL);
CREATE INDEX idx_email_templates_updated_at ON public.email_templates USING btree (updated_at DESC);
CREATE INDEX idx_idempotency_created ON public.idempotency_keys USING btree (created_at);
CREATE INDEX idx_lead_nurture_due ON public.lead_nurture_schedule USING btree (run_at) WHERE (status = ANY (ARRAY['pending'::text, 'sending'::text]));
CREATE INDEX idx_lead_scoring_events_contact ON public.lead_scoring_events USING btree (contact_id, occurred_at DESC);
CREATE INDEX idx_lifecycle_touch_due ON public.lifecycle_touch_schedule USING btree (run_at) WHERE (status = ANY (ARRAY['pending'::text, 'sending'::text]));
CREATE INDEX idx_messages_conversation ON public.conversation_messages USING btree (conversation_id, created_at);
CREATE INDEX idx_oai_auction ON public.outside_auction_invites USING btree (auction_id);
CREATE INDEX idx_segments_updated_at ON public.segments USING btree (updated_at DESC);
CREATE INDEX idx_workflow_enrollments_contact ON public.workflow_enrollments USING btree (contact_id);
CREATE INDEX idx_workflow_enrollments_due_resume ON public.workflow_enrollments USING btree (resume_at) WHERE ((resume_at IS NOT NULL) AND (status = 'active'::text));
CREATE INDEX idx_workflow_enrollments_failed ON public.workflow_enrollments USING btree (workflow_id, exited_at DESC) WHERE (status = ANY (ARRAY['failed'::text, 'exited'::text]));
CREATE INDEX idx_workflow_enrollments_status ON public.workflow_enrollments USING btree (status);
CREATE UNIQUE INDEX idx_workflow_enrollments_unique ON public.workflow_enrollments USING btree (workflow_id, contact_id);
CREATE INDEX idx_workflow_exec_log_enrollment ON public.workflow_execution_log USING btree (enrollment_id, executed_at);
CREATE INDEX idx_workflow_exec_log_status ON public.workflow_execution_log USING btree (status);
CREATE INDEX idx_workflow_versions_workflow ON public.workflow_versions USING btree (workflow_id, version DESC);
CREATE INDEX idx_workflows_status ON public.workflows USING btree (status);
CREATE INDEX idx_workflows_trigger ON public.workflows USING btree (trigger_type) WHERE (status = 'active'::text);
CREATE INDEX idx_workflows_updated ON public.workflows USING btree (updated_at DESC);
CREATE UNIQUE INDEX insurance_providers_name_key ON public.insurance_providers USING btree (name);
CREATE INDEX inventory_items_lane_is_active_idx ON public.inventory_items USING btree (lane, is_active);
CREATE INDEX inventory_items_rooftop_id_idx ON public.inventory_items USING btree (rooftop_id);
CREATE INDEX inventory_items_source_adapter_idx ON public.inventory_items USING btree (source_adapter);
CREATE UNIQUE INDEX inventory_items_vin_key ON public.inventory_items USING btree (vin);
CREATE UNIQUE INDEX inventory_quality_scores_inventory_item_id_key ON public.inventory_quality_scores USING btree (inventory_item_id);
CREATE UNIQUE INDEX inventory_sources_type_name_key ON public.inventory_sources USING btree (type, name);
CREATE INDEX inventory_upload_batches_admin_id_idx ON public.inventory_upload_batches USING btree (admin_id);
CREATE INDEX lead_scores_buyer_id_idx ON public.lead_scores USING btree (buyer_id);
CREATE INDEX lead_scores_session_id_idx ON public.lead_scores USING btree (session_id);
CREATE UNIQUE INDEX market_coverage_city_state_key ON public.market_coverage USING btree (city, state);
CREATE INDEX market_intelligence_buyer_leverage_score_idx ON public.market_intelligence USING btree (buyer_leverage_score);
CREATE UNIQUE INDEX market_intelligence_metro_name_state_key ON public.market_intelligence USING btree (metro_name, state);
CREATE INDEX market_intelligence_state_idx ON public.market_intelligence USING btree (state);
CREATE INDEX marketplace_intelligence_make_model_idx ON public.marketplace_intelligence USING btree (vehicle_make, vehicle_model);
CREATE INDEX marketplace_intelligence_metro_idx ON public.marketplace_intelligence USING btree (metro);
CREATE INDEX marketplace_intelligence_transaction_date_idx ON public.marketplace_intelligence USING btree (transaction_date);
CREATE UNIQUE INDEX message_read_receipts_message_id_user_id_key ON public.message_read_receipts USING btree (message_id, user_id);
CREATE UNIQUE INDEX message_thread_participants_thread_id_user_id_key ON public.message_thread_participants USING btree (thread_id, user_id);
CREATE INDEX messages_thread_id_idx ON public.messages USING btree (thread_id);
CREATE UNIQUE INDEX notification_preferences_user_id_key ON public.notification_preferences USING btree (user_id);
CREATE INDEX notifications_affiliate_id_read_at_idx ON public.notifications USING btree (affiliate_id, read_at);
CREATE INDEX notifications_buyer_id_read_at_idx ON public.notifications USING btree (buyer_id, read_at);
CREATE INDEX notifications_dealer_id_read_at_idx ON public.notifications USING btree (dealer_id, read_at);
CREATE UNIQUE INDEX nudge_configurations_stage_key ON public.nudge_configurations USING btree (stage);
CREATE INDEX nudge_events_buyer_id_stage_idx ON public.nudge_events USING btree (buyer_id, stage);
CREATE UNIQUE INDEX offers_original_offer_id_key ON public.offers USING btree (original_offer_id);
CREATE INDEX offers_submitted_by_admin_id_idx ON public.offers USING btree (submitted_by_admin_id) WHERE (submitted_by_admin_id IS NOT NULL);
CREATE INDEX outreach_log_sequence_step_idx ON public.dealer_outreach_log USING btree (outreach_sequence_step);
CREATE UNIQUE INDEX outside_auction_invites_auction_id_rooftop_id_key ON public.outside_auction_invites USING btree (auction_id, rooftop_id);
CREATE UNIQUE INDEX payment_provider_events_event_id_key ON public.payment_provider_events USING btree (event_id);
CREATE UNIQUE INDEX pickups_deal_id_key ON public.pickups USING btree (deal_id);
CREATE INDEX pickups_status_proposed_at_idx ON public.pickups USING btree (status, proposed_at);
CREATE UNIQUE INDEX pre_qualifications_buyer_id_key ON public.pre_qualifications USING btree (buyer_id);
CREATE INDEX prequal_consents_buyer_id_idx ON public.prequal_consents USING btree (buyer_id);
CREATE INDEX prequal_consents_prequal_id_idx ON public.prequal_consents USING btree (prequal_id);
CREATE INDEX rate_limit_events_identifier_endpoint_idx ON public.rate_limit_events USING btree (identifier, endpoint);
CREATE INDEX referral_milestone_configs_is_active_idx ON public.referral_milestone_configs USING btree (is_active);
CREATE INDEX referral_milestone_configs_sort_order_idx ON public.referral_milestone_configs USING btree (sort_order);
CREATE INDEX refinance_applications_created_at_idx ON public.refinance_applications USING btree (created_at);
CREATE UNIQUE INDEX refinance_applications_lead_id_key ON public.refinance_applications USING btree (lead_id);
CREATE INDEX refinance_applications_state_idx ON public.refinance_applications USING btree (state);
CREATE INDEX refinance_applications_status_idx ON public.refinance_applications USING btree (status);
CREATE INDEX revenue_attributions_deal_id_idx ON public.revenue_attributions USING btree (deal_id);
CREATE INDEX revenue_attributions_post_id_idx ON public.revenue_attributions USING btree (post_id);
CREATE INDEX revenue_attributions_status_idx ON public.revenue_attributions USING btree (attribution_status);
CREATE INDEX revenue_attributions_vehicle_request_id_idx ON public.revenue_attributions USING btree (vehicle_request_id);
CREATE UNIQUE INDEX revenue_snapshots_period_key ON public.revenue_snapshots USING btree (period);
CREATE INDEX saved_searches_buyer_id_idx ON public.saved_searches USING btree (buyer_id);
CREATE INDEX search_cache_cache_key_idx ON public.search_cache USING btree (cache_key);
CREATE INDEX search_cache_expires_at_idx ON public.search_cache USING btree (expires_at);
CREATE INDEX search_intelligence_content_tier_idx ON public.search_intelligence USING btree (content_tier);
CREATE INDEX search_intelligence_leads_generated_idx ON public.search_intelligence USING btree (leads_generated);
CREATE UNIQUE INDEX search_intelligence_url_week_of_key ON public.search_intelligence USING btree (url, week_of);
CREATE INDEX search_intelligence_week_of_idx ON public.search_intelligence USING btree (week_of);
CREATE UNIQUE INDEX seo_keywords_keyword_key ON public.seo_keywords USING btree (keyword);
CREATE UNIQUE INDEX seo_page_configs_page_slug_key ON public.seo_page_configs USING btree (page_slug);
CREATE UNIQUE INDEX seo_redirects_from_path_key ON public.seo_redirects USING btree (from_path);
CREATE UNIQUE INDEX seo_sitemap_entries_url_key ON public.seo_sitemap_entries USING btree (url);
CREATE UNIQUE INDEX service_fee_payments_deal_id_key ON public.service_fee_payments USING btree (deal_id);
CREATE UNIQUE INDEX service_fee_payments_stripe_payment_intent_id_key ON public.service_fee_payments USING btree (stripe_payment_intent_id);
CREATE UNIQUE INDEX sessions_token_key ON public.sessions USING btree (token);
CREATE INDEX sessions_user_id_idx ON public.sessions USING btree (user_id);
CREATE UNIQUE INDEX shortlist_items_shortlist_id_inventory_item_id_key ON public.shortlist_items USING btree (shortlist_id, inventory_item_id);
CREATE UNIQUE INDEX shortlists_buyer_id_key ON public.shortlists USING btree (buyer_id);
CREATE INDEX sms_opt_outs_phone_idx ON public.sms_opt_outs USING btree (phone);
CREATE INDEX social_leads_created_at_idx ON public.social_leads USING btree (created_at);
CREATE INDEX social_leads_email_idx ON public.social_leads USING btree (email);
CREATE INDEX social_leads_platform_idx ON public.social_leads USING btree (platform);
CREATE INDEX social_leads_post_id_idx ON public.social_leads USING btree (social_post_id);
CREATE INDEX social_leads_status_idx ON public.social_leads USING btree (status);
CREATE INDEX social_performance_post_id_idx ON public.social_performance USING btree (post_id);
CREATE INDEX social_performance_recorded_at_idx ON public.social_performance USING btree (recorded_at);
CREATE INDEX social_posts_created_at_idx ON public.social_posts USING btree (created_at);
CREATE INDEX social_posts_franchise_id_idx ON public.social_posts USING btree (franchise_id);
CREATE INDEX social_posts_platform_status_idx ON public.social_posts USING btree (platform, status);
CREATE INDEX social_posts_scheduled_at_idx ON public.social_posts USING btree (scheduled_at);
CREATE INDEX social_posts_signal_id_idx ON public.social_posts USING btree (signal_id);
CREATE INDEX social_posts_status_idx ON public.social_posts USING btree (status);
CREATE INDEX social_videos_post_id_idx ON public.social_videos USING btree (post_id);
CREATE INDEX social_videos_provider_job_id_idx ON public.social_videos USING btree (provider_job_id);
CREATE INDEX social_videos_status_idx ON public.social_videos USING btree (status);
CREATE UNIQUE INDEX system_configurations_key_key ON public.system_configurations USING btree (key);
CREATE INDEX topic_signals_assets_generated_idx ON public.topic_signals USING btree (assets_generated);
CREATE INDEX topic_signals_detected_at_idx ON public.topic_signals USING btree (detected_at);
CREATE INDEX topic_signals_expires_at_idx ON public.topic_signals USING btree (expires_at);
CREATE INDEX topic_signals_make_model_city_idx ON public.topic_signals USING btree (make, model, city);
CREATE INDEX topic_signals_type_idx ON public.topic_signals USING btree (signal_type);
CREATE UNIQUE INDEX trade_in_valuations_trade_in_id_key ON public.trade_in_valuations USING btree (trade_in_id);
CREATE UNIQUE INDEX uniq_mv_funnel_metrics_day ON public.mv_funnel_metrics USING btree (day);
CREATE UNIQUE INDEX uq_comms_outbox_dedup_key ON public.comms_outbox USING btree (dedup_key);
CREATE UNIQUE INDEX uq_email_templates_template_key ON public.email_templates USING btree (template_key) WHERE (template_key IS NOT NULL);
CREATE UNIQUE INDEX uq_lead_nurture_key_step ON public.lead_nurture_schedule USING btree (idempotency_key, step);
CREATE UNIQUE INDEX uq_lead_scoring_events_idem ON public.lead_scoring_events USING btree (idempotency_key) WHERE (idempotency_key IS NOT NULL);
CREATE UNIQUE INDEX uq_lifecycle_touch_key_sequence ON public.lifecycle_touch_schedule USING btree (base_key, sequence);
CREATE UNIQUE INDEX user_preferences_user_id_key ON public.user_preferences USING btree (user_id);
CREATE UNIQUE INDEX users_email_key ON public.users USING btree (email);
CREATE UNIQUE INDEX users_supabase_id_key ON public.users USING btree (supabase_id);
CREATE INDEX vehicle_intelligence_last_updated_idx ON public.vehicle_intelligence USING btree (last_updated);
CREATE INDEX vehicle_intelligence_make_model_idx ON public.vehicle_intelligence USING btree (make, model);
CREATE UNIQUE INDEX vehicle_intelligence_make_model_trim_year_key ON public.vehicle_intelligence USING btree (make, model, "trim", year) NULLS NOT DISTINCT;
CREATE UNIQUE INDEX vehicle_match_scores_buyer_id_inventory_item_id_key ON public.vehicle_match_scores USING btree (buyer_id, inventory_item_id);
CREATE UNIQUE INDEX vehicle_request_financing_vehicle_request_id_key ON public.vehicle_request_financing USING btree (vehicle_request_id);
CREATE INDEX vehicle_request_match_results_request_id_idx ON public.vehicle_request_match_results USING btree (request_id);
CREATE UNIQUE INDEX vehicle_request_match_results_request_id_inventory_item_id_key ON public.vehicle_request_match_results USING btree (request_id, inventory_item_id);
CREATE INDEX vehicle_requests_buyer_id_status_idx ON public.vehicle_requests USING btree (buyer_id, status);
CREATE INDEX vehicle_requests_buyer_opportunity_id_idx ON public.vehicle_requests USING btree (buyer_opportunity_id);
CREATE INDEX vehicle_requests_coverage_hold_at_idx ON public.vehicle_requests USING btree (coverage_hold_at);
CREATE INDEX vehiclerequest_buyer_opportunity_idx ON public.vehicle_requests USING btree (buyer_opportunity_id);
CREATE UNIQUE INDEX verse_library_reference_key ON public.verse_library USING btree (reference);
CREATE UNIQUE INDEX verse_page_assignments_page_key_effective_at_key ON public.verse_page_assignments USING btree (page_key, effective_at);
CREATE INDEX verse_page_assignments_page_key_is_active_idx ON public.verse_page_assignments USING btree (page_key, is_active);
CREATE UNIQUE INDEX violation_pattern_records_dealer_id_rule_id_key ON public.violation_pattern_records USING btree (dealer_id, rule_id);
CREATE INDEX winning_patterns_platform_franchise_idx ON public.winning_patterns USING btree (platform, franchise_slug);
CREATE INDEX winning_patterns_platform_hook_idx ON public.winning_patterns USING btree (platform, hook_type);
