import type { Metadata } from "next";

export const metadata: Metadata = { title: "Prequalification" };

import { requireBuyer } from "@/lib/auth/session";
import { redirect } from "next/navigation";
import PrequalFormClient from "@/components/buyer/PrequalFormClient";
import PrequalBudgetCalculator from "@/components/buyer/PrequalBudgetCalculator";
import { formatCents, cn } from "@/lib/utils";
import { CARD, TONE_STYLES, type Tone } from "@/components/ui/patterns/tokens";
import {
  getStabilityFactor,
  FRONT_END_AUTO_DTI,
  BACK_END_TOTAL_DTI,
} from "@/lib/services/prequal/income-gate";
import {
  CheckCircle2,
  Clock,
  ArrowRight,
  RefreshCw,
  ShieldCheck,
  ChevronRight,
  Star,
  CalendarDays,
  Info,
  AlertCircle,
  Sparkles,
  TrendingUp,
  Search,
  ListChecks,
  BadgeCheck,
  Banknote,
  Calculator,
  Car,
  FileText,
  Pen,
  Package,
  type LucideIcon,
} from "lucide-react";
import Link from "next/link";
import ExpandableSection from "@/components/buyer/prequal/ExpandableSection";

export const dynamic = "force-dynamic";

// Tier → sanctioned tone (kit palette only — no ad-hoc hues on the dashboard).
const TIER_LABELS: Record<string, { label: string; tone: Tone }> = {
  STRONG: { label: "Strong", tone: "success" },
  GOOD: { label: "Good", tone: "brand" },
  FAIR: { label: "Fair", tone: "warning" },
  WEAK: { label: "Weak", tone: "warning" },
  DECLINED: { label: "Declined", tone: "danger" },
};

function getPrequalSource(prequal: {
  isExternal: boolean;
  rawResponse: string | null;
}): { label: string; detail: string } {
  if (prequal.isExternal) {
    return { label: "External Financing", detail: "Your approval was submitted via external lender or financing source." };
  }
  if (prequal.rawResponse) {
    return { label: "iPredict™ Credit Analysis", detail: "Your approval was generated by AutoLenis iPredict™ powered by MicroBilt." };
  }
  return { label: "Manual / Admin Override", detail: "Your approval was set manually by the AutoLenis team." };
}

function getDaysRemaining(expiresAt: Date): number {
  return Math.max(0, Math.floor((expiresAt.getTime() - Date.now()) / (1000 * 60 * 60 * 24)));
}

export default async function PrequalPage() {
  const buyer = await requireBuyer();
  const prequal = buyer.preQualification;

  // Pending manual review — show the pending page.
  if (
    prequal &&
    (prequal.decision === "MANUAL_REVIEW" ||
      prequal.decision === "OFAC_ESCALATED" ||
      prequal.decision === "OFAC_REVIEW")
  ) {
    redirect("/buyer/prequal/pending");
  }

  // Approved and not yet expired — show premium status dashboard.
  if (prequal && prequal.decision === "APPROVED" && prequal.expiresAt > new Date()) {
    const now = new Date();
    const expiresLabel = prequal.expiresAt.toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    });
    const createdLabel = prequal.createdAt.toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    });
    const updatedLabel = prequal.updatedAt.toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    });

    const daysRemaining = getDaysRemaining(prequal.expiresAt);
    const isNearExpiry = daysRemaining <= 7;
    const tierInfo = prequal.tier ? TIER_LABELS[prequal.tier] : null;
    const source = getPrequalSource(prequal);

    // Recommended search range: 90% of approved max
    const recommendedMaxCents = Math.floor(prequal.maxOtdAmountCents * 0.9);

    // ── Budget math (FIX 8 transparency) ──────────────────────────────────────
    // Only shown for income-based iPredict approvals (not external / manual).
    const showBudgetMath =
      prequal.monthlyIncomeCents != null &&
      prequal.monthlyIncomeCents > 0 &&
      prequal.benchmarkAprBps != null;

    let budgetMath: {
      effectiveIncomeCents: number;
      housingCents: number;
      otherDebtCents: number;
      totalExistingCents: number;
      totalCapacityCents: number;
      availableAutoCents: number;
      benchmarkAprLabel: string;
    } | null = null;

    if (showBudgetMath) {
      // Prefer the persisted effective income; fall back to recomputing it from
      // the stored income + stability haircut for older records.
      const stabilityFactor = getStabilityFactor(
        prequal.employmentStatus,
        prequal.lengthOfEmployment,
      );
      const effectiveIncomeCents =
        prequal.effectiveIncomeCents ??
        Math.round(prequal.monthlyIncomeCents! * stabilityFactor);
      const housingCents = prequal.monthlyHousingPaymentCents ?? 0;
      const otherDebtCents = prequal.monthlyOtherDebtCents ?? 0;
      const totalExistingCents = housingCents + otherDebtCents;
      const totalCapacityCents = Math.round(effectiveIncomeCents * BACK_END_TOTAL_DTI);
      const frontEndMaxCents = Math.round(effectiveIncomeCents * FRONT_END_AUTO_DTI);
      const backEndMaxCents = totalCapacityCents - totalExistingCents;
      const availableAutoCents = Math.max(0, Math.min(frontEndMaxCents, backEndMaxCents));
      budgetMath = {
        effectiveIncomeCents,
        housingCents,
        otherDebtCents,
        totalExistingCents,
        totalCapacityCents,
        availableAutoCents,
        benchmarkAprLabel: `${(prequal.benchmarkAprBps! / 100).toFixed(2)}%`,
      };
    }

    return (
      <div className="min-h-screen bg-gradient-to-br from-al-bg via-white to-al-primary-subtle" data-testid="prequal-status-page">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-8 space-y-6">

          {/* ── Hero card ───────────────────────────────────────────────── */}
          <div
            className="relative rounded-3xl overflow-hidden"
            data-testid="prequal-hero-card"
          >
            {/* Gradient background */}
            <div className="absolute inset-0 bg-gradient-to-br from-al-primary via-al-primary-hover to-[#083FA0]" />
            {/* Decorative circles */}
            <div className="absolute -top-16 -right-16 w-64 h-64 rounded-full bg-white/5" />
            <div className="absolute -bottom-8 -left-8 w-48 h-48 rounded-full bg-white/5" />

            <div className="relative px-8 py-10">
              {/* Status badge */}
              <div className="flex flex-wrap items-center gap-3 mb-8">
                <div className="flex items-center gap-1.5 bg-green-400/20 text-green-200 text-xs font-semibold px-3 py-1.5 rounded-full border border-green-400/30">
                  <CheckCircle2 size={13} />
                  Pre-Qualification Approved
                </div>
                {tierInfo && (
                  <div className={`flex items-center gap-1.5 bg-white/15 text-white text-xs font-semibold px-3 py-1.5 rounded-full border border-white/20`}>
                    <Star size={12} />
                    {tierInfo.label} Credit Profile
                  </div>
                )}
                {source.label === "iPredict™ Credit Analysis" && (
                  <div className="flex items-center gap-1.5 bg-white/10 text-white/80 text-xs font-medium px-3 py-1.5 rounded-full border border-white/15">
                    <Sparkles size={12} />
                    iPredict™
                  </div>
                )}
              </div>

              {/* Budget display */}
              <div className="mb-8" data-testid="prequal-budget-display">
                <p className="text-white/60 text-xs uppercase tracking-widest mb-2">
                  Approved Max Out-the-Door Budget
                </p>
                <p className="text-5xl sm:text-6xl font-mono tabular-nums font-extrabold text-white tracking-tight mb-2">
                  {formatCents(prequal.maxOtdAmountCents)}
                </p>
                <p className="text-white/60 text-sm">
                  Maximum total purchase price including all taxes, fees, and add-ons
                </p>
              </div>

              {/* Expiry strip */}
              <div
                className={`flex flex-wrap items-center gap-4 border-t border-white/15 pt-5 ${isNearExpiry ? "text-amber-200" : "text-white/70"}`}
                data-testid="prequal-expiry-block"
              >
                <div className="flex items-center gap-2 text-sm">
                  <Clock size={14} className="shrink-0" />
                  <span>Expires {expiresLabel}</span>
                </div>
                <div className={`flex items-center gap-2 text-sm font-semibold px-3 py-1 rounded-full ${isNearExpiry ? "bg-amber-400/20 text-amber-200 border border-amber-400/30" : "bg-white/10 text-white border border-white/15"}`}>
                  <CalendarDays size={13} />
                  {daysRemaining === 0 ? "Expires today" : `${daysRemaining} day${daysRemaining !== 1 ? "s" : ""} remaining`}
                </div>
              </div>
            </div>
          </div>

          {/* ── Detail cards row ─────────────────────────────────────────── */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {/* Approval status */}
            <DetailCard
              icon={ShieldCheck}
              tone="success"
              label="Approval Status"
              value="Approved"
              sub="Active & valid"
              testId="prequal-approval-status-card"
            />

            {/* Credit profile */}
            {tierInfo ? (
              <DetailCard
                icon={Star}
                tone={tierInfo.tone}
                label="Credit Profile"
                value={`${tierInfo.label} Profile`}
                sub="Based on iPredict analysis"
                testId="prequal-credit-tier-card"
              />
            ) : (
              <DetailCard
                icon={Info}
                tone="neutral"
                label="Credit Profile"
                value="Not available"
                sub="No tier assigned"
                testId="prequal-credit-tier-card"
              />
            )}

            {/* Prequal source */}
            <DetailCard
              icon={BadgeCheck}
              tone="brand"
              label="Approval Source"
              value={source.label}
              sub={source.detail}
              testId="prequal-source-card"
            />

            {/* Created date */}
            <DetailCard
              icon={CalendarDays}
              tone="indigo"
              label="Submitted"
              value={createdLabel}
              sub="Original application date"
              testId="prequal-created-date-card"
            />

            {/* Last updated */}
            <DetailCard
              icon={TrendingUp}
              tone="neutral"
              label="Last Updated"
              value={updatedLabel}
              sub="Most recent change"
              testId="prequal-updated-date-card"
            />

            {/* Recommended search range */}
            <DetailCard
              icon={Search}
              tone="brand"
              label="Recommended Search Range"
              value={`Up to ${formatCents(recommendedMaxCents)}`}
              sub="~90% of approved max — leaves room for taxes & fees"
              testId="prequal-recommended-range-card"
            />
          </div>

          {/* ── Interactive Budget Calculator ────────────────────────────── */}
          <PrequalBudgetCalculator maxOtdAmountCents={prequal.maxOtdAmountCents} />

          {/* ── Expandable sections ──────────────────────────────────────── */}
          <div className="space-y-3">
            {budgetMath && (
              <ExpandableSection
                title="How We Calculated Your Budget"
                icon={<Calculator size={16} className="text-al-primary" />}
                testId="prequal-budget-calculation"
              >
                <div className="space-y-1 text-sm" data-testid="prequal-budget-calculation-rows">
                  <CalcRow
                    label="Monthly income (after stability adjustment)"
                    value={formatCents(budgetMath.effectiveIncomeCents)}
                  />
                  <CalcRow
                    label="Housing payment"
                    value={`– ${formatCents(budgetMath.housingCents)}`}
                  />
                  <CalcRow
                    label="Other debt payments"
                    value={`– ${formatCents(budgetMath.otherDebtCents)}`}
                  />
                  <CalcRow
                    label="Total existing obligations"
                    value={formatCents(budgetMath.totalExistingCents)}
                    muted
                  />
                  <div className="my-2 border-t border-slate-100" />
                  <CalcRow
                    label="Max total payment capacity (45% rule)"
                    value={formatCents(budgetMath.totalCapacityCents)}
                  />
                  <CalcRow
                    label="Available for auto payment / month"
                    value={formatCents(budgetMath.availableAutoCents)}
                    emphasize
                  />
                  <CalcRow
                    label="Benchmark APR for your tier"
                    value={budgetMath.benchmarkAprLabel}
                  />
                  <div className="my-2 border-t border-slate-100" />
                  <CalcRow
                    label="Approved max out-the-door budget"
                    value={formatCents(prequal.maxOtdAmountCents)}
                    emphasize
                  />
                </div>
                <p className="mt-4 text-xs text-slate-500 leading-relaxed">
                  We use the more conservative of two limits — your auto payment stays within 20% of
                  income (front-end), and your total debt stays within 45% of income (back-end). Your
                  final budget is the lower of what your income supports and what your credit profile
                  qualifies for. This mirrors the underwriting used by major auto lenders and credit
                  unions.
                </p>
              </ExpandableSection>
            )}
            <ExpandableSection
              title="How Your Budget Works"
              icon={<Banknote size={16} className="text-al-primary" />}
              testId="prequal-how-budget-works"
            >
              <div className="space-y-3 text-sm text-slate-600 leading-relaxed">
                <p>
                  Your approved max out-the-door (OTD) amount of{" "}
                  <strong className="text-slate-800">{formatCents(prequal.maxOtdAmountCents)}</strong> is
                  the maximum <em>total</em> purchase price you are pre-qualified for.
                </p>
                <p>
                  The OTD amount includes <strong>all</strong> costs: vehicle price, sales tax,
                  registration, dealer fees, and any optional add-ons. Your vehicle price alone
                  must stay below this limit after those costs are added.
                </p>
                <p>
                  We recommend searching for vehicles priced up to{" "}
                  <strong className="text-slate-800">{formatCents(recommendedMaxCents)}</strong> (~90% of
                  your approved max) to leave room for taxes and fees.
                </p>
              </div>
            </ExpandableSection>

            <ExpandableSection
              title="What This Means for You"
              icon={<Info size={16} className="text-blue-600" />}
              testId="prequal-what-this-means"
            >
              <div className="space-y-3 text-sm text-slate-600 leading-relaxed">
                <p>
                  This pre-qualification is a <strong>soft inquiry</strong> and does not impact your
                  credit score. It reflects your estimated buying power based on the credit
                  information available at the time of your application.
                </p>
                <p>
                  A pre-qualification is <strong>not a guarantee of financing</strong>. Final loan
                  approval, rate, and terms are determined by the lender after reviewing your full
                  credit profile, the specific vehicle, and other factors.
                </p>
                <p>AutoLenis is not a lender or dealer.</p>
                {tierInfo && (
                  <p>
                    Your <strong>{tierInfo.label}</strong> credit profile is used to estimate the
                    types of financing terms you may qualify for. Stronger profiles typically
                    receive lower rates and better loan terms.
                  </p>
                )}
              </div>
            </ExpandableSection>

            <ExpandableSection
              title="Important Limitations"
              icon={<AlertCircle size={16} className="text-amber-600" />}
              testId="prequal-limitations"
            >
              <div className="space-y-3 text-sm text-slate-600 leading-relaxed">
                <ul className="list-disc pl-4 space-y-2">
                  <li>
                    This approval expires on <strong>{expiresLabel}</strong>
                    {daysRemaining > 0 ? ` (${daysRemaining} days from today)` : " (today)"}. After
                    expiration, a new application will be required.
                  </li>
                  <li>
                    Your approved budget cannot be increased through this portal. Contact the
                    AutoLenis team if you need a re-evaluation.
                  </li>
                  <li>
                    Taxes, registration fees, dealer fees, and add-ons must all fit within your
                    approved OTD budget. They are not added on top.
                  </li>
                  <li>
                    The calculator on this page is an estimate only and does not reflect actual
                    lender quotes or final contract terms.
                  </li>
                  <li>
                    Pre-qualification is valid only for vehicles listed on the AutoLenis platform
                    in auctions you are invited to.
                  </li>
                </ul>
              </div>
            </ExpandableSection>
          </div>

          {/* ── Next Steps checklist ─────────────────────────────────────── */}
          <div
            className="bg-white border border-slate-200 rounded-2xl p-6"
            data-testid="prequal-next-steps"
          >
            <div className="flex items-center gap-2 mb-5">
              <ListChecks size={18} className="text-al-primary" />
              <h3 className="font-semibold text-slate-900">Your Buying Journey</h3>
            </div>
            <div className="space-y-3">
              <JourneyStep icon={<CheckCircle2 size={15} className="text-emerald-600" />} label="Pre-Qual complete" done />
              <JourneyStep icon={<Car size={15} className="text-al-primary" />} label="Search vehicles within your budget" current />
              <JourneyStep icon={<ListChecks size={15} className="text-slate-400" />} label="Build your shortlist" />
              <JourneyStep icon={<Banknote size={15} className="text-slate-400" />} label="Pay the Auction Access Deposit" />
              <JourneyStep icon={<TrendingUp size={15} className="text-slate-400" />} label="Participate in auction" />
              <JourneyStep icon={<FileText size={15} className="text-slate-400" />} label="Select deal & finalize financing" />
              <JourneyStep icon={<Pen size={15} className="text-slate-400" />} label="Sign contract" />
              <JourneyStep icon={<Package size={15} className="text-slate-400" />} label="Vehicle pickup" />
            </div>
          </div>

          {/* ── CTA buttons ──────────────────────────────────────────────── */}
          <div className="flex flex-col sm:flex-row gap-3 pb-8">
            <Link
              href="/buyer/search"
              data-testid="prequal-search-vehicles-btn"
              className="flex-1 flex items-center justify-center gap-2 bg-al-primary hover:bg-al-primary-hover text-white font-semibold py-3.5 px-6 rounded-xl transition-colors text-sm shadow-md shadow-al-primary/20"
            >
              Browse Vehicles Within My Budget
              <ArrowRight size={16} />
            </Link>
            <Link
              href="/buyer/prequal/external"
              data-testid="prequal-update-btn"
              className="flex-1 flex items-center justify-center gap-2 border border-slate-200 hover:bg-slate-50 text-slate-700 font-semibold py-3.5 px-6 rounded-xl transition-colors text-sm"
            >
              <RefreshCw size={15} />
              Update or Use External Financing
            </Link>
          </div>
        </div>
      </div>
    );
  }

  // No prequal, declined, or expired — show the application form.
  const now = new Date();
  const isExpired = Boolean(prequal && prequal.expiresAt && prequal.expiresAt <= now);
  return (
    <PrequalFormClient
      expired={isExpired}
      initial={{
        firstName:        buyer.firstName      ?? undefined,
        lastName:         buyer.lastName       ?? undefined,
        address:          buyer.address        ?? undefined,
        city:             buyer.city           ?? undefined,
        state:            buyer.state          ?? undefined,
        zip:              buyer.zip            ?? undefined,
        employmentStatus: prequal?.employmentStatus ?? undefined,
      }}
    />
  );
}

// ── Sub-components ──────────────────────────────────────────────────────────

function DetailCard({
  icon: Icon,
  tone,
  label,
  value,
  sub,
  testId,
}: {
  icon: LucideIcon;
  tone: Tone;
  label: string;
  value: string;
  sub: string;
  testId?: string;
}) {
  const t = TONE_STYLES[tone];
  return (
    <div className={cn(CARD, "p-5 flex flex-col gap-3")} data-testid={testId}>
      <div className={cn("w-9 h-9 rounded-xl flex items-center justify-center", t.iconBg)}>
        <Icon size={18} className={t.iconText} />
      </div>
      <div>
        <p className="text-xs text-slate-500 mb-0.5">{label}</p>
        <p className="text-sm font-semibold text-slate-900 tabular-nums">{value}</p>
        <p className="text-xs text-slate-500 mt-0.5 leading-relaxed">{sub}</p>
      </div>
    </div>
  );
}

function CalcRow({
  label,
  value,
  muted = false,
  emphasize = false,
}: {
  label: string;
  value: string;
  muted?: boolean;
  emphasize?: boolean;
}) {
  return (
    <div className="flex items-baseline justify-between gap-4 py-1">
      <span className={`${muted ? "text-slate-400" : "text-slate-600"} ${emphasize ? "font-semibold text-slate-900" : ""}`}>
        {label}
      </span>
      <span
        className={`font-mono tabular-nums shrink-0 ${emphasize ? "font-bold text-al-primary" : muted ? "text-slate-400" : "text-slate-700"}`}
      >
        {value}
      </span>
    </div>
  );
}

function JourneyStep({
  icon,
  label,
  done = false,
  current = false,
}: {
  icon: React.ReactNode;
  label: string;
  done?: boolean;
  current?: boolean;
}) {
  return (
    <div className={`flex items-center gap-3 py-2 px-3 rounded-lg ${current ? "bg-al-primary/5 border border-al-primary/15" : ""}`}>
      <span className="shrink-0">{icon}</span>
      <span
        className={`text-sm ${done ? "text-emerald-700 font-medium" : current ? "text-al-primary font-semibold" : "text-slate-400"}`}
      >
        {label}
      </span>
      {done && <CheckCircle2 size={13} className="text-emerald-500 ml-auto shrink-0" />}
      {current && <ChevronRight size={13} className="text-al-primary ml-auto shrink-0" />}
    </div>
  );
}

