// /admin/vehicle-offers — list of dealer offer links generated by admin.
import { requireAdmin } from "@/lib/auth/admin-session";
import { prisma } from "@/lib/prisma";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Car, PlusCircle } from "lucide-react";

export const dynamic = "force-dynamic";

export default async function AdminVehicleOffersPage() {
  await requireAdmin();

  const offers = await prisma.vehicleOffer.findMany({
    include: { _count: { select: { submissions: true } } },
    orderBy: { createdAt: "desc" },
    take: 100,
  });

  return (
    <div className="p-6 md:p-8 max-w-6xl" data-testid="admin-vehicle-offers-page">
      <div className="flex items-center gap-3 mb-6">
        <Car size={22} className="text-al-primary" />
        <h1 className="text-xl font-bold text-slate-900">Dealer Offer Links</h1>
        <Badge variant="secondary" className="text-xs">{offers.length}</Badge>
        <Link
          href="/admin/vehicle-offers/new"
          data-testid="create-offer-link-btn"
          className="ml-auto inline-flex items-center gap-1.5 px-3 py-1.5 bg-al-primary hover:bg-[#0944a8] text-white rounded-lg text-xs font-semibold transition-colors"
        >
          <PlusCircle size={13} /> Create Offer Link
        </Link>
      </div>

      {offers.length === 0 ? (
        <div className="bg-white rounded-2xl border-2 border-dashed border-slate-200 p-12 text-center" data-testid="no-offers">
          <Car size={32} className="text-slate-300 mx-auto mb-3" />
          <p className="text-sm font-semibold text-slate-700 mb-1">No vehicle offer links created yet.</p>
          <p className="text-xs text-slate-500 mb-4">Generate a tokenized link and share with dealers to collect competing offers.</p>
          <Link
            href="/admin/vehicle-offers/new"
            data-testid="empty-create-offer-link"
            className="inline-flex items-center gap-2 bg-al-primary hover:bg-[#0944a8] text-white rounded-lg px-4 py-2 text-sm font-semibold transition-colors"
          >
            <PlusCircle size={14} /> Create Offer Link →
          </Link>
        </div>
      ) : (
        <div className="space-y-3">
          {offers.map((o) => {
            const expired = o.expiresAt ? o.expiresAt < new Date() : false;
            const submissionCount = o._count.submissions;
            return (
              <Link
                key={o.id}
                href={`/admin/vehicle-offers/${o.id}`}
                data-testid={`offer-row-${o.id}`}
                className="flex items-center justify-between bg-white border border-slate-200 rounded-xl px-5 py-4 hover:border-al-primary/30 transition-colors"
              >
                <div className="min-w-0 flex-1">
                  <p className="font-semibold text-slate-900 text-sm truncate">
                    {o.vehicleYear} {o.vehicleMake} {o.vehicleModel}
                    {o.vehicleTrim && <span className="text-slate-400 font-normal"> {o.vehicleTrim}</span>}
                  </p>
                  <p className="text-xs text-slate-400 mt-0.5">
                    Budget: {o.buyerBudget} · ZIP {o.buyerZip} · Created {o.createdAt.toLocaleDateString()}
                    {o.referenceId ? ` · Ref ${o.referenceId}` : ""}
                  </p>
                </div>
                <div className="flex items-center gap-2 flex-wrap justify-end ml-4">
                  <span
                    className={`text-xs font-semibold px-2.5 py-1 rounded-full ${submissionCount > 0 ? "bg-green-100 text-green-700" : "bg-slate-100 text-slate-500"}`}
                    data-testid={`submission-count-${o.id}`}
                  >
                    {submissionCount} submission{submissionCount === 1 ? "" : "s"}
                  </span>
                  {o.expiresAt ? (
                    <Badge variant={expired ? "secondary" : "outline"} className="text-xs">
                      {expired ? "Expired" : `Expires ${o.expiresAt.toLocaleDateString()}`}
                    </Badge>
                  ) : (
                    <Badge variant="outline" className="text-xs">No expiry</Badge>
                  )}
                  <span className="text-xs text-al-primary font-medium">View →</span>
                </div>
              </Link>
            );
          })}
        </div>
      )}
    </div>
  );
}
