-- ============================================================================
-- Baseline: foreign keys for the manual-provisioned tables.
--
-- Companion to 20260423999999_baseline_manual_provisioned_tables. Runs late
-- (after every table referenced by these FKs exists, including core Prisma
-- tables created throughout the migration history) so table-creation order is
-- never a constraint. Each FK is guarded by a pg_constraint existence check, so
-- this is a safe no-op on environments where the constraints already exist.
-- ============================================================================

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ab_test_variants_group_id_fkey') THEN ALTER TABLE "ab_test_variants" ADD CONSTRAINT "ab_test_variants_group_id_fkey" FOREIGN KEY (group_id) REFERENCES ab_test_groups(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'affiliate_documents_affiliate_id_fkey') THEN ALTER TABLE "affiliate_documents" ADD CONSTRAINT "affiliate_documents_affiliate_id_fkey" FOREIGN KEY (affiliate_id) REFERENCES affiliates(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'affiliate_payout_methods_affiliate_id_fkey') THEN ALTER TABLE "affiliate_payout_methods" ADD CONSTRAINT "affiliate_payout_methods_affiliate_id_fkey" FOREIGN KEY (affiliate_id) REFERENCES affiliates(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'auction_vehicles_auction_id_fkey') THEN ALTER TABLE "auction_vehicles" ADD CONSTRAINT "auction_vehicles_auction_id_fkey" FOREIGN KEY (auction_id) REFERENCES auctions(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'auction_vehicles_inventory_item_id_fkey') THEN ALTER TABLE "auction_vehicles" ADD CONSTRAINT "auction_vehicles_inventory_item_id_fkey" FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'buyer_offer_review_items_buyer_offer_review_id_fkey') THEN ALTER TABLE "buyer_offer_review_items" ADD CONSTRAINT "buyer_offer_review_items_buyer_offer_review_id_fkey" FOREIGN KEY (buyer_offer_review_id) REFERENCES buyer_offer_reviews(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'buyer_offer_review_items_dealer_submission_id_fkey') THEN ALTER TABLE "buyer_offer_review_items" ADD CONSTRAINT "buyer_offer_review_items_dealer_submission_id_fkey" FOREIGN KEY (dealer_submission_id) REFERENCES dealer_offer_submissions(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'buyer_offer_reviews_vehicle_offer_id_fkey') THEN ALTER TABLE "buyer_offer_reviews" ADD CONSTRAINT "buyer_offer_reviews_vehicle_offer_id_fkey" FOREIGN KEY (vehicle_offer_id) REFERENCES vehicle_offers(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'content_derivatives_post_id_fkey') THEN ALTER TABLE "content_derivatives" ADD CONSTRAINT "content_derivatives_post_id_fkey" FOREIGN KEY (post_id) REFERENCES social_posts(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'content_derivatives_signal_id_fkey') THEN ALTER TABLE "content_derivatives" ADD CONSTRAINT "content_derivatives_signal_id_fkey" FOREIGN KEY (signal_id) REFERENCES topic_signals(id) ON DELETE SET NULL; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'creator_attributions_creator_id_fkey') THEN ALTER TABLE "creator_attributions" ADD CONSTRAINT "creator_attributions_creator_id_fkey" FOREIGN KEY (creator_id) REFERENCES creator_network(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'dealer_offer_submissions_dealer_id_fkey') THEN ALTER TABLE "dealer_offer_submissions" ADD CONSTRAINT "dealer_offer_submissions_dealer_id_fkey" FOREIGN KEY (dealer_id) REFERENCES dealers(id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'dealer_offer_submissions_vehicle_offer_id_fkey') THEN ALTER TABLE "dealer_offer_submissions" ADD CONSTRAINT "dealer_offer_submissions_vehicle_offer_id_fkey" FOREIGN KEY (vehicle_offer_id) REFERENCES vehicle_offers(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'dealer_outreach_log_dealer_prospect_id_fkey') THEN ALTER TABLE "dealer_outreach_log" ADD CONSTRAINT "dealer_outreach_log_dealer_prospect_id_fkey" FOREIGN KEY (dealer_prospect_id) REFERENCES dealer_prospects(id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'dealer_prospects_buyer_opp_id_fkey') THEN ALTER TABLE "dealer_prospects" ADD CONSTRAINT "dealer_prospects_buyer_opp_id_fkey" FOREIGN KEY (buyer_opp_id) REFERENCES buyer_opportunities(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'outside_auction_invites_auction_id_fkey') THEN ALTER TABLE "outside_auction_invites" ADD CONSTRAINT "outside_auction_invites_auction_id_fkey" FOREIGN KEY (auction_id) REFERENCES auctions(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'outside_auction_invites_offer_id_fkey') THEN ALTER TABLE "outside_auction_invites" ADD CONSTRAINT "outside_auction_invites_offer_id_fkey" FOREIGN KEY (offer_id) REFERENCES offers(id) ON UPDATE CASCADE ON DELETE SET NULL; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'revenue_attributions_post_id_fkey') THEN ALTER TABLE "revenue_attributions" ADD CONSTRAINT "revenue_attributions_post_id_fkey" FOREIGN KEY (post_id) REFERENCES social_posts(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'social_performance_post_id_fkey') THEN ALTER TABLE "social_performance" ADD CONSTRAINT "social_performance_post_id_fkey" FOREIGN KEY (post_id) REFERENCES social_posts(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'social_posts_franchise_id_fkey') THEN ALTER TABLE "social_posts" ADD CONSTRAINT "social_posts_franchise_id_fkey" FOREIGN KEY (franchise_id) REFERENCES content_franchises(id) ON DELETE SET NULL; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'social_posts_signal_id_fkey') THEN ALTER TABLE "social_posts" ADD CONSTRAINT "social_posts_signal_id_fkey" FOREIGN KEY (signal_id) REFERENCES topic_signals(id) ON DELETE SET NULL; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'social_videos_post_id_fkey') THEN ALTER TABLE "social_videos" ADD CONSTRAINT "social_videos_post_id_fkey" FOREIGN KEY (post_id) REFERENCES social_posts(id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'vehicle_offer_dealer_invites_submission_id_fkey') THEN ALTER TABLE "vehicle_offer_dealer_invites" ADD CONSTRAINT "vehicle_offer_dealer_invites_submission_id_fkey" FOREIGN KEY (submission_id) REFERENCES dealer_offer_submissions(id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'vehicle_offer_dealer_invites_vehicle_offer_id_fkey') THEN ALTER TABLE "vehicle_offer_dealer_invites" ADD CONSTRAINT "vehicle_offer_dealer_invites_vehicle_offer_id_fkey" FOREIGN KEY (vehicle_offer_id) REFERENCES vehicle_offers(id) ON DELETE CASCADE; END IF; END $$;
