// AMIPS Phase 2 — batch generation cron.
//
// Pulls the highest-priority pending queue items and generates an AMIPS page
// for each, narrating only real intelligence data. Scheduled three times a day
// (06:00 / 14:00 / 22:00 UTC); at ~17 items/run that is ~50 pages/day, the
// Stage 1 target. Raise BATCH_LIMIT to 34/run for Stage 2 (100/day) and 100/run
// for Stage 3 (300/day) once indexation is proven.

import { logger } from "@/lib/logger";
import { authorizeCronRequest } from "@/lib/security/cron-auth";
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { generateAmipsPage } from "@/lib/amips/amips-generator";
import { withCronRun } from "@/lib/services/monitoring/cron-monitor.service";

// Stage 1 batch size. 3 runs/day x 17 ≈ 50 pages/day.
const BATCH_LIMIT = 17;
// Rate-limit spacing between Groq calls.
const DELAY_MS = 1000;

// Allow up to ~5 minutes — 17 generations with 1s spacing plus model latency.
export const maxDuration = 300;

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

export async function GET(request: NextRequest) {
  const cronAuth = authorizeCronRequest(request);
  if (cronAuth) return cronAuth;

  const run = await withCronRun("amips-generate", async () => {
  // Highest-priority pending vehicle-backed items (Tier A has no vehicle and is
  // generated by a separate evergreen path).
  const items = await prisma.contentQueue.findMany({
    where: { status: "pending", make: { not: null }, model: { not: null } },
    orderBy: { priorityScore: "desc" },
    take: BATCH_LIMIT,
  });

  let generated = 0;
  let published = 0;
  let reviewNeeded = 0;
  let failed = 0;
  let pendingEnrichment = 0;

  for (const item of items) {
    try {
      const result = await generateAmipsPage(item);
      generated += 1;
      if (result.status === "published") published += 1;
      else if (result.status === "review_needed") reviewNeeded += 1;
      else if (result.status === "failed") failed += 1;
      else if (result.status === "pending_enrichment") pendingEnrichment += 1;
    } catch (err) {
      failed += 1;
      logger.error(
        `[amips-cron] generation threw for queue ${item.id}:`,
        err,
      );
      await prisma.contentQueue
        .update({
          where: { id: item.id },
          data: {
            status: "failed",
            attempts: { increment: 1 },
            failureReason: `Unhandled error: ${String(err)}`,
          },
        })
        .catch(() => undefined);
    }
    await sleep(DELAY_MS);
  }

  const summary = {
    considered: items.length,
    generated,
    published,
    reviewNeeded,
    failed,
    pendingEnrichment,
    timestamp: new Date().toISOString(),
  };
  logger.info("[amips-cron]", JSON.stringify(summary));

  return summary;
  });
  if (!run.ok) return NextResponse.json({ success: false, error: "amips-generate_failed" }, { status: 500 });

  return NextResponse.json({ success: true, data: run.result });
}
