-- AutoLenis Wave 1 (W1-B) — Privatize sensitive document buckets
--
-- These five Supabase Storage buckets hold sensitive buyer/dealer material
-- (identity & financial documents, insurance proofs, pre-approval letters,
-- signed/uploaded dealer contracts). They were provisioned as PUBLIC, so any
-- object URL was permanently readable by anyone who obtained (or guessed) it.
--
-- After this change the application persists the bare storage PATH and serves
-- reads via short-lived signed URLs generated by the service role at read time
-- (see lib/services/documents/storage-links.ts and the authorized read paths).
--
-- Setting `public = false` is authoritative: Supabase serves the public object
-- endpoint based on the bucket-level `public` flag. Service-role signed URLs are
-- unaffected (the service role bypasses storage RLS), so authorized reads keep
-- working. Existing rows that still store a full public URL keep working too —
-- extractStoragePath() recovers the path from them at read time.
--
-- Idempotent: safe to re-run. Bucket ids are enumerated verbatim from the upload
-- routes (BUCKET constants).

UPDATE storage.buckets
SET public = false
WHERE id IN (
  'buyer-documents',    -- app/api/buyer/documents/upload/route.ts
  'insurance-proofs',   -- app/api/buyer/insurance/upload-proof/route.ts
  'prequal-letters',    -- app/api/buyer/requests/financing/upload-letter/route.ts (+ public/request-vehicle)
  'dealer-documents',   -- app/api/dealer/documents/upload/route.ts
  'dealer-contracts'    -- app/api/dealer/contracts/upload-file/route.ts
);

-- Verification (run manually, expect public = false for all five):
--   SELECT id, public FROM storage.buckets
--   WHERE id IN ('buyer-documents','insurance-proofs','prequal-letters','dealer-documents','dealer-contracts');
--
-- If any custom "public read" policy was ever added to storage.objects for these
-- buckets, review and remove it as well — the bucket flip covers the default
-- public endpoint, but an explicit permissive SELECT policy would still expose
-- objects to the anon role. No such policy is created by this codebase.
