// AMIPS Phase 2 — page data assembler.
//
// The cardinal rule of AMIPS: "No data populated = no article generated. Ever."
// This module gathers every fact a page is allowed to narrate from the
// intelligence databases, enforces the freshness gates, and returns a single
// assembled object — or null when the required data is missing or stale (the
// signal to skip the queue item and flag it for enrichment).
//
// The AI never queries the databases. It only ever sees the object this builds.

import { prisma } from "@/lib/prisma";
import type { ContentQueue } from "@prisma/client";
import {
  computeMarketScore,
  type MarketScoreResult,
  type NegotiationDifficulty,
} from "@/lib/amips/market-score.service";

// Tiers that require local market + dealer data (Metro, Transaction, Dealer).
const METRO_TIERS = new Set(["C", "D", "E"]);

// Freshness windows (days) per the AMIPS quality gate.
export const FRESHNESS_DAYS = {
  vehicle: 180,
  dealer: 90,
  market: 30,
} as const;

export type AmipsCtaType = "request_offers" | "join_waitlist";

// The vehicle facts the narrator is allowed to use.
export interface AssembledVehicle {
  make: string;
  model: string;
  trim: string | null;
  year: number;
  msrpCents: number;
  fairMarketLowCents: number;
  fairMarketHighCents: number;
  aggressiveTargetCents: number;
  activeIncentives: string | null;
  incentivesExpiresAt: Date | null;
  financingNotes: string | null;
  negotiationDifficulty: NegotiationDifficulty;
}

// The market facts (Tier C/D/E only).
export interface AssembledMarket {
  metro: string;
  state: string;
  dealerCount: number;
}

export interface AmipsPageData {
  tier: string;
  keywordTarget: string;
  vehicle: AssembledVehicle;
  market?: AssembledMarket;
  marketScore?: MarketScoreResult;
  ctaType: AmipsCtaType;
  dealerCount: number; // 0 when no dealers in market (or non-metro tier)
  dataTokens: string[]; // real numbers available to embed in the article
  vehicleDataAsOf: Date;
  dealerDataAsOf?: Date;
  marketDataAsOf?: Date;
}

function isFresh(asOf: Date, withinDays: number): boolean {
  const ageMs = Date.now() - asOf.getTime();
  return ageMs <= withinDays * 24 * 60 * 60 * 1000;
}

function dollars(cents: number): string {
  return `$${Math.round(cents / 100).toLocaleString("en-US")}`;
}

/**
 * Assemble every fact a page is allowed to narrate, or return null when the
 * required data is missing/stale. A null result means: skip this queue item and
 * mark it pending_enrichment — never generate a page from incomplete data.
 */
export async function assembleAmipsPageData(
  queueItem: ContentQueue,
): Promise<AmipsPageData | null> {
  const tier = queueItem.contentTier;

  if (!queueItem.make || !queueItem.model) {
    // Tier A (no vehicle) is generated by a separate evergreen path — the data
    // narrator only handles vehicle-backed tiers (B–F).
    return null;
  }

  // 1 — Vehicle Intelligence. Pick the base trim (lowest MSRP) for the model.
  const vehicleRow = await prisma.vehicleIntelligence.findFirst({
    where: { make: queueItem.make, model: queueItem.model },
    orderBy: { msrpCents: "asc" },
  });
  if (!vehicleRow) return null;

  // Freshness gate — vehicle data within 180 days (all tiers).
  if (!isFresh(vehicleRow.lastUpdated, FRESHNESS_DAYS.vehicle)) return null;

  const vehicle: AssembledVehicle = {
    make: vehicleRow.make,
    model: vehicleRow.model,
    trim: vehicleRow.trim,
    year: vehicleRow.year,
    msrpCents: vehicleRow.msrpCents,
    fairMarketLowCents: vehicleRow.fairMarketLowCents,
    fairMarketHighCents: vehicleRow.fairMarketHighCents,
    aggressiveTargetCents: vehicleRow.aggressiveTargetCents,
    activeIncentives: vehicleRow.activeIncentives,
    incentivesExpiresAt: vehicleRow.incentivesExpiresAt,
    financingNotes: vehicleRow.financingNotes,
    negotiationDifficulty:
      vehicleRow.negotiationDifficulty as NegotiationDifficulty,
  };

  // Base data tokens — present for every vehicle-backed tier.
  const dataTokens: string[] = [
    dollars(vehicle.msrpCents),
    dollars(vehicle.fairMarketLowCents),
    dollars(vehicle.fairMarketHighCents),
    dollars(vehicle.aggressiveTargetCents),
  ];

  // Tier B (and any other non-metro vehicle tier) stops here — no market.
  if (!METRO_TIERS.has(tier)) {
    return {
      tier,
      keywordTarget: queueItem.keywordTarget,
      vehicle,
      ctaType: "join_waitlist", // no dealer context at the vehicle-authority tier
      dealerCount: 0,
      dataTokens,
      vehicleDataAsOf: vehicleRow.lastUpdated,
    };
  }

  // Metro tiers require a metro on the queue item.
  if (!queueItem.metro) return null;

  // 2 — Market Intelligence for the metro (also the market-freshness source).
  const marketRow = await prisma.marketIntelligence.findFirst({
    where: { metroName: queueItem.metro },
  });
  if (!marketRow) return null;
  if (!isFresh(marketRow.lastUpdated, FRESHNESS_DAYS.market)) return null;

  // 3 — Pre-computed Market Score (AMIPS-1 batch). Carries the in-metro,
  // same-brand dealer count and the defensible score. Absent => skip.
  const scoreRow = await prisma.amipsMarketScore.findUnique({
    where: {
      make_model_metro: {
        make: vehicle.make,
        model: vehicle.model,
        metro: queueItem.metro,
      },
    },
  });
  if (!scoreRow) return null;

  // The score was computed from dealer data; its timestamp is the dealer
  // freshness source for this combination.
  if (!isFresh(scoreRow.computedAt, FRESHNESS_DAYS.dealer)) return null;

  const dealerCount = scoreRow.dealerCount;

  // Prefer the stored score; recompute as a fallback if the JSON is unusable.
  let marketScore: MarketScoreResult;
  try {
    marketScore = JSON.parse(scoreRow.scoreJson) as MarketScoreResult;
    if (typeof marketScore.overallBuyerAdvantage !== "number") {
      throw new Error("invalid stored score");
    }
  } catch {
    const inv = marketRow.inventoryScore ?? 5;
    marketScore = computeMarketScore({
      dealersWithin30mi: dealerCount,
      inventorySignal: inv <= 3 ? "low" : inv >= 8 ? "high" : "normal",
      negotiationDifficulty: vehicle.negotiationDifficulty,
      incentiveStatus: vehicle.activeIncentives ? "some" : "none",
    });
  }

  // Market-derived data tokens.
  dataTokens.push(
    String(dealerCount),
    marketScore.overallBuyerAdvantage.toFixed(1),
    marketScore.dealerCompetition.toFixed(1),
    marketScore.negotiationOpportunity.toFixed(1),
  );

  return {
    tier,
    keywordTarget: queueItem.keywordTarget,
    vehicle,
    market: {
      metro: queueItem.metro,
      state: queueItem.state ?? marketRow.state,
      dealerCount,
    },
    marketScore,
    // CTA must match dealer supply state (Quality Gate 4).
    ctaType: dealerCount >= 3 ? "request_offers" : "join_waitlist",
    dealerCount,
    dataTokens,
    vehicleDataAsOf: vehicleRow.lastUpdated,
    dealerDataAsOf: scoreRow.computedAt,
    marketDataAsOf: marketRow.lastUpdated,
  };
}

// Small formatting helpers reused by the prompt builder.
export const fmt = { dollars };
