// AMIPS Phase 2 — page data assembler.
//
// The cardinal rule of AMIPS: "No data populated = no article generated. Ever."
// This module gathers every fact a page is allowed to narrate from the
// intelligence databases, enforces the freshness gates, and returns a single
// assembled object — or null when the required data is missing or stale (the
// signal to skip the queue item and flag it for enrichment).
//
// The AI never queries the databases. It only ever sees the object this builds.

import { prisma } from "@/lib/prisma";
import type { ContentQueue } from "@prisma/client";
import {
  computeMarketScore,
  type MarketScoreResult,
  type NegotiationDifficulty,
} from "@/lib/amips/market-score.service";
import { TIER_F_TRANSACTION_THRESHOLD } from "@/lib/amips/pipelines/tier-f-threshold.pipeline";

// Tiers that require local market + dealer data (Metro, Transaction, Dealer).
const METRO_TIERS = new Set(["C", "D", "E"]);

// Freshness windows (days) per the AMIPS quality gate.
export const FRESHNESS_DAYS = {
  vehicle: 180,
  dealer: 90,
  market: 30,
} as const;

export type AmipsCtaType = "request_offers" | "join_waitlist";

// The vehicle facts the narrator is allowed to use.
export interface AssembledVehicle {
  make: string;
  model: string;
  trim: string | null;
  year: number;
  msrpCents: number;
  fairMarketLowCents: number;
  fairMarketHighCents: number;
  aggressiveTargetCents: number;
  activeIncentives: string | null;
  incentivesExpiresAt: Date | null;
  financingNotes: string | null;
  negotiationDifficulty: NegotiationDifficulty;
}

// The market facts (Tier C/D/E only).
export interface AssembledMarket {
  metro: string;
  state: string;
  dealerCount: number;
}

// Verified AutoLenis transaction facts (Tier F only). These are real,
// observed values — never estimates — drawn from autolenis_intelligence after
// the 50-transaction gate has been crossed for this vehicle + metro.
export interface AssembledTierF {
  transactionCount: number;
  dealerResponseRatePct: number | null; // e.g. 73
  avgOffersPerBuyer: number | null;
  medianTimeToBestOfferHours: number | null;
  periodMonth: string;
  dataAsOf: Date;
}

export interface AmipsPageData {
  tier: string;
  keywordTarget: string;
  vehicle: AssembledVehicle;
  market?: AssembledMarket;
  marketScore?: MarketScoreResult;
  tierF?: AssembledTierF;
  ctaType: AmipsCtaType;
  dealerCount: number; // 0 when no dealers in market (or non-metro tier)
  dataTokens: string[]; // real numbers available to embed in the article
  vehicleDataAsOf: Date;
  dealerDataAsOf?: Date;
  marketDataAsOf?: Date;
}

function isFresh(asOf: Date, withinDays: number): boolean {
  const ageMs = Date.now() - asOf.getTime();
  return ageMs <= withinDays * 24 * 60 * 60 * 1000;
}

function dollars(cents: number): string {
  return `$${Math.round(cents / 100).toLocaleString("en-US")}`;
}

/**
 * Assemble every fact a page is allowed to narrate, or return null when the
 * required data is missing/stale. A null result means: skip this queue item and
 * mark it pending_enrichment — never generate a page from incomplete data.
 */
export async function assembleAmipsPageData(
  queueItem: ContentQueue,
): Promise<AmipsPageData | null> {
  const tier = queueItem.contentTier;

  if (!queueItem.make || !queueItem.model) {
    // Tier A (no vehicle) is generated by a separate evergreen path — the data
    // narrator only handles vehicle-backed tiers (B–F).
    return null;
  }

  // 1 — Vehicle Intelligence. Pick the base trim (lowest MSRP) for the model.
  const vehicleRow = await prisma.vehicleIntelligence.findFirst({
    where: { make: queueItem.make, model: queueItem.model },
    orderBy: { msrpCents: "asc" },
  });
  if (!vehicleRow) return null;

  // Freshness gate — vehicle data within 180 days (all tiers).
  if (!isFresh(vehicleRow.lastUpdated, FRESHNESS_DAYS.vehicle)) return null;

  const vehicle: AssembledVehicle = {
    make: vehicleRow.make,
    model: vehicleRow.model,
    trim: vehicleRow.trim,
    year: vehicleRow.year,
    msrpCents: vehicleRow.msrpCents,
    fairMarketLowCents: vehicleRow.fairMarketLowCents,
    fairMarketHighCents: vehicleRow.fairMarketHighCents,
    aggressiveTargetCents: vehicleRow.aggressiveTargetCents,
    activeIncentives: vehicleRow.activeIncentives,
    incentivesExpiresAt: vehicleRow.incentivesExpiresAt,
    financingNotes: vehicleRow.financingNotes,
    negotiationDifficulty:
      vehicleRow.negotiationDifficulty as NegotiationDifficulty,
  };

  // Base data tokens — present for every vehicle-backed tier.
  const dataTokens: string[] = [
    dollars(vehicle.msrpCents),
    dollars(vehicle.fairMarketLowCents),
    dollars(vehicle.fairMarketHighCents),
    dollars(vehicle.aggressiveTargetCents),
  ];

  // Tier F — proprietary, transaction-backed. Narrated from verified AutoLenis
  // data, gated on at least 50 completed transactions for this vehicle + metro.
  if (tier === "F") {
    if (!queueItem.metro) return null;

    const al = await prisma.autolenisIntelligence.findFirst({
      where: {
        metro: queueItem.metro,
        vehicleMake: vehicle.make,
        vehicleModel: vehicle.model,
      },
      orderBy: { transactionCount: "desc" },
    });
    // Hard gate: no Tier F page before the 50-transaction threshold.
    if (!al || al.transactionCount < TIER_F_TRANSACTION_THRESHOLD) return null;

    // Median time to the best (final) offer, computed from the real transaction
    // records — honest data, not an estimate.
    const txns = await prisma.marketplaceIntelligence.findMany({
      where: {
        metro: queueItem.metro,
        vehicleMake: vehicle.make,
        vehicleModel: vehicle.model,
        buyerAcceptedOffer: true,
        timeToFinalOfferMinutes: { not: null },
      },
      select: { timeToFinalOfferMinutes: true },
    });
    const times = txns
      .map((t) => t.timeToFinalOfferMinutes as number)
      .sort((a, b) => a - b);
    const medianMin = times.length
      ? times[Math.floor((times.length - 1) / 2)]
      : null;

    const tierF: AssembledTierF = {
      transactionCount: al.transactionCount,
      dealerResponseRatePct:
        al.dealerResponseRate != null
          ? Math.round(al.dealerResponseRate * 100)
          : null,
      avgOffersPerBuyer:
        al.avgOffersReceived != null
          ? Math.round(al.avgOffersReceived * 10) / 10
          : null,
      medianTimeToBestOfferHours:
        medianMin != null ? Math.round((medianMin / 60) * 10) / 10 : null,
      periodMonth: al.periodMonth,
      dataAsOf: al.lastUpdated,
    };

    // Pre-computed Market Score for context, if available (not freshness-gated
    // for Tier F — the proven transaction record is the source of authority).
    const scoreRow = await prisma.amipsMarketScore.findUnique({
      where: {
        make_model_metro: {
          make: vehicle.make,
          model: vehicle.model,
          metro: queueItem.metro,
        },
      },
    });

    let marketScore: MarketScoreResult | undefined;
    if (scoreRow) {
      try {
        const parsed = JSON.parse(scoreRow.scoreJson) as MarketScoreResult;
        if (typeof parsed.overallBuyerAdvantage === "number") {
          marketScore = parsed;
        }
      } catch {
        marketScore = undefined;
      }
    }

    const marketRow = await prisma.marketIntelligence.findFirst({
      where: { metroName: queueItem.metro },
    });
    // Completed transactions prove active, competing dealers exist.
    const dealerCount =
      scoreRow?.dealerCount ??
      Math.max(3, Math.round(tierF.avgOffersPerBuyer ?? 3));

    // Verified Tier F data tokens — all real, observed numbers.
    dataTokens.push(String(tierF.transactionCount));
    if (tierF.dealerResponseRatePct != null) {
      dataTokens.push(`${tierF.dealerResponseRatePct}%`);
    }
    if (tierF.avgOffersPerBuyer != null) {
      dataTokens.push(String(tierF.avgOffersPerBuyer));
    }
    if (tierF.medianTimeToBestOfferHours != null) {
      dataTokens.push(`${tierF.medianTimeToBestOfferHours} hours`);
    }

    return {
      tier,
      keywordTarget: queueItem.keywordTarget,
      vehicle,
      market: {
        metro: queueItem.metro,
        state: queueItem.state ?? marketRow?.state ?? "",
        dealerCount,
      },
      marketScore,
      tierF,
      ctaType: "request_offers", // proven, active, competing dealers
      dealerCount,
      dataTokens,
      vehicleDataAsOf: vehicleRow.lastUpdated,
    };
  }

  // Tier B (and any other non-metro vehicle tier) stops here — no market.
  if (!METRO_TIERS.has(tier)) {
    return {
      tier,
      keywordTarget: queueItem.keywordTarget,
      vehicle,
      ctaType: "join_waitlist", // no dealer context at the vehicle-authority tier
      dealerCount: 0,
      dataTokens,
      vehicleDataAsOf: vehicleRow.lastUpdated,
    };
  }

  // Metro tiers require a metro on the queue item.
  if (!queueItem.metro) return null;

  // 2 — Market Intelligence for the metro (also the market-freshness source).
  const marketRow = await prisma.marketIntelligence.findFirst({
    where: { metroName: queueItem.metro },
  });
  if (!marketRow) return null;
  if (!isFresh(marketRow.lastUpdated, FRESHNESS_DAYS.market)) return null;

  // 3 — Pre-computed Market Score (AMIPS-1 batch). Carries the in-metro,
  // same-brand dealer count and the defensible score. Absent => skip.
  const scoreRow = await prisma.amipsMarketScore.findUnique({
    where: {
      make_model_metro: {
        make: vehicle.make,
        model: vehicle.model,
        metro: queueItem.metro,
      },
    },
  });
  if (!scoreRow) return null;

  // The score was computed from dealer data; its timestamp is the dealer
  // freshness source for this combination.
  if (!isFresh(scoreRow.computedAt, FRESHNESS_DAYS.dealer)) return null;

  const dealerCount = scoreRow.dealerCount;

  // Prefer the stored score; recompute as a fallback if the JSON is unusable.
  let marketScore: MarketScoreResult;
  try {
    marketScore = JSON.parse(scoreRow.scoreJson) as MarketScoreResult;
    if (typeof marketScore.overallBuyerAdvantage !== "number") {
      throw new Error("invalid stored score");
    }
  } catch {
    const inv = marketRow.inventoryScore ?? 5;
    marketScore = computeMarketScore({
      dealersWithin30mi: dealerCount,
      inventorySignal: inv <= 3 ? "low" : inv >= 8 ? "high" : "normal",
      negotiationDifficulty: vehicle.negotiationDifficulty,
      incentiveStatus: vehicle.activeIncentives ? "some" : "none",
    });
  }

  // Market-derived data tokens.
  dataTokens.push(
    String(dealerCount),
    marketScore.overallBuyerAdvantage.toFixed(1),
    marketScore.dealerCompetition.toFixed(1),
    marketScore.negotiationOpportunity.toFixed(1),
  );

  return {
    tier,
    keywordTarget: queueItem.keywordTarget,
    vehicle,
    market: {
      metro: queueItem.metro,
      state: queueItem.state ?? marketRow.state,
      dealerCount,
    },
    marketScore,
    // CTA must match dealer supply state (Quality Gate 4).
    ctaType: dealerCount >= 3 ? "request_offers" : "join_waitlist",
    dealerCount,
    dataTokens,
    vehicleDataAsOf: vehicleRow.lastUpdated,
    dealerDataAsOf: scoreRow.computedAt,
    marketDataAsOf: marketRow.lastUpdated,
  };
}

// Small formatting helpers reused by the prompt builder.
export const fmt = { dollars };
